[RFC] util-linux: exclude bin from default PATH
void-linux/void-packages pull request #14267
Opened 2019-09-06 18:19 UTC by Chocimier

/bin is still added to PATH by /etc/profile, but after /usr/bin.
This makes `which` return real file instead of symlink.

2019-09-09 11:54 UTC, Piraty commented
It's the other way around you mean? `which ls` gives `/bin/ls` (which is the symlink) but should be `/usr/bin/ls` (which is the real file).
I stumbled on this before, as `xbps-query -o $(which ls)` fails because of this.

2019-09-09 17:04 UTC, Chocimier commented
> It's the other way around you mean? |which ls| gives |/bin/ls| (which is the symlink) but should be |/usr/bin/ls| (which is the real file).

Yes, the effect of that change is that /usr/bin/ls is returned.

On tty at least, because lxdm sets PATH independently. Would we need to patch each display manager?

2021-01-29 02:50 UTC, ericonr commented
From `./configure --help`:

```
 --enable-usrdir-path    use only /usr paths in PATH env. variable
                          (recommended on systems with /bin -> /usr/bin
                          symlinks)
```

I think we should add this change, but also fix `/etc/profile` to put `/usr/bin` in front of everything.

2021-01-29 08:23 UTC, Chocimier commented
/etc/profile already have /usr/bin in front of /bin. Problem here is that /etc/profile appends to PATH passed to shell from it's parent, and every parent (atty, ssh, different graphical login managers) passes something different, usually not fitting usrmerge.

Unless there is vaild usecase for preserving parent's path, it could be reset by /etc/profile instead of patching all possible parents.

2021-01-29 18:52 UTC, Chocimier commented
#6233 states it is for WSL, optimizing for that doesn't convince me.
Is it still relevant with WSL2?

2021-02-16 05:38 UTC, ericonr commented
It seems @am11's https://github.com/am11/VoidWSL project is still active, at least...

2021-02-16 05:54 UTC, am11 commented
Yup, we are actively providing https://git.io/voidwsl and https://git.io/voidmuslwsl from GitHub releases. It is mainly the Void Linux official rootf image with a [slim WSL C binding](https://github.com/yuk7/wsldl/blob/main/main.c).

2021-03-05 04:47 UTC, ericonr commented
I'm a bit confused now, isn't `which` provided by the `which` package, which is completely separate from `util-linux`?

2021-03-30 21:14 UTC, Chocimier commented
`which` looks for executable in directories of `$PATH`, in order, as passed to it by shell.
Shell build `$PATH` as specified in /etc/profile, that is by appending to `$PATH` passed from parent process.
Parent process may be agetty from `util-linux`, ssh, graphical login manager like lxdm.
Order of /etc/profile is right, but all directories there are read by `which` after directories from parent, that for some parents are symlinks, leading to reporting symlink directories rather than real ones.

Given there is some usage of not reset PATH in profile, I would like to sync defaults of login managers.

2022-04-22 00:26 UTC, Piraty commented
Let's resurrect this

2022-05-04 19:33 UTC, Chocimier commented
@Piraty, rebased. Would you like to patch services you use?

2022-08-24 19:15 UTC, 0x5c commented
I use KDE from SDDM, and the default path is `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin`.
It seems correct already but different than the path specified in this PR.

2023-06-26 22:12 UTC, Chocimier commented
As @leahneukirchen already started doing this in 3b9cc95ac4157290d16dc46fe087b6072367a991, I will patch few more *dm and merge.

2023-06-27 11:21 UTC, leahneukirchen commented
The PR title should be adjusted.

2023-06-27 11:23 UTC, leahneukirchen requested changes

2023-06-27 11:23 UTC, leahneukirchen commented on srcpkgs/openssh/template
> + --with-default-path=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
Why put /usr/bin before /usr/sbin, yet /sbin before /bin? IMO sbin always should go first, as on classic Unix.

2023-06-27 11:23 UTC, leahneukirchen commented on srcpkgs/util-linux/patches/default-PATH.patch
> ++# define _PATH_DEFPATH	        "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin"
Same here.

2023-06-27 11:23 UTC, leahneukirchen commented on srcpkgs/util-linux/patches/default-PATH.patch
> ++# define _PATH_DEFPATH_ROOT	"/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin"
And here.

2023-06-27 11:23 UTC, leahneukirchen commented on srcpkgs/sddm/patches/0.19.0--default-path.patch
> ++            Entry(DefaultPath,         QString,     _S("/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin"), _S("Default $PATH for logged in users"));
And here.

2023-07-01 20:27 UTC, Chocimier commented
/usr/bin goes before /usr/sbin to make `command -v`, zsh `=` expansion and so on return real path of command, so it is more useful, e.g. can be passed to `xbps-query -o`. It is the order given in /etc/profile as well. Using real path is main reason to introduce changes here, as it worked until #6233..

2023-07-01 21:26 UTC, leahneukirchen commented
This makes sense, thanks for pointing it out.

2023-07-01 21:26 UTC, leahneukirchen approved these changes

2023-07-03 16:48 UTC, merged