New package: OpenRGB-0.2
void-linux/void-packages pull request #22588
Opened 2020-06-04 17:00 UTC by NeelChotai

2020-06-04 18:55 UTC, DirectorX commented
Is this software have daemon mode?

2020-06-04 19:02 UTC, DirectorX commented
You may want to set the `archs=` variable, those RGB controllers are tided to x86 systems anyway.

2020-06-04 19:19 UTC, NeelChotai commented
> 
> 
> Is this software have daemon mode?

I believe this will be a feature in the next update, thus far I've been using the CLI functionality in my window manager launch script.

> 
> 
> You may want to set the `archs=` variable, those RGB controllers are tided to x86 systems anyway.

I considered this but the program has support for USB RGB devices too. I'm not sure about inherent incompatibilities with other architectures.

Something seems to be wrong with Travis - it's manually compiling dependencies. I'll have another crack at this soon.

2020-06-04 19:40 UTC, pullmoll commented
@DirectorX there is no need to restrict with `archs=...` just because (currently) a package is useful only for specific architectures. There may be (1) use cases which do not require a device, or (2) cross platform use like with e.g. `mac-fdisk` which could be used to edit an Apple partition table on a device connected to an x86_64 system.

The general rule for using `archs=...` is this: Specify `__`**only**`__` in case a package contains e.g. assembler code for just specific target architectures and as a result cannot be built for other platforms. If it can be built, do not restrict archs.

2020-07-09 20:01 UTC, Eluminae commented
maybe we should setup the udev module as https://gitlab.com/CalcProgrammer1/OpenRGB#usb-access-1

2020-07-09 20:53 UTC, NeelChotai commented
> 
> 
> maybe we should setup the udev module as https://gitlab.com/CalcProgrammer1/OpenRGB#usb-access-1

I omitted this since it wasn't released in 0.2 but I will add it in manually.

I'll do so when I have a go at fixing cross tonight.

2020-07-10 00:29 UTC, NeelChotai commented
Compiles successfully and confirmed working on x86_64.

Version 0.2 used system groups to control RGB which has been superseded by the udev rules in master. If anyone else can test and ensure that OpenRGB works without root permissions, this is good to merge.

2020-07-23 21:46 UTC, NeelChotai commented
Updated to 0.3, this should be ready to merge.

2020-10-06 12:42 UTC, Piraty requested changes
1. `0.4` is out
1. please name it all lowercase (see [repology](https://repology.org/projects/?search=OpenRGB))
1. take some inspiration from #24150.

2020-10-06 18:03 UTC, NeelChotai commented
>     1. `0.4` is out
> 
>     2. please name it all lowercase (see [repology](https://repology.org/projects/?search=OpenRGB))
> 
>     3. take some inspiration from #24150.

Updated to 0.4, thanks for the reminder.

I'm going by the Manual, the tar.gz is uppercase and packages in some other repos are uppercase too. If you believe renaming it lowercase is still preferable, let me know and I'll change it.

Added the service and log files from #24150, thank you @cpixl.

2020-10-15 10:28 UTC, Piraty commented
please lowercase it, else it's good to merge

2020-12-14 18:19 UTC, NeelChotai commented
@Piraty the OpenRGB developers have made the decision to lowercase the binary so I've taken the liberty of lowercasing everything for this pull request, it should be good to merge now.

2020-12-17 22:52 UTC, Piraty requested changes
else it's good to go

2020-12-17 22:52 UTC, Piraty commented on srcpkgs/openrgb/template
> +	sed -i 's|rules.path=/lib|rules.path=/usr/lib|g' OpenRGB.pro
vsed please

2020-12-17 22:53 UTC, closed without merging