python3-trimesh: update to 3.7.5.
void-linux/void-packages pull request #23338
Opened 2020-07-01 03:48 UTC by karl-nilsson

2020-07-01 08:28 UTC, Piraty commented
xlint: `Place checkdepends= after depends=`

2020-07-01 22:12 UTC, karl-nilsson commented
@Piraty fixed, thanks

2020-07-03 18:55 UTC, Chocimier commented
> TypeError: don't know how to make test from: <trimesh.exceptions.ExceptionModule object at 0x7f76eb5ce520>

passes for you?

2020-07-12 08:34 UTC, Piraty commented
not for me

2020-07-12 18:48 UTC, karl-nilsson commented
> passes for you?

No, but the newest changes should (mostly) pass.
I'm working on packaging rtree

2020-08-03 08:26 UTC, Piraty commented
tests still don't pass, require [a few more modules](https://github.com/mikedh/trimesh/blob/5b3c5d4/setup.py#L31-L47)

2020-08-04 17:25 UTC, karl-nilsson commented
> tests still don't pass, require [a few more modules](https://github.com/mikedh/trimesh/blob/5b3c5d4/setup.py#L31-L47)

Strictly speaking, In order to pass all tests, all dependencies must be included:
https://github.com/mikedh/trimesh/issues/590#issuecomment-549457839

What's an acceptable solution: package all of requirements_easy, then have pytest do a conditional import? Or just package all requirements?

2020-08-10 23:57 UTC, Piraty commented
if it's not feasable to package the missing modules (and they're not required at runtime at all), i'd say skip `do_check` (but leave a comment).

2020-08-24 03:04 UTC, karl-nilsson commented
@Piraty I was able to package the remaining dependencies, and make check seems to work (albeit with warnings).
Let me know what you think.

2020-08-24 07:10 UTC, Piraty requested changes
looks good!

2020-08-24 07:10 UTC, Piraty commented on srcpkgs/python3-pycollada/template
> +#create_wrksrc=yes
please remove

2020-08-24 10:07 UTC, closed without merging