Etesync dav 0.20.0
void-linux/void-packages pull request #23908
Opened 2020-07-28 18:55 UTC by ProjectMoon

Continuation of https://github.com/void-linux/void-packages/pull/22810.

2020-07-28 18:55 UTC, ProjectMoon commented
Still working on implementing suggested changes from original PR.

2020-07-28 20:27 UTC, lemmi commented
So after thinking about this a little bit, we should follow @CameronNemo suggestion and only have a single `radicale` package. It's what we usually do and only in very specific cases do we manage multiple versions this way. Thanks for adopting the package.

2020-09-17 14:24 UTC, ahesford requested changes
#24945 comes closer to doing the right thing with `radicale`. Specifically, it seems there are some new access control files that should be installed, and you've dropped the service directory. Either merge the changes from that PR into this one (also addressing my issues there) or drop the `radicale` changes and wait for #24945 to be merged, leaving this PR to update only `etesync-dav`.

2020-09-17 14:24 UTC, ahesford commented on srcpkgs/radicale/template
> +provides="radicale-${version}_${revision}"
This line doesn't add value.

2020-09-17 14:46 UTC, ProjectMoon commented
Waiting for the other PR is definitely the best path for me. I don't really have time to deal with upgrading radicale at the same time.

2020-09-17 17:56 UTC, ahesford commented
`radicale` is in, so you can strip this down to the `etesync-dav` update only.

2020-10-18 14:15 UTC, closed without merging