nodejs build style
void-linux/void-packages pull request #23947
Opened 2020-07-30 09:19 UTC by selfisekai

2020-08-03 20:08 UTC, Chocimier commented
I do not want it as long as it install precompiled binaries, i. e. until #21758 is done and build style uses that.

2020-08-16 23:37 UTC, fosslinux commented
Can we revisit this?

2020-09-04 16:02 UTC, Anachron commented
We should export NODE_ENV=production, no?

2020-11-15 23:41 UTC, fosslinux commented
Ping

2020-12-30 07:19 UTC, the-maldridge commented
Looks good to me.  Needs docs to explain the new template variables that are supported by this build style and then it can be merged.  Ideally templates that can benefit from this style would be moved over to it as well.

2021-01-02 20:20 UTC, selfisekai commented
@the-maldridge I did some simple docs and merged all the changes from master (force-pushed, because I did `git pull --rebase` and the PR included like 10k commits from master), you can check it now.

2021-01-02 21:59 UTC, fosslinux commented
You need to rebase, not merge.

2021-01-02 22:20 UTC, the-maldridge requested changes
And you should address the rebase issue.

2021-01-02 22:20 UTC, the-maldridge commented on Manual.md
> +- `nodejs` For apps made in Node.js that get built with npm or yarn
I think the explanation of variables could be better formatted as a list.  Look at the python section starting on line 1504.

2021-01-29 03:00 UTC, ericonr commented on Manual.md
> +<a id="pkgs_nodejs"></a>
This needs to go on the table of contents at the start of the document.

2021-01-29 03:00 UTC, ericonr commented on Manual.md
> +	in your build script.
```suggestion
- `nodejs_install_script`: app installing script, which is unlikely to exist.
Most of the time, you will have to define your own `do_install`.
```

2021-01-29 03:00 UTC, ericonr commented on Manual.md
> +- `NODE_ENV`: set to `production` by default
it should be exported in the build style, otherwise just setting it won't affect the build.

2021-01-29 03:01 UTC, ericonr commented
To be honest, though, I'm not sure I entirely see the value in this... #23948 seems to have successfully completed CI even without having the build style there.

2021-01-29 05:03 UTC, fosslinux commented
@ericonr uh, there is a nodejs build style commit in that pr...

2021-01-29 05:18 UTC, ericonr commented
well, oops. Still, the template defines its own `do_build` and `do_install`.

2021-04-03 23:14 UTC, closed without merging