[WIP] New package: opencamlib-2019.07
void-linux/void-packages pull request #24529
Opened 2020-08-29 01:52 UTC by karl-nilsson

@Piraty the python bindings depend on vtk's python wrapper. How difficult would it be to enable that in vtk?

2020-08-29 02:50 UTC, ahesford commented
VTK python bindings in #24531

2020-08-30 11:16 UTC, fosslinux requested changes
doxygen seems to be needed in `hostmakedepends`, see the CI build

2020-08-30 12:59 UTC, karl-nilsson commented
> doxygen seems to be needed in `hostmakedepends`, see the CI build

Doxygen doesn't matter, because the current template doesn't build documentation.
It's failing because it can't find Python:
> -- Could NOT find Python3 (missing: Interpreter) (found version "3.8.5")
>    Reason given by package: 
>        Interpreter: Cannot run the interpreter "/usr/aarch64-linux-gnu/usr/bin/python3.8"

2020-08-31 00:50 UTC, ahesford commented
You at least want to add `python3` to `hostmakedepends` in addition to your `python3-devel` in `makedepends`.

2020-08-31 16:57 UTC, karl-nilsson commented
@ahesford that seems to have fixed it, thanks!

2020-08-31 17:13 UTC, closed without merging