Ledger autosync
void-linux/void-packages pull request #24756
Opened 2020-09-08 04:28 UTC by Vaelatern

Almost fully tested.

ofxhome works
ledger-autosync seems to work
ofxclient seems to work
ofxparse is deep in the dependency chain but I don't think I've tested it yet ("seems to work" above)

2021-01-29 00:53 UTC, ericonr commented
@Vaelatern ping

2021-01-29 06:00 UTC, Vaelatern commented
Can't think of why not merge it. Rebased and pushed to re-run CI.

2021-02-15 14:26 UTC, ericonr commented
Ping

2021-03-01 02:37 UTC, Vaelatern commented
pong

2022-04-19 02:17 UTC, Vaelatern commented
hrm, just another rebase and I'll test and push

2026-09-01 00:44 UTC, nazaradeh requested changes

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/ledger-autosync/template
> +version=1.0.2
```suggestion
version=1.2.0
```

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/ledger-autosync/template
> +depends="ofxclient"
```suggestion
build_style=python3-pep517
hostmakedepends="python3-poetry-core"
depends="ofxclient python3-lxml python3-ofxparse"
```

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/ledger-autosync/template
> +}
```suggestion
checksum=8621e23cc26b84a95409ee3e073e857a5c22bdd86125bdbe7ea60e4cc9d20cfc
```

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/python3-ofxparse/template
> +version=0.20
```suggestion
version=0.21
```

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/python3-ofxparse/template
> +depends="python3-BeautifulSoup4"
```suggestion
depends="python3-BeautifulSoup4 python3-lxml python3-six"
```

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/python3-ofxparse/template
> +checksum=eb45db5802938ac0ab3664418ca564619cc9e7ec6d301c1063ffc16e587ec37e
```suggestion
checksum=057ab68d31270dece4d1a47662096aa76341968aaee145ffc711cb44cbd5c4a7
```

2026-09-01 00:44 UTC, nazaradeh commented on srcpkgs/ledger-autosync/template
> +version=1.0.2
1.0.2 is no longer compatible with the latest version of python3. Want to give a shot at reviving this PR to clean up backlog.

2026-09-01 00:45 UTC, nazaradeh commented
Tested these changes myself by running it with a test .ofx file.

2026-09-02 03:27 UTC, Vaelatern commented
Go ahead and make a PR yourself, and @ me? @nazaradeh

2026-09-03 06:55 UTC, closed without merging