github-cli: update to 0.12.0.
void-linux/void-packages pull request #24775
Opened 2020-09-09 06:01 UTC by shizonic

2020-09-17 18:05 UTC, NeelChotai commented
1.0.0 is out.

2020-09-17 23:08 UTC, mcbloch requested changes
I'd suggest bumping to 1.0

2020-09-17 23:08 UTC, mcbloch commented on srcpkgs/github-cli/template
> +version=0.12.0
```suggestion
version=1.0.0
```

2020-09-17 23:08 UTC, mcbloch commented on srcpkgs/github-cli/template
> +checksum=227031cc381555da2a406bde7d5bfdd631979f635cda22537f206b5362cf6fc1
```suggestion
checksum=96575c888d979a6717928fe53bbd75d1acd52a6eec32aa41202d15919475ebfa
```

2020-09-18 07:51 UTC, shizonic commented
Updated to 1.0.0. Thanks!

2020-09-19 22:01 UTC, merged