dhcpcd: make privsep a build option
void-linux/void-packages pull request #24867
Opened 2020-09-12 18:39 UTC by CameronNemo

Still forks away from the supervisor :/
But there is no huge process tree, just a launcher and master.

2020-09-13 00:54 UTC, sgn commented on srcpkgs/dhcpcd/template
> +	_dhcpcd_homedir="/var/db/dhcpcd"
I prefer to keep them for no reason.

2020-09-15 18:46 UTC, Piraty requested changes

2020-09-15 18:46 UTC, Piraty commented on srcpkgs/dhcpcd/template
> +	configure_args+=" --privsepuser=_dhcpcd"
`vopt_if`?

2020-09-21 00:34 UTC, CameronNemo commented on srcpkgs/dhcpcd/template
> +	_dhcpcd_homedir="/var/db/dhcpcd"
kept

2020-09-21 00:35 UTC, CameronNemo commented on srcpkgs/dhcpcd/template
> +	configure_args+=" --privsepuser=_dhcpcd"
used vopt_if

2020-09-23 09:54 UTC, the-maldridge commented
This doesn't really solve the original problem though, which is it forking away from the supervisor.   I'm not sure why you'd add this package since it doesn't change the status of the bug that needs to be fixed.

2020-10-15 14:43 UTC, closed without merging