New package: goattracker-2.75
void-linux/void-packages pull request #25316
Opened 2020-10-03 16:19 UTC by Zeinok

C64 music tracker

2020-12-22 10:18 UTC, fosslinux requested changes

2020-12-22 10:18 UTC, fosslinux commented on srcpkgs/goattracker/template
> +wrksrc=goattrk2/
Slash unrequired

2020-12-22 10:18 UTC, fosslinux commented on srcpkgs/goattracker/template
> +	make
Use `${makejobs}` here as an argument to make for parallelism.

2020-12-22 10:18 UTC, fosslinux commented on srcpkgs/goattracker/template
> +	cd ${wrksrc}/src/
If you want to be fancy, you could go:

```
pushd src
make clean
pushd bme
make
popd
make
popd

2021-05-23 07:30 UTC, Zeinok commented
continued in #31074, closing

2021-05-23 07:30 UTC, closed without merging