docker: update to 19.03.13.
void-linux/void-packages pull request #25389
Opened 2020-10-06 15:44 UTC by aguilbau

2020-10-21 17:35 UTC, ahesford requested changes

2020-10-21 17:35 UTC, ahesford commented on srcpkgs/docker/template
>  revision=2
`revision=1`

2020-10-22 13:00 UTC, closed without merging

2020-10-22 15:00 UTC, aguilbau commented
why was it closed ?

2020-10-22 15:04 UTC, ahesford commented
I merged this from an external tool: "ahesford closed this in 50f7d64"