Add xvfb-run package, update gtkmm and glib, fix glibmm tests
void-linux/void-packages pull request #25420
Opened 2020-10-07 21:08 UTC by ericonr

2020-10-07 22:21 UTC, ericonr commented
glib tests complete on glibc but fail on musl. Investigating, though it's likely not urgent.

2020-10-07 23:34 UTC, fosslinux requested changes

2020-10-07 23:34 UTC, fosslinux commented on srcpkgs/cabbage/template
> +	# TODO: use xfbv-run script for testing
typo

2020-10-08 01:05 UTC, ericonr commented on srcpkgs/cabbage/template
> +	# TODO: use xfbv-run script for testing
Thanks!

2020-10-08 01:05 UTC, ericonr commented on srcpkgs/cabbage/template
> +	# TODO: use xfbv-run script for testing
Thanks!

2020-10-08 18:39 UTC, ericonr commented
Added `fwupd` fix up to use the new gtk-doc.

2020-10-09 19:46 UTC, merged