krita: update to 4.4.0.
void-linux/void-packages pull request #25651
Opened 2020-10-16 09:50 UTC by kartikynwa

I have built both packages and can confirm they work perfectly at least for x86_64. The SeExpr module for Krita is working as well.

Should I test cross-building for `seexpr-krita`? I can't do it for `krita` cuz my computer is slow but can test the `seexpr-krita` if needed.

2020-10-18 12:10 UTC, Johnnynator requested changes
seexpr doesn't cross compile ootb, either try to fix it or set it `nocross` and make the dep in krita conditional.

2020-10-18 12:10 UTC, Johnnynator commented on srcpkgs/seexpr-krita/template
> +configure_args="-DBUILD_DEMOS=OFF -DBUILD_TESTS=OFF \
No need to escape a newline in a quoted string. Also don't hard disable tests. add smth like
```
if [ "$XBPS_CHECK_PKGS" ]; then
        configure_args+=" -DBUILD_TESTS=ON"
else
        configure_args+=" -DBUILD_TESTS=OFF"
fi
```
after checksum and

```
do_check() {
        cd build
        # BlockTests requires llvm, we don't build it with llvm
        ctest -E 'BlockTests'
}

post_install() {
        [ -d "${DESTDIR}/usr/share/test/SeExpr2" ] && rm -r "${DESTDIR}/usr/share/test/SeExpr2" || true
}
```
 after pre_configure

2020-10-18 12:10 UTC, Johnnynator commented on srcpkgs/seexpr-krita/template
> +		vmove usr/share/pkgconfig
Add `vmove "usr/lib/*.so"`

2020-10-18 12:10 UTC, Johnnynator commented on srcpkgs/seexpr-krita/template
> +makedepends="qt5-tools-devel boost-devel python3-devel python3-PyQt5-devel python3-sip-devel"
Add `checkdepends="gtest-devel"`

2020-10-18 18:31 UTC, kartikynwa commented
@Johnnynator I tried cross-building it for `aarch64-musl`. Many of the errors were fixed by moving the `makedepends` to `hostmakedepends`. [This](http://ix.io/2BaS) is the template I have now. But I get [this](http://ix.io/2BaJ) error now that I don't have any idea about. Any pointers?

2020-10-20 14:42 UTC, kartikynwa commented
@Johnnynator I put the `-DUSE_PYTHON=OFF` flag in `seexpr-krita`. It can now be cross-built (tested with armv6l-musl and armv7) and still has full functionality with `krita`.

2020-10-22 09:55 UTC, merged