Manual.md: relax and clarify the "no sripts" policy
void-linux/void-packages pull request #25707
Opened 2020-10-18 14:24 UTC by ahesford

I think our "no scripts" policy is too strict and precludes the inclusion of useful administrative tools. These are helpful to have packaged because it makes deploying new Void systems easier by keeping tools in one place. Based on a discussion in #xbps, I propose the following relaxed language that still gives us a reasonable justification for rejecting apparently useless scripts while admitting some more useful ones.

2020-10-18 14:33 UTC, sgn commented on Manual.md
> +scripts are unlikly to be accepted unless they provide considerable value to a
s/unlikly/unlikely

2020-10-20 19:24 UTC, Chocimier approved these changes
typo in "no sripts" in commit message

2020-11-03 18:18 UTC, the-maldridge requested changes

2020-11-03 18:18 UTC, the-maldridge commented on Manual.md
> +broad user base. New fonts are welcome if they provide value beyond aesthetics
New fonts are not welcome, but might be accepted.

2020-11-13 23:17 UTC, closed without merging

2020-11-13 23:18 UTC, ahesford commented
I've seen no objections except for rewording suggestions that have been accommodated, so merging seems appropriate.