tzdata: update to 2020d.
void-linux/void-packages pull request #25815
Opened 2020-10-23 09:20 UTC by ailiop-git

2020-10-23 15:23 UTC, PaperMountainStudio requested changes
Can you remove `-y ./yearistype`? `-y` is ignored and yeartype file was removed this release

2020-10-25 04:00 UTC, fosslinux requested changes

2020-10-25 04:00 UTC, fosslinux commented on srcpkgs/tzdata/template
>  hostmakedepends="tzutils"
AFAICT this is no longer needed either if yearistype has been dropped?

2020-10-28 16:52 UTC, leahneukirchen commented
Obsoleted by #25941, which includes important fix.

2020-10-28 16:52 UTC, closed without merging