libsndfile: update homepage and distfiles
void-linux/void-packages pull request #26023
Opened 2020-10-31 20:18 UTC by lun-4

Noticed the repository moved to its own organization. Update homepage and distfiles to keep it in sync.

The old `distfiles` url still redirects and the given `.tar.bz2` file from it has matching hashes, so I didn't bump `revision`.

2020-10-31 20:52 UTC, ericonr requested changes

2020-10-31 20:52 UTC, ericonr commented on srcpkgs/libsndfile/template
> +homepage="http://libsndfile.github.io/libsndfile/"
Please use https

2020-11-01 09:10 UTC, biopsin commented
what about bump to python3 ?
https://github.com/libsndfile/libsndfile/issues/490

2020-11-01 18:02 UTC, lun-4 commented
I think a `python3` bump would be better in a separate PR.

2020-11-01 19:07 UTC, ericonr commented
> I think a python3 bump would be better in a separate PR.

Your choice, really. The link fixes are routine maintenance, but you can repurpose the PR and just include the fixes together with the rest.

2020-11-06 15:12 UTC, ericonr commented
Does it need to be revbumped?

2020-11-06 19:31 UTC, lun-4 commented
I didn't read the `Manual.md` section on revisions and had a wrong definition in my mind. I kept the package on the old revision.

2020-11-06 19:35 UTC, ericonr commented
Great. thanks!

2020-11-06 19:35 UTC, merged