New package: qt-virt-manager-0.71.95
void-linux/void-packages pull request #26473
Opened 2020-11-18 06:05 UTC by Logarithmus

Qt Virtual machines manager

2020-11-20 20:07 UTC, Logarithmus commented
@ericonr @pullmoll @Duncaen i think it can be merged now

2020-11-20 20:15 UTC, Duncaen commented on srcpkgs/qt-virt-manager/template
> +	libglib-devel spice-gtk-devel libvncserver-devel \
Indention with just one space and \ at the end of lines inside quotes variables is not required.

2020-11-20 20:17 UTC, Duncaen commented on srcpkgs/qt-virt-manager/template
> +homepage="https://f1ash.github.io/qt-virt-manager/"
Add
```
changelog="https://github.com/F1ash/qt-virt-manager/raw/master/Changelog"
```

2020-11-20 20:18 UTC, Duncaen commented
Please don't ping me if I'm not strictly involved, this just adds noise to my notifications and I generally review or merge PRs on my own accord.

2020-11-20 20:33 UTC, Logarithmus commented
I'm sorry for that. I've added the changelog and corrected the spaces.

2021-02-27 17:43 UTC, Logarithmus commented
@ericonr ping?

2022-03-06 14:38 UTC, zen0bit approved these changes
title should be (I think): New package: qt-virt-manager 0.72.98
otherwise
:+1:

I didn't even known that exist and I like it...

Thanks @Logarithmus

2022-06-05 03:03 UTC, zen0bit commented
new version 0.72.99

2022-06-05 03:17 UTC, zen0bit requested changes
New version 0.72.99 is out...

2022-06-05 03:17 UTC, zen0bit commented on srcpkgs/qt-virt-manager/template
> +version=0.72.98
version=0.72.99

2022-06-05 03:17 UTC, zen0bit commented on srcpkgs/qt-virt-manager/template
> +checksum=bf8b0ffe08453224efcb60a3a9f49a60f0fa195a345f996463540c78d523ec91
checksum=06b451d32ea427c17a5520f26adfc49848ea348a8fa3b6cf73d74813e6cd0b5f

2022-06-05 17:55 UTC, zen0bit requested changes

2022-06-05 17:55 UTC, zen0bit commented on srcpkgs/qt-virt-manager/template
> +depends="qt5-xml"
Looks like this also needed as dependency:
krdc qtermwidget

2022-06-20 02:12 UTC, closed without merging