zoom: fixes xcb-utils-* dependencies
void-linux/void-packages pull request #27014
Opened 2020-12-07 08:26 UTC by waynevanson

closes #26844

2020-12-07 14:03 UTC, mobinmob commented
Please bump revision ;)

2020-12-08 03:33 UTC, fosslinux requested changes

2020-12-08 03:33 UTC, fosslinux commented on srcpkgs/zoom/template
> +depends="$(vopt_if systemqt 'qt5 qt5-graphicaleffects qt5-imageformats qt5-quickcontrols qt5-quickcontrols2 qt5-svg qt5-script qt5-declarative') xcb-util-image xcb-util-keysyms"
split into a new line, it's ok to have it over 80 chars for the vopt_if bit i guess but please split the new dependencies onto a new line.

2020-12-09 20:03 UTC, waynevanson commented
@mobinmob did I do the bump for the revision correctly?

2020-12-09 20:07 UTC, waynevanson commented
Apologies for multiple force pushes, forgot to `git add .` before `git commit --amend`.

2020-12-09 20:07 UTC, ericonr commented on srcpkgs/zoom/template
>  revision=1
```suggestion
version=5.4.54779.1115
revision=2
```

2020-12-09 20:07 UTC, ericonr commented on srcpkgs/zoom/template
> +"
```suggestion
depends="$(vopt_if systemqt 'qt5 qt5-graphicaleffects qt5-imageformats qt5-quickcontrols qt5-quickcontrols2 qt5-svg qt5-script qt5-declarative')
 xcb-util-image xcb-util-keysyms"
```

We indent multi-line variables with spaces

2020-12-09 20:13 UTC, merged