new package: espeak-ng-1.50
void-linux/void-packages pull request #27193
Opened 2020-12-16 08:34 UTC by joey-commits

Speech Dispatcher and espeakup were also corrected to build against the new espeak-ng
  I used dummy packages to replace Espeak on installed machines. The idea was gained from polkit-elogind, however, I am open to doing something else if it is prefered.  Apparently, the author of espeak could not be contacted and espeak-ng was created a few years ago to continue development.
I have been using these packages with my screen readers for a few hours and everything seems like its working so far.

2020-12-16 16:46 UTC, joey-commits commented
I am not sure how to fix the builds on non-intel arches. I guess its failing because its trying to execute the non-intel binaries on the intel builder as part of the build process. I will do some research and would also appreciate any help if someone has time. I'll try to figure this out but cross compiling is new territory for me.

2020-12-16 17:12 UTC, ericonr commented
Please fix the xlint complaints:

```
Run common/travis/xlint.sh
Linting srcpkgs/espeak-ng/template...
srcpkgs/espeak-ng/template: Place checksum= after homepage=
Linting srcpkgs/espeakup/template...
srcpkgs/espeakup/template: Place checksum= after build_style=
srcpkgs/espeakup/template: Place distfiles= after makedepends=
srcpkgs/espeakup/template:5: short_desc should not start with an article
srcpkgs/espeakup/template:7: use SPDX id for 'GPL-3' license or see Manual.md
Linting srcpkgs/speech-dispatcher/template...
Error: Process completed with exit code 1.
```

2020-12-16 17:15 UTC, ericonr commented
Argh, solving this might be a bit complicated, but definitely required, since espeak did cross build previously. I will try to poke at it.

2020-12-16 19:13 UTC, joey-commits commented
I was looking at the data built by the binaries and it doesn't seem to be archetecture specific. I need to look at a bit more to be sure. I am wondering if I  could make a  nocross package to build the data files and then pull it in for the real espeak-ng package with hostmakedepends. Then it could be coppied to the build directory before the build and the Makefile would detect that the voice dictionaries are already built.

2020-12-16 19:30 UTC, ericonr commented
> I am wondering if I could make a nocross package to build the data files and then pull it in for the real espeak-ng package with hostmakedepends. Then it could be coppied to the build directory before the build and the Makefile would detect that the voice dictionaries are already built.

Doesn't even need to be nocross. I've done exactly this for the `sdcc` package. Something like:

```
if [ "$CROSS_BUILD" ]; then
hostmakedepends+=" espeak-ng"
fi

pre_build() {
if [ "$CROSS_BUILD" ]; then
cp -r ....
fi
}
```

2020-12-17 14:44 UTC, Piraty requested changes

2020-12-17 14:44 UTC, Piraty commented on srcpkgs/espeakup/template
> +
please xlint this template

2020-12-17 14:45 UTC, Piraty commented
if you'd be so kind to ensure arcan's tts build option will work with your changeset

2020-12-17 15:05 UTC, ericonr commented on srcpkgs/espeak-ng/template
> +	fi
I guess just putting the files there didn't work? This is quite unfortunate.

Having numbered seds is quite fragile, though, so ideally we could come up with a patch for it.

Also, indentation of the last `sed` line is too far right by 2 tabs.

2020-12-17 15:15 UTC, joey-commits commented
I am just glad its building. Gives me hope. Sorry about the indentation issues. I am trying to get better about this, however, indentation is tricky when using a screen reader. It makes me wonder how many other people are actually packaging and programming with Orca instead of a screen. I don't know anyone else.

2020-12-17 15:21 UTC, joey-commits commented
I can definitely do a patch instead. Are you ok with me patching the Makefile after running configure like I am doing with sed?

2020-12-17 15:31 UTC, ericonr commented
>  I am trying to get better about this, however, indentation is tricky when using a screen reader.

I can imagine. If you need any help for the fiinal clean up, I can do a final once over. Thanks for contributing :)

> I can definitely do a patch instead. Are you ok with me patching the Makefile after running configure like I am doing with sed?

Hmm that is indeed not ideal, since it can change dependending on the environment. Can you show me the part you're trying to delete? We can try to come up with a solution.

2020-12-17 15:35 UTC, joey-commits commented
The main problem is that the Makefile calls espeak-ng in a bunch of places. I am simply redirecting it to usr/bin in all those cases so that it runs the copy from the x86_64 package. I am really sorry. i don't know enough about autotools to fix this properly.

2020-12-17 15:37 UTC, joey-commits commented
After espeak-ng is compiled, the binary is used to compile the dictionaries and phoneme data as a part of the make process..

2020-12-17 15:53 UTC, ericonr commented
Ah! Got it.

I think if we can make the rules a bit more specific, it won't be necessary to specify the line numbers. I will try to build it locally to see if I can come up with one, but I think `vsed -e "s_\ts_src/espeak-ng_/usr/bin/espeak-ng_" -i Makefile` might do the trick (plus a rule with `../s_src/espeak-ng`.

By the way, do you think we could use a symlink in `/usr/bin/espeak`?

2020-12-17 16:10 UTC, joey-commits commented
I think a simlink pointing from /usr/bin/espeak to /usr/bin/espeak-ng could be nice. I will add that to the espeak-ng package. Thanks so much for your help with this. Espeak-ng works so much better with my reader and it will be nice to have it in the repositories.

2020-12-17 16:48 UTC, joey-commits commented
@piraty Is there any way you could help me test Arcan? It looks like an alternative display server. I think my screen reader depends on Xorg and may not run in Arcan. From what I can tell, it ships with its own desktop and I think Orca only supports Gnome, Mate and XFCE.

2020-12-17 16:54 UTC, joey-commits commented
A quick grep of the Arcan sources shows that it uses a header that espeak-ng ships for backwards compatibility. I would think it would work ok.

2020-12-17 21:30 UTC, Piraty commented
for now it's enough if arcan builds and correctly links the espeak-ng, as it's just an opt-in build option it's for custom use cases anyway. thanks for you work!

2020-12-18 14:34 UTC, joey-commits commented
Hey, I was wondering if there are any further changes you think we would need before this can enter the repo. I think the tests failed du to pulseaudio 14 tests. I replaced the line numbers with searches and substitutions like we discussed. Thanks again for all the help!

2020-12-18 14:46 UTC, joey-commits commented
I mean the packages failed to build due to pulseaudio tests failing not my packages not building.

2020-12-18 20:06 UTC, ericonr commented
I'm re-running all CI jobs, then. How can I test the package?

2020-12-18 20:17 UTC, joey-commits commented
You can test espeak-ng by typing:

espeak-ng "testing testing"

 which will play speech through your sound card.

Alternatively:

espeak-ng "testing testing" -w output.wav

will generate a PCM audio file with the speech.

2020-12-18 23:47 UTC, joey-commits commented
Looks like this is passing since pulse 14 hit the repos. That is good news.

2020-12-19 03:02 UTC, ericonr commented
@joey-commits 

Another espeak user (over IRC) asked that we keep both espeak and espeak-ng as options, since they had heard that espeak-ng had some issues with latency. What are your thoughts on that? If you think it's ok but don't want to work on the template, I can try to get it going. I believe it would be possible to have both available, including as a build option for speech-dispatcher.

2020-12-19 03:08 UTC, ericonr commented
I'd imagine it doesn't integrate nearly as well, but have you tried `mimic`? It sounds reasonably good.

2020-12-19 03:20 UTC, joey-commits commented
I would be ok with keeping espeak but I would be very interested to learn the use case. Since espeak is not maintained any more, I would much   rather keep espeak around until we can fix all issues and then migrate. I certainly wouldn't want to break someones workflow.
I know that speech dispatcher has been less latent with espeak-ng for a long time. I also applied patches to pcaudilib to ensure that espeak-ng would be less latent with espeakup. The patches that I applied fix two problems with espeakup which are latency and overlapping audio. I tested espeakup for a while today to ensure that it was reliable since I actually have friends who use it even though I am mostly an Orca user.

2020-12-19 03:23 UTC, joey-commits commented
The problem with keeping both around is that you can only build espeakup against one or the other. I have been thinking about wanting to migrate to espeak-ng for a long time but I knew about the espeakup issues. I didn't want to make a pull request until I was sure those issues were solved. One of the accessibility folks who works on the debian project solved the accessibility issues with espeakup.. If there is another thing though that is broken that I don't know about, lets the use case and wait to migrate until we can be sure it is solved. Having both around will be messy.

2020-12-19 03:25 UTC, joey-commits commented
Could the user comment on the pull request here? I think it would be good to keep a record of the issues people have on this pull request so that we can think about and solve them.

2020-12-19 03:47 UTC, ericonr commented
> One of the accessibility folks who works on the debian project solved the accessibility issues with espeakup..

That's nice to hear!

What I was considering was adding a new espeak-ng package which doesn't replace espeak, and adding a build option to espeakup to allow it to be built with either, but make espeak-ng the default. The only disadvantage is that an espeak user who hasn't heard about espeak-ng won't get an update.

I asked them to comment, but haven't heard back yet.

2020-12-19 21:36 UTC, CMB commented
I've been testing this PR.  There are no latency issues anymore.  I
whole-heartedly approve.

2020-12-19 21:57 UTC, CMB commented
BTW this is teiresias from freenode.

2020-12-19 22:27 UTC, ericonr commented
Yay! Thank you very much for checking :)

2020-12-20 19:22 UTC, Piraty approved these changes

2020-12-20 19:30 UTC, closed without merging