New package: Opencoarrays-2.9.2
void-linux/void-packages pull request #27618
Opened 2021-01-02 10:14 UTC by ramos

2021-01-09 13:30 UTC, kawaiiamber commented
Get rid of line 15 to pass Link check.

2021-01-16 10:12 UTC, kawaiiamber commented on srcpkgs/OpenCoarrays/template
> +hostdepends="gcc gcc-fortran openmpi openmpi-devel cmake"
`hostmakedepends`, -devel things should go in `makedepends`. The `build_style` is `cmake`, no need to include `cmake` in `hostmakedepends` or in `makedepends`. Looking at the project, you might want `openmpi-devel` for the development files in `makedepends`.

2021-01-16 10:13 UTC, kawaiiamber requested changes

2021-01-16 10:13 UTC, kawaiiamber commented on srcpkgs/OpenCoarrays/template
> +license="GPL-3.0-or-later"
The license is actually a BSD 3 Clause license, change to `license="BSD-3-Clause"`, and add
```
post_install() {
    vlicense LICENSE
}
```
but with a tab before vlicense, not spaces.

2021-01-16 10:18 UTC, kawaiiamber commented on srcpkgs/OpenCoarrays/template
> +distfiles="https://github.com/sourceryinstitute/OpenCoarrays/releases/download/2.9.2/OpenCoarrays-${version}.tar.gz"
You hardcoded `2.9.2` in one spot in the URL yet expanded `${version}` in another? It's recommended to expand `${version}` when possible to make maintaining easier. Try switching `distfiles` to `distfiles="https://github.com/sourceryinstitute/OpenCoarrays/archive/${version}.tar.gz"` and match the checksum.

2021-01-16 10:23 UTC, kawaiiamber commented
There are three commits, there should only be one. Try squashing your commits with rebase: `git rebase -i HEAD~3` and squash the last two, having the commit message just be "New package: OpenCoarrays-2.9.2", just use `amend` to commit future changes.
```
git commit --amend
git push origin master -f
```
One thing I might recommend while I'm on git things, I would recommend making a specific branch on your fork, e.g.
```
git checkout -b opencoarrays
<add your template>
git add -A
git commit -m "New package: OpenCoarrays-2.9.2"
git push origin opencoarrays
```
then, on this PR, switch to request merging that branch from your fork to the upstream master branch.

2021-01-16 10:41 UTC, kawaiiamber commented
Haven't tested, but, from what I've read on upstream's documentation, [this](https://pastebin.com/z4ea1hEu) template might be helpful as a start point.

2021-01-16 10:59 UTC, kawaiiamber commented
I tried testing on aarch64-musl, and found that:
```
=> OpenCoarrays-2.9.2_1: building [cmake] for aarch64-musl...
   [host] gcc-fortran-9.3.0_9: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] openmpi-4.1.0_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [host] cmake-3.19.3_1: found (https://alpha.de.repo.voidlinux.org/current/musl)
   [target] libgfortran-devel-9.3.0_9: found (https://alpha.de.repo.voidlinux.org/current/aarch64)
   [target] openmpi-devel-4.1.0_1: not found
```
`openmpi` isn't on cross platform. I have an updated template [here](https://pastebin.com/pZQzpSQB). I don't know much about fortran, though.

2021-01-17 10:29 UTC, ramos commented
Ok, Many thank

Not sure about the conflicts. I have checked that this builds ok in my system with your new template.

Many thanks!

2021-01-17 10:35 UTC, kawaiiamber commented
It looks like you pulled all changes from latest upstream master branch - over 700 commits! You might want to do a couple of things:
1. Add an upstream remote: `git remote add upstream https://github.com/void-linux/void-packages.git`
2. Rebase your branch against upstream master: `git pull --rebase upstream master`
3. Add a branch specifically for your template: `git checkout -b opencoarrays`, then add your template and push there: `git push origin opencoarrays`, switch this PR to merge from that branch rather than your forked master branch.

2022-05-17 02:13 UTC, closed without merging