Limd
void-linux/void-packages pull request #28297
Opened 2021-01-29 04:29 UTC by CRKatri

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-01-30 00:22 UTC, kawaiiamber commented
Short descriptions shouldn't start with articles and shouldn't end in periods. Try changing to `Allows communication with iBoot/iBSS of iOS devices via USB` and `Command-line application to restore firmware files to iOS devices`

2021-01-30 00:24 UTC, kawaiiamber commented on srcpkgs/idevicerestore/template
> +short_desc="A command-line application to restore firmware files to iOS devices."
`short_desc=Command-line application to restore firmware files to iOS devices`

2021-01-30 00:26 UTC, kawaiiamber requested changes
To pass the link check

2021-01-30 00:26 UTC, kawaiiamber commented on srcpkgs/libirecovery/template
> +short_desc="The libirecovery library allows communication with iBoot/iBSS of iOS devices via USB."
`short_desc=Allows communication with iBoot/iBSS of iOS devices via USB`

2021-01-30 00:26 UTC, kawaiiamber commented on srcpkgs/idevicerestore/template
> +short_desc="A command-line application to restore firmware files to iOS devices."
`short_desc=Command-line application to restore firmware files to iOS devices`

2021-03-10 04:51 UTC, ericonr commented
Ideally you wouldn't add the packages as orphaned...

2022-01-12 20:16 UTC, Jackojc commented
Any updates on getting these packages merged?

2022-01-12 20:21 UTC, ahesford commented
The first step is not creating new packages that are orphaned from the outset.

2022-05-17 02:14 UTC, closed without merging