<!-- Mark items with [x] where applicable -->
void-linux/void-packages pull request #28401
Opened 2021-02-02 09:32 UTC by Gottox

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-02-02 12:15 UTC, Piraty commented
`srcpkgs/gitlab-runner` ?

2021-02-02 12:16 UTC, Piraty requested changes

2021-02-02 12:16 UTC, Piraty commented on srcpkgs/glab/template
> +short_desc="Official GitLab CI runner written in Go"
may be you copied another template and didn't modify relevant parts?

2021-02-02 12:27 UTC, Piraty requested changes

2021-02-02 12:27 UTC, Piraty commented on srcpkgs/glab/files/gitlab-runner/run
> +exec gitlab-runner run
leftover

2021-02-02 12:27 UTC, Piraty commented on srcpkgs/glab/update
> +site="https://gitlab.com/gitlab-org/gitlab-runner/tags"
leftover

2021-02-02 13:03 UTC, Gottox commented
thx for the pointers! :)

2021-02-02 19:22 UTC, ericonr commented on srcpkgs/glab/template
> +distfiles=https://github.com/profclems/$pkgname/archive/v$version.tar.gz
```suggestion
distfiles="https://github.com/profclems/glab/archive/v$version.tar.gz"
```

2021-02-02 19:22 UTC, ericonr commented on srcpkgs/glab/template
> +	vlicense ${wrksrc}/LICENSE
I think this should be just `vlicense LICENSE`

2021-02-05 13:33 UTC, Piraty approved these changes

2021-02-05 13:33 UTC, merged