[WIP] nextcloud-client: update to 3.1.2, remove shibboleth and wekbit support
void-linux/void-packages pull request #28674
Opened 2021-02-11 20:25 UTC by yopito

* shibboleth is "highly deprecated" by upstream, will be removed in 3.2.
* webkit support is currently ineffective and difficult to fix.
* fix ~dolphin build options

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-02-11 20:35 UTC, ericonr commented
I think we can avoid adding this to `removed-packages` for armv7l if we can move the builders to i686.

2021-02-11 23:27 UTC, paper42 commented
@yopito could you fix the typo in the commit message? wekbit? 😉

2021-02-11 23:34 UTC, yopito commented
> @yopito could you fix the typo in the commit message? wekbit? wink

nice catch ! yes of course.

2021-02-13 20:28 UTC, ericonr commented
I don't love this solution, but that's mainly because I don't like vendoring in desktop files. If you can generate the desktop file reliably with a sed on the original desktop file at build time, I'd rather have that.

Besides that, LGTM. Maybe make the INSTALL msg a `README.voidlinux` instead? Otherwise the message will always be there.

2021-02-14 21:01 UTC, yopito commented
here it is. looks like this: 
![image](https://user-images.githubusercontent.com/12870617/107888947-0e990000-6f10-11eb-8bcb-70dc4a4e391c.png)

2021-02-15 08:46 UTC, yopito commented
squashed commits, removed INSTALL.msg, add a README.voidlinux to new subpackage `nextcloud-client-kwallet` .

2021-02-16 05:48 UTC, fosslinux requested changes

2021-02-16 05:48 UTC, fosslinux commented on srcpkgs/nextcloud-client/files/kwallet/README.voidlinux
> +This is usefull when not using KDE as Desktop Environment.
usefull typo

2021-02-24 04:18 UTC, merged

2021-02-24 16:30 UTC, q66 commented
? why was the `webengine` option removed? the patch applies perfectly fine and doesn't need any rebasing

2021-02-25 07:33 UTC, yopito commented
@q66: I don't remember exactly the details, but webkit support is completely useless according to my runtime tests.

2021-02-25 10:06 UTC, q66 commented
... the webkit stuff and the webengine removal patch are two completely different and separate things

webengine is used for login flow, which the patch disables, it does not use webkit for anything

2021-02-25 19:18 UTC, yopito commented
I agree. but without the login flow, can this app be considered as usable ?
I don't see how to use it then.