New package: python3-pytest-flake8-1.0.7
void-linux/void-packages pull request #28842
Opened 2021-02-18 15:19 UTC by paper42

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-02-18 15:26 UTC, FollieHiyuki commented
Why not use the default `do_check()` from build style? It doesn't work?

2021-02-18 15:41 UTC, paper42 commented
@FollieHiyuki you were right, I forgot. Now I added PYTHONPATH, so I need it.

2021-02-18 18:59 UTC, ahesford requested changes
If this package isn't being pulled into `checkdepends` for other end-user packages, does it provide value on its own?

2021-02-18 18:59 UTC, ahesford commented on srcpkgs/python3-pytest-flake8/template
> +}
You don't need this. The build style will automatically call `python3 -m pytest` when `python3-pytest` is available, which implicitly adds `.` to `PYTHONPATH`.

2021-02-19 14:50 UTC, paper42 commented
> If this package isn't being pulled into `checkdepends` for other end-user packages, does it provide value on its own?

no, but the tests depending on this package are patched out from at least python3-numpy-stl. Then, at least python3-pep517, python3-cairocffi and radicale have their tests disabled **partially** because of this missing package.

2021-02-22 14:41 UTC, ahesford commented
If adding this package is sufficient to make tests in `python3-numpy-stl` work without the `pre_check` patch, please drop that patch in this PR. No need to revbump.

2021-03-02 19:54 UTC, paper42 commented
> If adding this package is sufficient to make tests in `python3-numpy-stl` work without the `pre_check` patch, please drop that patch in this PR. No need to revbump.

@ahesford done

2021-03-12 13:47 UTC, merged