julia: update to 1.6.0.
void-linux/void-packages pull request #29758
Opened 2021-03-25 21:27 UTC by non-Jedi

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-03-26 01:16 UTC, non-Jedi commented
Just realized that since this vendors in suitesparse, technically this package should be marked as GPL rather than MIT. Or we could build without sparse linear algebra support... How are projects with mixed licenses supposed to be handled?

2021-03-26 01:22 UTC, ahesford commented
I remember earlier versions passed the bast majority of tests but some still failed. If the number of failures isn't dramatically increasing, we shouldn't worry too much.

For licenses, just list both separated by a comma, *e.g.*, "MIT, GPL-3.0-or-later". Just double check the right GPL version restrictions and use the SPDX identifier.

2021-03-26 01:24 UTC, ahesford commented
Just checked the test log, and the number of broken, failed and errors from tests are in the ballpark of my memory. Nothing alarming.

2021-03-26 15:25 UTC, non-Jedi commented
> I remember earlier versions passed the bast majority of tests but some still failed. If the number of failures isn't dramatically increasing, we shouldn't worry too much.

Ya. It's no different than it has been. I included that blurb so that people unfamiliar with the history wouldn't be confused by the CI failures.

> For licenses, just list both separated by a comma, _e.g._, "MIT, GPL-3.0-or-later". Just double check the right GPL version restrictions and use the SPDX identifier.

Will do. By the looks of it, it will just be a list of basically every prominent free software license in existence: https://github.com/JuliaLang/julia/blob/master/LICENSE.md

2021-03-26 21:56 UTC, ahesford commented
In that case, just leave it MIT. You're already copying the full list as it is, this is just metadata for convenient categorization.

2021-03-30 04:15 UTC, ahesford requested changes
Looks like this release adds a few other copies of system libraries. Please add the `libssp` and `libatomic` dependencies as noted. Also, in the `for` loop in `post_install` that removes the copied libraries and replaces them with symlinks, please add `libatomic.so.1`, `libstdc++.so.6` and `libssp.so.0` to the list of libraries to remove and link. (The `libstdc++` dependency does not need to be added to `shlib_requires` or `depends` because it is picked up elsewhere.)

Also, when removing the vendored copy on Line 90, please drop the `-f` so the build will fail if a future update stops copying any of the libraries we remove here.

2021-03-30 04:15 UTC, ahesford commented on srcpkgs/julia/template
> +depends="libgit2 libcurl mpfr mbedtls libpcre2 libssh2 nghttp2 libquadmath p7zip"
Add `libssp` and `libatomic` to `depends`.

2021-03-30 04:15 UTC, ahesford commented on srcpkgs/julia/template
> + libssh2.so.1 libquadmath.so.0 libnghttp2.so.14"
Add `libatomic.so.1` and `libssp.so.0` to `shlib_requires`.

2021-03-31 15:17 UTC, non-Jedi commented
Thanks for the thorough review. And good catch on the additional libraries. I've made the changes you suggested and force pushed.

2021-03-31 18:13 UTC, merged

2021-03-31 19:35 UTC, ahesford commented
I merged this before I noticed that the failure on `i686` is not the tests but the build process. See [build logs](https://build.voidlinux.org/builders/i686_builder/builds/31520/steps/shell_3/logs/stdio) or the [CI results in this PR](https://github.com/void-linux/void-packages/pull/29758/checks?check_run_id=2236946329).

Do you mind taking a look at the failure to see if you can get this building for i686 again?

```
ERROR: error: address range table at offset 0x720 has an invalid tuple (length = 0) at offset 0x738
LoadError: failed process: Process(`/builddir/julia-1.6.0/usr/bin/julia -O0 --sysimage /builddir/julia-1.6.0/usr/lib/julia/sys.ji --startup-file=no -Cnative -e 'pushfirst!(DEPOT_PATH, "/tmp/jl_DXUoMZ");
Base.PRECOMPILE_TRACE_COMPILE[] = "/tmp/jl_XA56VY";
Base.compilecache(Base.PkgId("__PackagePrecompilationStatementModule"), "/tmp/jl_DXUoMZ/__PackagePrecompilationStatementModule/src/__PackagePrecompilationStatementModule.jl")
```

2021-03-31 22:43 UTC, non-Jedi commented
I'll see what I can do.

2021-04-01 21:27 UTC, non-Jedi commented
I haven't tested yet, but I have a sneaking suspicion that we need this patch to llvm 11 to successfully build julia i686. Will report back after building llvm and checking, but I'm not sure when I'll get the time to do so.

https://github.com/JuliaLang/julia/blob/21e7486322846836532fb0d19092c239cce190c9/deps/patches/llvm-11-D85313-debuginfo-empty-arange.patch

2021-04-02 16:20 UTC, non-Jedi commented
The patch I pointed to doesn't fix the issue. However the problem is most likely fixed by one of the patches julia applies to the vendored llvm. Julia builds fine for x86 when you allow it to vendor in its own llvm.

2021-04-02 18:15 UTC, ahesford commented
I wouldn't go too deep into this matter. Maintaining patches to our system LLVM just to support Julia on i686 doesn't seem like an attractive option. For now, we can leave it broken and decide whether to drop the `i686*` from `archs`. We can think about the merits of using the vendored LLVM when Void moves to `llvm12` relative to keeping the `llvm11` package around.