[NOMERGE] New package: purescript-0.14.0
void-linux/void-packages pull request #29846
Opened 2021-03-29 08:57 UTC by waynevanson

#### Summary
- Adds the wonderful compiler for purescript.
- Adds a dependency for spago (https://github.com/void-linux/void-packages/issues/24682)

___Not to be merged until___:
- [ ] GHC has been updated to 8.10.4 (https://github.com/void-linux/void-packages/pull/29506)
- [ ] Commits from adding future GHC version have been removed from this git branch
- [ ] Retested against an up-to-date master containing GHC-8.10.4

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

2021-05-20 12:51 UTC, BlueChrystal requested changes

2021-05-20 12:51 UTC, BlueChrystal commented on srcpkgs/purescript/template
> +license="GPL-3.0-or-later"
I took a look, and the PureScript compiler is licensed under the 3-clause BSD license, not GPLv3 or later.

2021-05-20 12:51 UTC, BlueChrystal commented on srcpkgs/purescript/template
> +makedepends="ncurses-libtinfo-devel ncurses-devel zlib-devel"
Apparently, the libtinfo dependency has been removed (see https://github.com/purescript/purescript/pull/4069). The change still hasn't been released though.

2021-05-20 12:51 UTC, BlueChrystal commented on srcpkgs/purescript/template
> +version=0.14.0
Maybe update this to 0.14.1?

2021-06-20 20:59 UTC, waynevanson commented
I'm no longer working on this, so closing. Others are free to reference this :)

2021-06-20 20:59 UTC, closed without merging