New package: sigi-0.2.0
void-linux/void-packages pull request #29907
Opened 2021-03-31 09:57 UTC by hiljusti

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] armv7l
  - [x] armv6l-musl

2021-03-31 11:13 UTC, ericonr commented
The commit message is still outdated, you can use `git commit --ammend` to fix it. Please avoid opening new PRs for the same package, as well: just force push to the PR with the new version.

2021-04-03 03:32 UTC, hiljusti commented
I udated the commit message and also rebased once. (I'll rebase again if needed.)

2021-04-15 04:37 UTC, cinerea0 commented
Small nitpick, but I'd suggest changing your short description from "Sigi is an organizing tool and no-frills stack database" to "Organizing tool and no-frills stack database" to fit with the style of other package short descriptions. Also, you don't need to check off anything under the "Does it build and run successfully?" section or even display it because your PR can be processed through CI in a reasonable amount of time.

2021-04-15 05:03 UTC, hiljusti commented
Thanks @cinerea0 ! I updated

2021-04-17 06:19 UTC, ericonr commented
The template looks ok, but for new packages I'd like to wait a bit, see how both maintenance and interest go.

2021-04-21 03:04 UTC, hiljusti commented
Thanks @ericonr!

For what it's worth, I'm the developer, and my daily driver is void. I use it to help me organize my life and don't plan to switch to other software.

2021-11-26 19:39 UTC, hiljusti commented
@ericonr As far as maintenance/interest, I think both are going pretty well here?

- I've gotten past two major version bumps (including backwards compat migration tools)
- Downloads of Sigi are up to 800 (from 350 back in April). I'm not advertising it, so this is just Rust folks who are finding it organically in crates.io and giving it a shot (or updating)
- I've also started getting (and responding to) issues on the project.

I know "TO DO list" is a pretty basic idea, and there's [plenty of other implementations](https://github.com/hiljusti/sigi/blob/core/NOTES.md). That said, Sigi strikes a really good balance between being simple, scriptable, and useful when compared to other tools.

2021-11-29 01:39 UTC, hiljusti commented
Fixed lint failure (The description was longer than 72 chars)

2021-12-08 00:42 UTC, hiljusti commented
@ericonr Could I ask you to take a look again? (Only because you've looked before)

2021-12-11 02:39 UTC, ericonr commented
Can you please rebase for CI to run correctly?

2021-12-12 08:59 UTC, hiljusti commented
@ericonr Rebased

2021-12-13 17:30 UTC, hiljusti commented
(I'll just keep rebasing periodically)

2021-12-17 19:22 UTC, hiljusti commented
@ericonr How does it look?

2022-01-12 09:50 UTC, hiljusti commented
Note: License changed in version 3.0.0.

It used to be GPL3+, now it is GPL2 (only)

2022-04-01 11:49 UTC, subnut requested changes

2022-04-02 19:26 UTC, hiljusti commented on srcpkgs/sigi/template
> +distfiles="https://crates.io/api/v1/crates/sigi/${version}/download>sigi-${version}.tar.gz"
I can do this - is there a reason to prefer github over crates.io though?

Github tags can change, but crate identifiers are immutable. I kind of prefer the former

2022-04-02 19:26 UTC, hiljusti commented on srcpkgs/sigi/template
> +}
Ohh great call. Thanks!

2022-04-02 19:29 UTC, hiljusti commented on srcpkgs/sigi/template
> +distfiles="https://crates.io/api/v1/crates/sigi/${version}/download>sigi-${version}.tar.gz"
(The "crate" from Rust is also a source tarball)

2022-04-02 19:35 UTC, hiljusti commented on srcpkgs/sigi/template
> +}
Made this change

2022-04-02 19:49 UTC, hiljusti commented on srcpkgs/sigi/template
> +distfiles="https://crates.io/api/v1/crates/sigi/${version}/download>sigi-${version}.tar.gz"
I'll update the homepage, but right now I want to keep the distfile at crates.io. The link is immutable, and publishing to crates.io has some really basic validation, like the sources being compilable

2022-04-03 05:44 UTC, hiljusti commented
@subnut How's it look?

2022-04-07 04:17 UTC, merged