New package: telegram-tg-0.12.0
void-linux/void-packages pull request #30458
Opened 2021-04-23 18:27 UTC by begss

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-04-25 18:30 UTC, Piraty commented
please take a look at why `do_check()` fails for some archs

2021-04-25 21:42 UTC, FollieHiyuki commented
There is no test to run so we should add `do_check=no` there.
And don't add `fzf, urlview, ffmpeg` to depends. They are optional.

2021-04-26 18:36 UTC, FollieHiyuki commented
You can pull the distfile for `python3-telegram` from Github, so that we don't need to vendor the LICENSE file.
And 0.16.0 came out

2021-04-26 19:53 UTC, Piraty requested changes

2021-04-26 19:53 UTC, Piraty commented on srcpkgs/python3-telegram/template
> +distfiles="${PYPI_SITE}/p/python-telegram/python-telegram-${version}.tar.gz"
if it's feasable, please use source tarball from github and don't vendor the license here.

2021-04-26 19:53 UTC, Piraty commented on srcpkgs/python3-telegram/template
> +do_configure() {
make that post_extract

2021-05-01 14:53 UTC, Piraty requested changes

2021-05-01 14:53 UTC, Piraty commented on srcpkgs/python3-telegram/patches/use-system-tdlib.patch
> ++    return '/usr/lib/libtdjson.so.1.7.0'
any chance you can make that find the correct file dynamically instead?

2021-05-10 09:56 UTC, Piraty requested changes

2021-05-10 09:56 UTC, Piraty commented on srcpkgs/python3-telegram/patches/use-system-tdlib.patch
> ++            library_path = 'libtdjson.so.1.7.0'
as asked earlier: can you make this forward-compatible? else this patch needs adaptation should the lib's version change and it might be missed

2021-05-16 16:11 UTC, Piraty requested changes

2021-05-16 16:11 UTC, Piraty commented on srcpkgs/python3-telegram/patches/use-system-tdlib.patch
> +diff --git a/telegram/tdjson.py b/telegram/tdjson.py
leave a comment where you got this from + upstream issue

2021-05-17 12:07 UTC, merged