umurmur: remove shmapi config, crash somtimes the server, no response…
void-linux/void-packages pull request #31158
Opened 2021-05-28 04:16 UTC by pfpulux

… from upstream

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-05-31 21:34 UTC, ericonr commented
Can you link the bug report?

2021-06-15 10:13 UTC, Piraty requested changes

2021-06-15 10:13 UTC, Piraty commented on srcpkgs/umurmur/template
> -configure_args="--enable-shmapi --with-ssl=openssl"
i'd vote do explicitly disable and link related bug reports at least in the commit

2021-06-15 10:13 UTC, Piraty commented
also @Duncaen (maintainer)

2022-06-04 02:08 UTC, closed without merging