New package: cargo-update-7.0.1
void-linux/void-packages pull request #32760
Opened 2021-08-30 12:47 UTC by jcgruenhage

This came up while using topgrade recently, so considering we're shipping topgrade, we should ship this too IMO.

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Remaining TODOs:

- [ ]  disable self-update

2021-11-08 22:58 UTC, Piraty requested changes

2021-11-08 22:58 UTC, Piraty commented on srcpkgs/cargo-update/template
> +	cd ..
this is superfluous

2021-11-09 09:30 UTC, jcgruenhage commented on srcpkgs/cargo-update/template
> +	cd ..
Gone now

2022-06-11 14:04 UTC, jcgruenhage commented
PR is not actually stale

2022-06-22 22:11 UTC, Piraty commented
can you please rebase, so CI is triggered again

2022-09-21 11:04 UTC, jcgruenhage commented
updated again, retriggered CI

2022-09-21 21:03 UTC, merged