proot: update to 5.2.0.
void-linux/void-packages pull request #33272
Opened 2021-10-02 20:12 UTC by Goorzhel

- Delete obsolete patches and fix the rest.
- Add pkg-config (otherwise, undefined talloc_* refs abound).
- Use docs/GNUMakefile to generate manpage.

I could still use some help getting this to cross-compile on ARM architectures; whenever I try it, I get `pkg-config: No such file or directory`. It could be the case that I'm simply using `pkg-config` wrong (my C isn't great, to be honest).

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

2021-10-03 01:10 UTC, Goorzhel commented
Another foible: `src/Makefile` depends on CWD being a Git repo:
```
GIT_VERSION := $(shell git describe --tags `git rev-list --tags --max-count=1`)

GIT_COMMIT := $(shell git rev-list --all --max-count=1 | cut -c 1-8)

VERSION = $(GIT_VERSION)-$(GIT_COMMIT)
```
So the Void package, being built from a tarball, does this —
```
❯ proot --version | head -4
 _____ _____              ___
|  __ \  __ \_____  _____|   |_
|   __/     /  _  \/  _  \    _|
|__|  |__|__\_____/\_____/\____| -
```
— instead of `5.2.0-d0a02a66`.

2021-10-04 00:24 UTC, Goorzhel commented
Rebasing for [new mirror](https://voidlinux.org/news/2021/10/mirror-retirement.html).

2021-10-04 18:58 UTC, Piraty requested changes
please fix cross compilation

last time i heard about it, we discussed removing this package from the tree...

2021-10-04 18:58 UTC, Piraty commented on srcpkgs/proot/template
> +makedepends="libarchive-devel talloc-devel python3-docutils pkg-config python3-lxml"
those are host dependencies

2021-10-08 00:28 UTC, Goorzhel commented
No, it had worked when I compiled it in x64 but I didn't try it in ARM. 🤦‍♂️ _Now_ it should be good.

2021-10-30 23:17 UTC, Piraty requested changes
good to merge otherwise

2021-10-30 23:17 UTC, Piraty commented on srcpkgs/proot/patches/disable-seccomp-based-tracing.patch
> -Bug: https://github.com/proot-me/PRoot/issues/106
do not remove reference to issue

2021-10-30 23:17 UTC, Piraty commented on srcpkgs/proot/patches/disable-seccomp-based-tracing.patch
> -# reason: https://github.com/proot-me/proot/issues/106
do not remove reference to origin

2021-10-30 23:17 UTC, Piraty commented on srcpkgs/proot/template
> +hostmakedepends="python3-docutils pkg-config python3-lxml"
sort the entries

2021-11-05 22:52 UTC, closed without merging