[WIP]New package: helvum-0.3.1
void-linux/void-packages pull request #34560
Opened 2021-12-15 23:51 UTC by xaltsc

This package does not build because rust is too old. Waitin for #32555 to be merged.

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

2021-12-17 21:15 UTC, Roger-Roger-debug commented
Shouldn't the homepage be [https://gitlab.freedesktop.org/ryuukyu/helvum](https://gitlab.freedesktop.org/ryuukyu/helvum)?

2022-01-05 09:38 UTC, dkwo commented
Would you like to try again now?

2022-01-09 00:04 UTC, classabbyamp requested changes
I was able to successfully build and install `helvum` on x86_64 glibc. However, upon launching, I get this error and nothing else happens:

```
$ helvum 
helvum: symbol lookup error: /usr/lib64/libgtk-4.so.1: undefined symbol: pango_attr_word_new
```

Also, v0.3.2 is available from upstream now, and it has the same error as above

2022-01-09 10:39 UTC, Roger-Roger-debug commented
`libgtk-4.so.1` is provided by gtk4, so it should be added as a dependency (maybe even pipewire?). Also when compiling I get the warning
```
warning: the cargo feature `edition2021` has been stabilized in the 1.56 release and is no longer necessary to be listed in the manifest
```
so we can probably remove the configure bit.

2022-02-13 13:56 UTC, dkwo commented
This builds and installs fine for me on `x86_64-musl`.
```
# Template file for 'helvum'
pkgname=helvum
version=0.3.4
revision=1
build_style="meson"
hostmakedepends="cargo pkg-config"
makedepends="clang gtk4-devel pipewire-devel desktop-file-utils
 glib-devel appstream-glib-devel"
depends="gtk4 pipewire dbus"
short_desc="GTK patchbay for pipewire"
maintainer="xaltsc <hey+dev@xaltsc.dev>"
license="GPL-3.0-only"
homepage="https://gitlab.freedesktop.org/ryuukyu/helvum"
distfiles="https://gitlab.freedesktop.org/ryuukyu/helvum/-/archive/${version}/helvum-${version}.tar.gz"
checksum=e19054f3bcd1ba234c451134fe7f4c6afee35f108c122642c1d502fc16785c02
```
Anyone @xaltsc @Roger-Roger-debug @classabbyamp interested in updating this PR, or creating a new one?

2022-02-13 20:30 UTC, dkwo commented
Well, pipewire requires dbus anyway, right?

2022-03-07 18:10 UTC, xaltsc commented
Sorry for the delay, given that this PR #35591 seems to be going well, should I close this PR or can I help in some way ?

2022-03-07 23:05 UTC, classabbyamp commented
I think that PR is just waiting for a maintainer approval. If you'd like to test it that'd be great but otherwise I don't think there's anything to do.

2022-03-14 07:08 UTC, closed without merging