kafkacat: rename to kcat and update to kcat-1.7.0
void-linux/void-packages pull request #34871
Opened 2022-01-05 19:22 UTC by TeddyDD

#### Testing the changes
- I tested the changes in this PR: **YES**

2022-02-12 21:23 UTC, jcgruenhage commented on srcpkgs/kcat/template
> +replaces="kafkacat>=1.6.0"
The manual was missing a section on renaming packages, but assuming that @Chocimier opened https://github.com/void-linux/void-packages/pull/34875/files in response to this, I'd like to point you there. The way you renamed the package here is not sufficient.

2022-02-12 21:23 UTC, jcgruenhage requested changes
The manual was missing a section on renaming packages, but assuming that @Chocimier opened https://github.com/void-linux/void-packages/pull/34875/files in response to this, I'd like to point you there. The way you renamed the package here is not sufficient.

2022-02-12 21:42 UTC, Chocimier commented
Yes, his needs to be improved. Thanks for bumping.

I haven't seen this, and written that section after it was suggested at #34581.

2022-02-13 08:30 UTC, jcgruenhage commented
Ah, okay. I thought that you had written it in response to this because it came on the same day and specifically mentions the issues I've seen while going through this one here :D

2022-03-13 00:54 UTC, ahesford commented
https://github.com/void-linux/void-packages/issues/36116

2022-03-13 00:54 UTC, closed without merging