New package: ouch-0.3.1
void-linux/void-packages pull request #34931
Opened 2022-01-07 21:36 UTC by ElDifinitivo

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

2022-01-07 21:39 UTC, abenson commented on srcpkgs/ouch/template
> +hostmakedepends="liblzma-devel bzip2-devel libzip-devel"
This should be `makedepends`

2022-01-07 21:39 UTC, abenson commented on srcpkgs/ouch/template
> +	vlicense LICENSE license.txt
Just `vlicense LICENSE`, don't rename it

2022-01-14 15:26 UTC, ElDifinitivo commented
Forgot to mention but template issues have been resolved

2022-02-12 21:46 UTC, jcgruenhage requested changes
`ouch` can generate completions at compile time, which you can enable using

```bash
pre_build() {
	export GEN_COMPLETIONS=1
}
```

then you can do something like this:
```
vcompletion "path/to/_ouch" zsh
vcompletion "path/to/ouch.fish" fish
vcompletion "path/to/ouch.bash" bash
```
in your `post_install` function. 

Aside of completions missing: looks good to me, and looking forward to using `ouch`

2022-02-13 09:27 UTC, jcgruenhage commented
So, I was nerd-sniped a bit by this, and wanted to get the completions working at least locally. This turned out to be a slight bit more difficult than anticipated, resulting in two patches I'll submit upstream. One for allowing to override the location of the completions, and one for working around https://github.com/clap-rs/clap/issues/1596.

The resulting template and patches can be found at https://github.com/void-linux/void-packages/commit/44cefdee00b3b8ac0a309819fd3fbfce5e24bb08.

@ElDifinitivo Which one would you prefer, including those changes into your PR, or me opening a PR myself?

2022-02-13 17:18 UTC, jcgruenhage commented
Sounds good to me :)

2022-02-14 07:20 UTC, paper42 commented
@ElDifinitivo please rebase on top of master to fix CI

2022-03-03 21:50 UTC, merged