pam_rundir: fix conditional and set the user gid for the dir.
void-linux/void-packages pull request #35212
Opened 2022-01-23 22:00 UTC by travankor

#### Testing the changes
- I tested the changes in this PR: **briefly**

2022-02-25 11:55 UTC, Piraty requested changes

2022-02-25 11:55 UTC, Piraty commented on srcpkgs/pam_rundir/patches/fix2.patch
> +diff --git a/pam_rundir.c b/pam_rundir.c
i assume you got this from here? https://github.com/jjk-jacky/pam_rundir/pull/5/
please put a reference, (same for the other patches)

2022-02-26 00:33 UTC, merged

2022-02-26 13:25 UTC, eoli3n commented
I have a problem when disconnecting from my session. I can't run sway anymore, I need to reboot to be able to relaunch a new sway session. I get an error "XDG_DIR not set". Do you experienced that issue ?

2022-02-26 21:55 UTC, Piraty commented
@eoli3n is this caused by these patches? (test by downgrading pam_rundir to previous version)

2022-02-27 17:12 UTC, eoli3n commented
No, just a general question.

2022-02-28 12:55 UTC, travankor commented
If it's not related to this PR, could you please open a separate issue, instead? I have not run into that issue if I understood correctly, though.