tigervnc: update to 1.12.0
void-linux/void-packages pull request #35249
Opened 2022-01-26 16:58 UTC by Emru1

#### Testing the changes
- I tested the changes in this PR: **YES**

 
#### Local build testing
- I built this PR locally for my native architecture, (amd64, amd64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv7l

Builded and tested on amd64, builded on amd64-musl, crossbuilded on amd64 for armv7l.
TigerVNC now demands presence of PAM

2022-03-18 18:28 UTC, ahesford requested changes

2022-03-18 18:28 UTC, ahesford commented on srcpkgs/tigervnc/template
> +hostmakedepends="automake gettext xorg-util-macros font-util pkg-config libtool xtrans pam"
`pam` isn't required in `hostmakedepends`; adding `pam-devel` to `makedepends` is sufficient.

2022-03-18 18:28 UTC, ahesford commented on srcpkgs/tigervnc/template
> + libxshmfence-devel"
Please re-wrap to 80 columns.

2022-03-18 18:28 UTC, ahesford commented on srcpkgs/tigervnc/template
> +depends="perl xauth xkeyboard-config pam"
Drop `pam` from `depends`; just let `xbps-src` automatically resolve the `pam-libs` dependency.

2022-04-12 08:06 UTC, Emru1 commented
@ahesford

2022-07-28 02:15 UTC, closed without merging