New package: onlyoffice
void-linux/void-packages pull request #36279
Opened 2022-03-22 14:10 UTC by Toromino

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Description
This PR adds a new template for OnlyOffice desktop editors.

2022-03-23 07:44 UTC, Toromino commented
Fixed the lint warnings and also copy the licenses now

2022-03-27 18:20 UTC, Vaelatern requested changes
This can't be accepted if it's just a binary download.

Either close the PR, or rework to do an actual compile and build.

2022-03-27 18:20 UTC, Vaelatern commented on srcpkgs/onlyoffice/template
> +hostmakedepends="tar xz"
not needed

2022-03-27 18:20 UTC, Vaelatern commented on srcpkgs/onlyoffice/template
> +archs="x86_64"
why? At least comment why.

2022-03-27 18:20 UTC, Vaelatern commented on srcpkgs/onlyoffice/template
> +depends="libstdc++ curl xdg-utils dejavu-fonts-ttf GConf gtk+3 liberation-fonts-ttf libpulseaudio gstreamer1 nss alsa-lib gst-plugins-base1 gst-plugins-ugly1 nspr hicolor-icon-theme"
.... is this just a download of a binary and extraction?

2022-03-27 18:20 UTC, Vaelatern commented on srcpkgs/onlyoffice/template
> +distfiles="https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v${version}/onlyoffice-desktopeditors_amd64.deb"
Yep.

Not accepted. We don't need more big binary blobs we just download. We prefer to build these things ourself.

2022-03-27 20:01 UTC, Toromino commented
> This can't be accepted if it's just a binary download.
> 
> Either close the PR, or rework to do an actual compile and build.

Sorry. I did not know, it **had** to be compiled. I will rework it.

2022-07-15 02:14 UTC, closed without merging