[WIP] occt: update to 7.6.1
void-linux/void-packages pull request #36356
Opened 2022-03-26 04:42 UTC by karl-nilsson

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x64-glibc

Like previously, broken ABI
```console
During initialization the error "/usr/lib/freecad/lib64/Part.so: undefined symbol: _ZN24BRepBuilderAPI_MakeShape5BuildEv" occurred in /home/nilsson/.FreeCAD/Mod/A2plus/InitGui.py                                                                                                                        
Please look into the log file for further information                                                                                                
Wizard shaft module cannot be loaded                                                                                                                 
/usr/lib/freecad/lib64/Part.so: undefined symbol: _ZN24BRepBuilderAPI_MakeShape5BuildEv                                                              
connect failed: No such file or directory      
```

Looks like we'll have to update or patch freecad
```console
In file included from /usr/include/opencascade/Extrema_POnSurf.lxx:15,
                 from /usr/include/opencascade/Extrema_POnSurf.hxx:75,
                 from /usr/include/opencascade/Extrema_ExtPElS.hxx:27,
                 from /usr/include/opencascade/Extrema_ExtPS.hxx:24,
                 from /usr/include/opencascade/ShapeAnalysis_Surface.hxx:20,
                 from ../src/3rdParty/salomesmesh/inc/SMESH_MesherHelper.hxx:37,
                 from ../src/3rdParty/salomesmesh/src/SMESH/SMESH_Mesh.cpp:34:
/usr/include/opencascade/Precision.hxx:98:7: note: previous definition of 'class Precision'
   98 | class Precision
      |       ^~~~~~~~~

```

ping @Piraty

2022-05-02 14:51 UTC, karl-nilsson commented
I'm just going to wait for the release of freecad v0.20. There's a slew of patches required to build with occt 7.6.x

2022-07-24 04:11 UTC, luzpaz commented
Thanks for you work on this!

2022-07-25 03:38 UTC, karl-nilsson commented
@Piraty I think it's ready

@yopito I updated FreeCAD to v0.20, and it looks like most of the patches were upstreamed. Could you please double-check my work?

2022-07-26 03:39 UTC, yopito requested changes
other points in freecad/template:
* add `python3-pivy` in `makedepends`:
    ```diff
    - qt5-xmlpatterns-devel coin3-doc glew-devel"
    + qt5-xmlpatterns-devel coin3-doc glew-devel python3-pivy"
    ```
* apply this change too:
    ```diff
    -# FreeCAD help: qt5/assistant with SQLite storage
    -depends="python3-matplotlib python3-pyside2 qt5-plugin-sqlite python3-pivy"
    +depends="python3-matplotlib python3-pyside2-webengine python3-pivy"
    ```

2022-07-26 03:39 UTC, yopito commented on srcpkgs/freecad/template
> -
don't remove this vsed: will be usefull on next minor minor release

2022-07-26 03:40 UTC, yopito commented
regarding FreeCAD 0.20 (only): I have some WIP on it, here some points about it:
* help is not generated anymore from source by available (only) from online: see my review of your freecad/template
* `freecad/patches/010-salomesmesh-execinfo.patch` is uneeded anymore
* I've also update libspnav to 1.0 on my side, so additional patch for freecad is needed: could you add these into your commits ?
    * libspnav : update to 1.0: https://gist.github.com/yopito/2757c1a501e2772143814b4a3553cbea
    * freecad: : fix PATH_MAX on musl libc : https://gist.github.com/yopito/fd25b30edcbc762babd9069641a9b86e
* another fix:
    * freecad: : fix build (stderr resource is readonly): https://gist.github.com/yopito/3ac7d4c8fee646171ca900ff17452567
* I have some SIGSEGV on running FreeCAD (x86_64 musl)  when it's using Coin/pivy and shiboken2/pyside2 in 5.15.5 (in WIP) : don't know yet if related to shiboken2/pyside2 in 5.15.5 : see https://github.com/coin3d/pivy/issues/98
   => could you run at least `FreeCAD  -t MeshTestsApp` to see if you have the same trouble ?

2022-08-12 09:12 UTC, yopito commented
hello, any news regarding FreeCAD packaging ?

2022-08-12 14:24 UTC, luzpaz commented
JFYI, OCCT release v7.6.3 has been [released](https://github.com/Open-Cascade-SAS/OCCT/releases/tag/V7_6_3)

2022-08-22 11:48 UTC, yopito commented
hello, since this PR looks stale, I will shortly open another PR focused on freecad 0.20.1 and related updated stuff  (pyside2, libspnav).
Then this one could focus on OCCT solely ?

2022-08-22 13:59 UTC, karl-nilsson commented
> hello, since this PR looks stale, I will shortly open another PR focused on freecad 0.20.1 and related updated stuff (pyside2, libspnav). Then this one could focus on OCCT solely ?
> 
> Edit: this is just a proposal, don't hesitate to react.

Please do!
I've been swamped with work lately, I should have some time in the coming weeks to finish this PR.

2022-08-23 13:29 UTC, yopito commented
> > hello, since this PR looks stale, I will shortly open another PR focused on freecad 0.20.1 and related updated stuff (pyside2, libspnav). Then this one could focus on OCCT solely ?
> > Edit: this is just a proposal, don't hesitate to react.
> 
> Please do! I've been swamped with work lately, I should have some time in the coming weeks to finish this PR.

OK, thanks. Here it is: #38856 
I suggest to close this PR ?

2022-09-27 19:34 UTC, enderger commented
For the musl build, `libexecinfo-devel` should allow it to work. Got about 75% through the build after adding it to the dependency list.

2022-12-19 00:31 UTC, Piraty commented
ping

2023-01-20 03:23 UTC, luzpaz commented
any more traction here ?

2023-04-24 22:33 UTC, luzpaz commented
bump

2023-04-30 19:32 UTC, Piraty commented
I assume no. anyone interested in picking up is welcome to open a new PR

2023-04-30 19:32 UTC, closed without merging