New package: python3-pathvalidate-2.5.0
void-linux/void-packages pull request #37549
Opened 2022-06-13 17:33 UTC by nbelikov

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES** (this package is a new requirement for `Electron-Cash`).

#### Local build testing
- I built this PR locally for my native architecture, (ARCH-LIBC)

2022-06-13 17:44 UTC, classabbyamp requested changes

2022-06-13 17:44 UTC, classabbyamp commented on srcpkgs/python3-pathvalidate/template
> +
```suggestion
```

2022-06-13 17:44 UTC, classabbyamp commented on srcpkgs/python3-pathvalidate/template
> +
```suggestion
```

2022-06-13 17:44 UTC, classabbyamp commented on srcpkgs/python3-pathvalidate/template
> +# pytest-md-report.
(nitpick) this would be fine as one line, i think

2022-06-13 17:44 UTC, classabbyamp commented on srcpkgs/python3-pathvalidate/template
> +depends="python3>=3.6"
```suggestion
depends="python3"
```
it is extremely unlikely that `python3` would get downgraded below 3.6 at any time.

2022-06-13 18:09 UTC, nbelikov commented
Thanks for review, I applied your suggestions.

2022-06-16 16:57 UTC, nbelikov commented
Superseded by  #37568

2022-06-16 16:57 UTC, closed without merging