New package: drivestrike-2.1.20
void-linux/void-packages pull request #38917
Opened 2022-08-26 08:00 UTC by jcgruenhage

Not sure if this is interesting for anyone here, but we have to deploy this onto our machines for work, so I created this template to install it on my work laptop. EULA says no copies except for subscribers installing it onto their systems, so `restricted` it is.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

2022-11-25 17:11 UTC, madonius commented
I would propose updating the Package to 2.1.21-2.
Moreover, I would recommend extracting the information from the [Packages](https://app.drivestrike.com/static/apt/dists/stretch/main/binary-amd64/Packages) file

2022-11-26 16:06 UTC, jcgruenhage commented
Automatically extracting that for the sake of the template doesn't make much sense, but using the Packages file for the `update` file to fetch what the most recent version is would definitely make sense. Thanks for the hint :)

2022-12-14 00:19 UTC, Piraty commented on srcpkgs/drivestrike/template
> +	ar x "${_filename}"
look at c18090b458b704ca314d76c4e198a546443ae168

2022-12-14 07:55 UTC, jcgruenhage commented on srcpkgs/drivestrike/template
> +	ar x "${_filename}"
lgtm, will adapt. Thanks!

2023-03-05 22:33 UTC, Piraty requested changes

2023-03-05 22:33 UTC, Piraty commented on srcpkgs/drivestrike/files/drivestrike/log/run
> +/usr/bin/vlogger
see https://github.com/void-linux/void-packages/pull/42026

2023-04-09 20:06 UTC, merged