python3-cssutils: update to 2.6.0.
void-linux/void-packages pull request #40408
Opened 2022-11-09 10:34 UTC by Emru1

#### Testing the changes
- I tested the changes in this PR: **briefly**
- I built this PR locally for my native architecture, amd64

This package was strange, when I was updating to python3.11, byte-compile thrown errors about syntax, code looked like python2

2022-11-11 09:57 UTC, icp1994 requested changes

2022-11-11 09:57 UTC, icp1994 commented on srcpkgs/python3-cssutils/template
> +hostmakedepends="python3-setuptools python3-setuptools_scm python3-wheel"
```suggestion
hostmakedepends="python3-setuptools python3-setuptools_scm python3-wheel"
depends="python3"
```

2022-11-11 09:57 UTC, icp1994 commented on srcpkgs/python3-cssutils/template
>  homepage="https://pypi.org/project/cssutils/"
```suggestion
homepage="https://pypi.org/project/cssutils/"
changelog="https://raw.githubusercontent.com/jaraco/cssutils/main/CHANGES.rst"
```

2022-11-12 16:11 UTC, Emru1 commented
Hey, @icp1994 
I added your suggestions. Is this template good now?

2022-11-12 16:35 UTC, icp1994 commented
Seems fine to me.

2023-02-25 02:01 UTC, closed without merging

2023-02-25 12:54 UTC, MarcinWieczorek commented
Bump