octave: update to 7.3.0.
void-linux/void-packages pull request #40720
Opened 2022-11-24 03:02 UTC by tornaria

- Fix cross build
- Use SuiteSparse
- Use rapidjson
- Use --disable-docs to skip building docs, instead install the docs in
  the tarball. This way we don't need texlive/texinfo/gnuplot to build.
- Avoid warnings due to egrep deprecation
- xlint fixes

#### Testing the changes
- I tested the changes in this PR: **briefly**

---

I wonder if we really want all those build options. I am tempted to remove almost all of them.

I also wonder if the choice of `GraphicsMagick` over `ImageMagick` is the best one.

NOTE: this PR includes #39846 for the current SuiteSparse. Could work with the current SuiteSparse, but I didn't try (#39846 is ready to merge IMO; the CI failures in that PR are addressed in the comments)

2022-12-04 14:56 UTC, hervyqa commented
can you please rebase? CI runs again
igraph merged https://github.com/void-linux/void-packages/pull/40224

2022-12-04 21:12 UTC, Piraty commented
remove the suitesparse commits from this branch. #39846 is merged

2022-12-05 09:37 UTC, Piraty requested changes

2022-12-05 09:37 UTC, Piraty commented on srcpkgs/octave/template
> +	vcopy "doc/*/*.1" usr/share/man/man1
use `vman`

2022-12-06 22:11 UTC, tornaria commented
The testsuite was giving a segfault on i686, when using `qr` on a sparse matrix. In fact this is trivial to reproduce:
```
octave:1> qr(sparse(1,1));
fatal: caught signal Segmentation fault -- stopping myself...
Segmentation fault
```
I "solved" it by using `--without-spqr` on i686 builds.

---

Then there are a couple of test failures seemingly due to numerical unstability, but they are not fixed with the standard tricks (`-ffloat-store`, `-mfpmath=sse`, etc). At least one is unrelated to octave as I can reproduce with:
```
$ cat sin.cc 
#include <complex>
#include <iostream>

int main()
{
	std::complex<double> c(-1.3962634015954636, 3.141592653589793);
	std::complex<double> d(-11.415845458288851, 2.0054175437381652);
	std::complex<double> e = std::sin(c) - d;

	std::cout << e << std::endl;
}
$ g++ sin.cc -o sin && ./sin                    
(-1.77636e-15,0)
```
The same code on x86_64 gives `(0,0)`.

2022-12-06 22:54 UTC, tornaria commented
Summary of testsuite (since failures don't error out):
 - on `x86_64`, everything looks ok:
```
Summary:

  PASS                            17107
  FAIL                                0
  XFAIL (reported bug)               33
  SKIP (missing feature)            140
  SKIP (run-time condition)          52
```
 - on `x86_64-musl`, 6 regressions:
```
  libinterp/corefcn/mappers.cc-tst ............................... pass  412/420 
                                                              REGRESSION   6
...
Summary:

  PASS                            17099
  FAIL                                0
  REGRESSION                          6
  XFAIL (reported bug)               35
  SKIP (missing feature)            140
  SKIP (run-time condition)          52
```
 - on `i686`, 2 failures and 1 regression:
```

  libinterp/corefcn/qz.cc-tst .................................... pass    3/4   
                                                                   FAIL    1
  libinterp/corefcn/sqrtm.cc-tst ................................. pass    3/4   
                                                              REGRESSION   1
...
  elfun/sind.m ................................................... pass    9/10  
                                                                   FAIL    1
...
Summary:

  PASS                            17095
  FAIL                                2
  REGRESSION                          1
  XFAIL (reported bug)               30
  SKIP (missing feature)            152
  SKIP (run-time condition)          52
```
Note that `i686` has more skips because of the `--without-spqr`.

I'm satisfied as it is, I'm not going to work on fixing these unless this causes some real issue for someone.

2022-12-07 00:14 UTC, Piraty commented
good work!!

2022-12-07 00:14 UTC, merged