[WIP] New package: ntfy-1.30.1
void-linux/void-packages pull request #41427
Opened 2023-01-03 17:43 UTC by TinfoilSubmarine

#### Testing the changes
- I tested the changes in this PR: **YES**

Closes https://github.com/void-linux/void-packages/issues/41422

I am using this exclusively for the server functionality as I am using the ntfy android app as the client. @biopsin did you require any additional services for the client side?

2023-01-03 20:13 UTC, biopsin commented
@TinfoilSubmarine 
Whosh that was fast, thougth I would tinker with this upcomming weekend.
Honestly I just discovered it and have not had the time to investigate all aspects, so Im unaware off any services I might require for the moment. Tnx.

2023-01-03 21:45 UTC, TinfoilSubmarine commented
Don't give me too much credit for it, I had just been working on it the week before :)

For now it just has the service for running the server (meaning `ntfy serve`) since that was the functionality I needed--it seems that the Gotify-UP android app no longer exists and so I need a new UnifiedPush solution.

2023-01-05 15:13 UTC, TinfoilSubmarine commented
OK, I fixed the webapp not showing. As far as a client service replicating the [systemd service in the upstream source](https://github.com/binwiederhier/ntfy/blob/main/client/ntfy-client.service), I don't know if this makes much sense since likely a user would just want to have a per-user runit service.

2023-01-05 15:32 UTC, TinfoilSubmarine commented
Added a data directory so the server can use the cache/auth file.

2023-01-22 21:14 UTC, Piraty commented
is this ready? (if not, please prefix `WIP` to the title until it is)

2023-01-22 21:29 UTC, TinfoilSubmarine commented
> is this ready? (if not, please prefix `WIP` to the title until it is)

Yes, it is ready

2023-02-15 22:48 UTC, Piraty requested changes

2023-02-15 22:48 UTC, Piraty commented on srcpkgs/ntfy/files/ntfy-server/log/run
> +/usr/bin/vlogger
see https://github.com/void-linux/void-packages/pull/42026

2023-02-15 22:51 UTC, TinfoilSubmarine commented on srcpkgs/ntfy/files/ntfy-server/log/run
> +/usr/bin/vlogger
Fixed, thanks

2023-02-16 22:52 UTC, merged