New package: newsraft-0.15
void-linux/void-packages pull request #41490
Opened 2023-01-06 12:03 UTC by txgk

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

2023-01-06 13:43 UTC, icp1994 requested changes

2023-01-06 13:43 UTC, icp1994 commented on srcpkgs/newsraft/template
> +makedepends="libcurl-devel expat-devel gumbo-parser-devel ncurses-devel scdoc sqlite-devel yajl-devel"
```suggestion
make_install_args="EXAMPLES_DIR=${DESTDIR}/usr/share/examples/newsraft"
hostmakedepends="scdoc"
makedepends="libcurl-devel expat-devel gumbo-parser-devel ncurses-devel
 sqlite-devel yajl-devel"
```

2023-01-06 13:43 UTC, icp1994 commented on srcpkgs/newsraft/template
> +distfiles="${homepage}/archive/${pkgname}-${version}.tar.gz"
```suggestion
distfiles="https://codeberg.org/grisha/newsraft/archive/newsraft-${version}.tar.gz"
```

2023-01-06 13:47 UTC, txgk commented on srcpkgs/newsraft/template
> +makedepends="libcurl-devel expat-devel gumbo-parser-devel ncurses-devel scdoc sqlite-devel yajl-devel"
Applied it, thank you!

2023-01-06 13:48 UTC, txgk commented on srcpkgs/newsraft/template
> +distfiles="${homepage}/archive/${pkgname}-${version}.tar.gz"
Fixed now

2023-01-14 14:34 UTC, daniel-eys commented
Tested this for a couple of days now. Working great, thanks!

2023-01-26 09:52 UTC, daniel-eys approved these changes

2023-02-01 13:41 UTC, txgk commented
Never mind

2023-02-01 13:42 UTC, closed without merging