nmap: update to 7.93
void-linux/void-packages pull request #41520
Opened 2023-01-08 17:05 UTC by pascal-huber

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures:
  - x86_64-musl
  - aarch64 (crossbuild)
  - armv7l (crossbuild)

#### Notes

- There were some licensing issues (see #27866). While nmap version 7.90, 7.91 and 7.92 could have been distributed using the old (good) license, 7.93 is the first nmap release which comes exclusively under the custom "Nmap Public Source License" (NPSL) [[1]]. However, the issues with previous versions of this license seem to have been solved in version 0.94 (of the license). Fedora added it to their list of "Good Licenses" [[2]]. Fedora as well as Gentoo both have nmap version 7.93 in their repos [[3],[4]].
- `openssl.patch` fixes namp issue 2516.
- `gcc12.patch` seems not to be needed anymore.

[1]: https://nmap.org/npsl/
[2]: https://fedoraproject.org/wiki/Licensing:Main
[3]: https://src.fedoraproject.org/rpms/nmap
[4]: https://packages.gentoo.org/packages/net-analyzer/nmap

2023-01-09 15:44 UTC, leahneukirchen commented
AFAICS the license doesn't restrict redistribution of binaries, so we can just package it. Let's just slap `repository=nonfree` on it and be done.

2023-01-09 17:23 UTC, pascal-huber commented
> AFAICS the license doesn't restrict redistribution of binaries, so we can just package it. Let's just slap `repository=nonfree` on it and be done.

Thanks! \*slap\*, done.

2023-01-10 15:32 UTC, leahneukirchen requested changes

2023-01-10 15:32 UTC, leahneukirchen commented on srcpkgs/nmap/template
> + libssh2-devel $(vopt_if lua lua53-devel)"
this is a duplicate

2023-01-10 17:26 UTC, merged