devilutionX: switch to the -src tarball; drop gettext
void-linux/void-packages pull request #41678
Opened 2023-01-16 10:16 UTC by kruceter

One of the upstream maintainers (glebm) suggested[^1] to use the `src` tarball instead of `src-fully-vendored`, which does not bundle libraries already available in the repository (SDL2, SDL2_image, libfmt, bzip2, libsodium, googletest) without the need to specify dedicated configure flags for them.

gettext is used for generating `libdevilutionX.mpq` but not required here because it is shipped in the tarball.

Rebuild is not required as the result is the same: shlibs, extracted files, configuration are identical.

#### Testing the changes
- I tested the changes in this PR: **YES**

[^1]: https://github.com/diasurgical/devilutionX/issues/5664#issuecomment-1383685675

2023-01-17 23:31 UTC, paper42 commented
@bugcrazy would you mind reviewing these changes?

2023-01-18 00:24 UTC, bugcrazy commented
> @bugcrazy would you mind reviewing these changes?

I reviewed the changes, it's all right (okay)!

2023-01-18 01:00 UTC, bugcrazy requested changes

2023-01-18 01:20 UTC, kruceter commented on srcpkgs/devilutionX/template
>  revision=1
Why should I do that? Whatever I have done here does not affect the distributed package at all (see CI's "compare to previous" output).

The commit message written by me has the following reasoning:

```
Rebuild is not required as the result is the same: shlibs, extracted files, configuration are identical.
```

2023-01-18 01:32 UTC, ahesford commented on srcpkgs/devilutionX/template
>  revision=1
You're changing the source tarball and the arguments passed at configuration time. Whether the metadata appears different or not, the revision should be bumped.

2023-01-18 01:38 UTC, kruceter commented on srcpkgs/devilutionX/template
>  revision=1
Done!

2023-01-18 04:50 UTC, merged