liferea: update to 1.14.0.
void-linux/void-packages pull request #41902
Opened 2023-01-27 17:53 UTC by geekdiop

Testing the changes
- I tested the changes in this PR: **YES**

2023-04-01 00:18 UTC, duskull88 commented
There is 1.14.4 now, but it cannot be compiled on Void, as discussed here: `https://github.com/lwindolf/liferea/issues/1209`

2023-04-01 19:56 UTC, Chocimier commented
1.14.4 builds within xbps-src just fine

2023-05-03 20:54 UTC, zen0bit commented on srcpkgs/liferea/template
> +version=1.14.0
version=1.14.5

2023-05-03 20:54 UTC, zen0bit commented on srcpkgs/liferea/template
> +checksum=b82de4b09e27357063418a8d392e2a2ba6822bafd6cdfdbb6171db33bdd3a5d5
checksum=2244e78d8f6b6e28f411a3554d61496a012d5fe1392fe1b475978ecfd8c61177

2023-05-03 20:58 UTC, zen0bit requested changes
new stable version out...

2023-05-03 21:01 UTC, zen0bit requested changes
1.14.5 stable is out

2023-05-03 21:01 UTC, zen0bit commented on srcpkgs/liferea/template
> +checksum=b82de4b09e27357063418a8d392e2a2ba6822bafd6cdfdbb6171db33bdd3a5d5
```suggestion
checksum=2244e78d8f6b6e28f411a3554d61496a012d5fe1392fe1b475978ecfd8c61177
```

2023-06-27 11:41 UTC, Duncaen commented
Merged as https://github.com/void-linux/void-packages/commit/00c969b44c4963c54e8a08c8ef982ed64bdbe58c.

2023-06-27 11:41 UTC, closed without merging