New package: cloudflare-warp-2023.1.133_1
void-linux/void-packages pull request #42005
Opened 2023-01-31 21:02 UTC by 2trvl

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

2023-05-02 19:13 UTC, Duncaen requested changes
The whole logging mechanism diverts from any other service packaged and I don't think this is necessary. Just use `vlogger(1)` in the log service and let the user decide to log messages in any other way.

Commits should be squashed and follow the format in https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md.

2023-05-02 19:13 UTC, Duncaen commented on srcpkgs/cloudflare-warp/template
> +license="Unknown"
This should probably be something like `custom: Proprietary`.

2023-05-02 19:13 UTC, Duncaen commented on srcpkgs/cloudflare-warp/template
> +archs="i686 x86_64"
You are only downloading and packaging `x86_64` binaries.

2023-05-02 19:13 UTC, Duncaen commented on srcpkgs/cloudflare-warp/template
> +_debpkgid="cloudflare_warp_2023_3_398_1_amd64_002e48d521.deb"
`${version//./_}` instead of hard coding the version, maybe also add the `1` to the version.

2023-08-15 12:35 UTC, 2trvl commented
bump

2023-08-15 13:00 UTC, closed without merging