ibus-libpinyin: update to 1.15.0
void-linux/void-packages pull request #42031
Opened 2023-02-02 11:25 UTC by LMFuture-Me

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

2023-02-02 11:37 UTC, sgn requested changes
Please also revbump `fcitx-libpinyin`, `fcitx5-libzhuyin`

2023-02-02 11:37 UTC, sgn commented on common/shlibs
> +libzhuyin.so.15 libzhuyin-2.8.1_1
```suggestion
libpinyin.so.15 libpinyin-2.8.1_1
libzhuyin.so.15 libzhuyin-2.8.1_1
```

2023-02-02 11:37 UTC, sgn commented on srcpkgs/libpinyin/template
> +		vmove "usr/include/libpinyin-2.8.1/novel*"
```suggestion
		vmove "usr/include/libpinyin-${version}/novel*"
```

2023-02-02 11:37 UTC, sgn commented on srcpkgs/libpinyin/template
> +		vmove "usr/include/libpinyin-2.8.1/pinyin*"
```suggestion
		vmove "usr/include/libpinyin-${version}/pinyin*"
```

2023-02-02 11:37 UTC, sgn commented on srcpkgs/libpinyin/template
> +		vmove "usr/include/libpinyin-2.8.1/zhuyin*"
```suggestion
		vmove "usr/include/libpinyin-${version}/zhuyin*"
```

2023-02-02 11:43 UTC, LMFuture-Me commented
> 

its the latest version of fcitx-libpinyin and fcitx5-libzhuyin

2023-02-02 11:49 UTC, LMFuture-Me commented
> Please also revbump `fcitx-libpinyin`, `fcitx5-libzhuyin`

This is their latest version. Should they be deleted before they are updated?

2023-02-02 12:14 UTC, sgn commented
> This is their latest version. Should they be deleted before they are updated?

No, just increase their revision is enough (like I did for you).

Anyway, please make a commit with valid email.

2023-02-02 12:16 UTC, LMFuture-Me commented
> 



> > This is their latest version. Should they be deleted before they are updated?
> 
> No, just increase their revision is enough (like I did for you).
> 
> Anyway, please make a commit with valid email.

2023-02-02 12:17 UTC, LMFuture-Me commented
> > This is their latest version. Should they be deleted before they are updated?
> 
> No, just increase their revision is enough (like I did for you).
> 
> Anyway, please make a commit with valid email.

thank you very much. i am new here

2023-02-02 16:00 UTC, sgn commented
Nope, I asked to make your git author email.

Please do it by:
```sh
git config --global user.name <put-your-name-here>
git config --global user.email <put-your-email-here>
git commit --amend --reset-author
```

2023-02-02 16:01 UTC, sgn commented
btw, you missed two rev-bumped make by me :(

2023-02-03 01:49 UTC, LMFuture-Me commented
> Nope, I asked to make your git author email.
> 
> Please do it by:
> ```sh
> git config --global user.name <put-your-name-here>
> git config --global user.email <put-your-email-here>
> git commit --amend --reset-author
> ```

fixed

2023-02-05 01:29 UTC, merged