python3-xlib: update to 0.33.
void-linux/void-packages pull request #42205
Opened 2023-02-10 20:16 UTC by mhmdanas

#### Testing the changes
- I tested the changes in this PR: **briefly**

2023-02-11 10:51 UTC, mhmdanas commented
The check failures are also present on python3-xlib 0.30, and I couldn't figure out how to fix them. Disable checks for now?

2023-02-14 00:17 UTC, ahesford requested changes
The changes I suggest will make the tests pass on `x86_64`. I haven't checked the other archs.

2023-02-14 00:17 UTC, ahesford commented on srcpkgs/python3-xlib/template
>  build_style=python3-module
```suggestion
build_style=python3-module
make_check_target="test"
```

2023-02-14 00:17 UTC, ahesford commented on srcpkgs/python3-xlib/template
> +checkdepends="${depends} xvfb-run python3-nose python3-mock"
```suggestion
checkdepends="${depends} xvfb-run python3-pytest-xdist python3-mock"
```

2023-02-14 00:17 UTC, ahesford commented on srcpkgs/python3-xlib/template
> +checksum=b7a45aaf919915f4908e4b2d79fc2ff3abbbec3b801a45162b3d0f67ed581b37
```suggestion
checksum=b7a45aaf919915f4908e4b2d79fc2ff3abbbec3b801a45162b3d0f67ed581b37
make_check_pre="xvfb-run"
```

2023-02-14 00:17 UTC, ahesford commented on srcpkgs/python3-xlib/template
>  do_check() {
You can delete this entire function with the other changes I suggest.

2023-02-14 20:57 UTC, mhmdanas commented
@ahesford I suspect the failing test in the CI is flaky. I _think_ I had the failure happen locally once, but three subsequent runs did not have the same problem.

2023-02-14 21:08 UTC, merged

2023-02-14 21:09 UTC, ahesford commented
Could be a race, and may be exacerbated by pytest-xdist parallelizing things. It passes locally for me, so we can defer a resolution until a later update.