v2ray: update to 5.4.0
void-linux/void-packages pull request #42502
Opened 2023-02-28 15:38 UTC by ipkalm

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686
  - i686-musl
  - aarch64
  - aarch64-musl
  - armv7l
  - armv7l-musl
  - armv6l
  - armv6l-musl
  - ppc64le

2023-02-28 15:47 UTC, ipkalm commented
Locally I built again with `-Q` arg without any errors for `i686`.

2023-06-25 19:10 UTC, Duncaen requested changes
See inline comments.

2023-06-25 19:10 UTC, Duncaen commented on srcpkgs/v2ray/INSTALL.msg
> +instructions.
Please don't add noise install messages, this is not required and results in users just ignoring them all together.

2023-06-25 19:10 UTC, Duncaen commented on srcpkgs/v2ray/REMOVE
> +                [ -d etc/v2ray ] && rmdir etc/v2ray 2>/dev/null
This should not be required. xbps does that.

2023-06-25 19:10 UTC, Duncaen commented on srcpkgs/v2ray/files/v2ray/run
> +exec chpst -e /etc/v2ray/env -u _v2ray v2ray run ${OPTS:- -config=/etc/v2ray/config.json} 2>&1
the conf file can already export environment variables. for consistency with other service please remove it.

2023-06-25 19:10 UTC, Duncaen commented on srcpkgs/v2ray/template
> +	vdoc "${FILESDIR}/README.voidlinux"
I feel like the readme is pointless if the service follows how every other service is configured.

2024-01-07 01:49 UTC, closed without merging