New package: lsp-plugins-1.2.5
void-linux/void-packages pull request #42512
Opened 2023-02-28 21:16 UTC by subnut

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

2023-02-28 21:39 UTC, subnut commented
Fixes #32991

2023-03-01 13:43 UTC, subnut commented
According to the build logs, the build is failing on musl due to our outdated musl not having the `qsort_r` function, which was introduced in musl 1.2.3

@paper42 What should be done? Should I set `archs="~*-musl"`?

2023-03-01 18:57 UTC, paper42 commented
> According to the build logs, the build is failing on musl due to our outdated musl not having the `qsort_r` function, which was introduced in musl 1.2.3
> 
> @paper42 What should be done? Should I set `archs="~*-musl"`?

definitely no, either you can fix it with a patch or wait for #42425

2023-03-01 19:53 UTC, subnut commented
Okay, I'll wait for #42425

2023-04-12 04:10 UTC, zen0bit requested changes
New version 1.2.6 builded at tested on glibc 64bit...
(used changes of lv2...)

2023-04-12 04:10 UTC, zen0bit commented on srcpkgs/lsp-plugins/template
> +version=1.2.5
version=1.2.6

2023-06-24 13:47 UTC, merged