New package: logiops-0.2.3
void-linux/void-packages pull request #42849
Opened 2023-03-18 21:58 UTC by T0mstone

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

2023-06-25 18:53 UTC, Duncaen commented on srcpkgs/logiops/files/logid.cfg
> +devices: ();
Its easier to simply not ship a configuration file and let the user create it.

2023-06-25 18:56 UTC, Duncaen commented on srcpkgs/logiops/files/logid/run
> +fi
The file should have a trailing newline and probably look like
```
#!/bin/sh
[ -r conf ] && . ./conf
modprobe -q hid_logitech_hidpp || exit 1
exec logid ${OPTS}

2023-06-25 18:57 UTC, Duncaen requested changes
see comments.

2023-06-28 17:23 UTC, T0mstone commented
Thanks for the feedback! Is it fine now? (I'll squash the branch if you want me to – I've kept it as a separate commit for now to keep the PR history)

2023-06-28 17:49 UTC, closed without merging