glibmm2.68: update to 2.76.0.
void-linux/void-packages pull request #43231
Opened 2023-04-03 06:46 UTC by baalajimaestro

#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, glibc, x64

2023-04-11 22:42 UTC, mhmdanas requested changes
Apply this change to `update` to fix update-check:
```diff
diff --git a/srcpkgs/glibmm2.68/update b/srcpkgs/glibmm2.68/update
index c2768fb0e7..8173c5f3ba 100644
--- a/srcpkgs/glibmm2.68/update
+++ b/srcpkgs/glibmm2.68/update
@@ -1,3 +1,3 @@
 pkgname=glibmm
 site=https://gitlab.gnome.org/GNOME/glibmm/-/tags
-pattern="$pkgname-\K[0-9]\.[0-9]*[02468]\.[0-9.]*[0-9](?=)"
+ignore="*.*[13579].*"
```

2023-04-11 22:42 UTC, mhmdanas commented on srcpkgs/glibmm2.68/template
>  homepage="https://www.gtkmm.org"
```suggestion
homepage="https://www.gtkmm.org"
changelog="https://gitlab.gnome.org/GNOME/glibmm/-/raw/master/NEWS"
```

2023-04-14 22:50 UTC, mhmdanas commented on srcpkgs/glibmm2.68/template
>  build_style=meson
```suggestion
build_style=meson
configure_args="-Dbuild-examples=false"
```

2023-05-07 13:49 UTC, Johnnynator commented
495db89f66ce823930983e3666d8f69a7ea742d2

2023-05-07 13:49 UTC, closed without merging