New package: trurl-0.8
void-linux/void-packages pull request #43260
Opened 2023-04-04 15:00 UTC by TinfoilSubmarine

#### Testing the changes
- I tested the changes in this PR: **YES**

2023-04-04 19:09 UTC, icp1994 requested changes

2023-04-04 19:09 UTC, icp1994 commented on srcpkgs/trurl/template
> +build_style=gnu-makefile
```suggestion
build_style=gnu-makefile
make_check_target="test"
```

2023-04-04 19:09 UTC, icp1994 commented on srcpkgs/trurl/template
> +makedepends="libcurl-devel"
```suggestion
makedepends="libcurl-devel"
checkdepends="perl"
```

2023-04-04 21:34 UTC, TinfoilSubmarine commented on srcpkgs/trurl/template
> +makedepends="libcurl-devel"
Thanks!

2023-04-05 05:40 UTC, icp1994 approved these changes

2023-06-23 20:04 UTC, icp1994 commented
Any reason to push v0.6 while the newest tag is v0.8?

2023-06-27 12:26 UTC, merged