urlwatch: update to 2.26
void-linux/void-packages pull request #43398
Opened 2023-04-11 21:10 UTC by RunningDroid

#### Testing the changes
- I tested the changes in this PR: **briefly**

2023-04-11 23:04 UTC, mhmdanas requested changes
The checks worked for me locally without `python3-Pygments` in checkdepends, so remove it from there.

2023-04-11 23:04 UTC, mhmdanas commented on srcpkgs/urlwatch/template
Remove `do_check` below and do this:
```suggestion
# skip the tests that require python modules that aren't packaged
# (pdftotext & pytesseract)
make_check_args="-k not((pdf)or(ocr))"

```

2023-04-12 00:59 UTC, RunningDroid commented
I stumbled across a [regression](https://github.com/thp/urlwatch/issues/755) when I tried to add upstream's dependency docs to my local urlwatch*, so I'd prefer to wait and see what upstream does before merging but I'm not opposed to merging as-is.

*: I have an [alias set up](https://gitlab.com/RunningDroid/minidots/-/blob/master/.zsh/aliases#L29-31) for some sites, I only came across this because I tried to add it to urlwatch without an alias.

2023-04-13 02:10 UTC, RunningDroid commented
I've pulled in upstream's patch for the issue I came across, this is ready to merge whenever anyone has time

2023-04-23 22:24 UTC, merged