libtickit and libvterm update
void-linux/void-packages pull request #43532
Opened 2023-04-19 22:05 UTC by littlewing7

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (ARCH-LIBC)
- I built this PR locally for these architectures:
  - x86_64-musl

2023-04-19 22:14 UTC, mhmdanas commented
Please remove the merge commit; next time, rebase your branch instead.

2023-04-20 10:17 UTC, littlewing7 commented
hi, 

I'm new on this tasks I apologize,  I misunderstood the contributing guide.

I'm not expert in git use so  can you give me more help on how to correctly delete the merge commit or better redo the PR from scratch. 

can you please explain in simple way the correct command sequence for the PR, ex.:
is better to create a new branch for each one of the templates update? 
after I create the new branch locally and tested for example (./xbps-src pkg libtickit successful ),  PR must be requested using GITHUB web interface or there is a way to done this via command line directly from my local git repository?

can you kindly provide me a little list of steps to successfully complete this task? 

Many thanks for your help 

Max

2023-04-20 12:04 UTC, abenson commented
In the future, you can rebase to get rid of the merge commit.

    $ git rebase HEAD~5
    $ git push -f

Secondly, these should be in separate PRs unless there is some kind of dependency/synchronization that expects them to be merged together.

2023-04-20 12:06 UTC, abenson commented
Looks like `libtool` is using the wrong compiler on link.

    libtool: link: gcc -shared  -fPIC -DPIC

2023-04-20 13:51 UTC, littlewing7 commented
this is failing on arm Achitecture, but I only update the version on template, and in my repository xbps-src fail for the same achitecture in the master branch with the actual released libtick_0.4.1. and libvterm_0.3 too. 

Arm cross-compile fail  for both the packages libtickit and libvterm in my branch, but fail with the same error in the master branch. 

What I need to do ? 

many thanks for your help 
Max

2023-04-26 13:59 UTC, littlewing7 commented
As you can see I'm able to successful build other packages in my environment for arm arch: 

![image](https://user-images.githubusercontent.com/24845072/234599244-64f37545-b1a5-469a-8172-4456cb98330f.png)


Can you please confirm me that the 2 submitted packages build fail for ARM architecture in the original master branch ? 

I perform a list of test and other packages build correctly in my cloned  master branch using arm7 or aarch64, but still fail for libtickit and libvterm. 

have someone the same problem? How I can solve? 

many thanks 
Max

2023-04-26 15:26 UTC, abenson commented
You'll need to fix cross-compilation for the template.

2023-04-26 20:23 UTC, mhmdanas requested changes

2023-04-26 20:23 UTC, mhmdanas commented on srcpkgs/libtickit/template
>  make_build_args="LIBTOOL=${XBPS_CROSS_BASE}/usr/bin/libtool"
Removing `make_build_args` and `make_install_args`, and applying my other suggestion below, fixed cross-compilation locally for me.

2023-04-26 20:23 UTC, mhmdanas commented on srcpkgs/libtickit/template
> +checksum=a830588fa1f4c99d548c11e6df50281c23dfa01f75e2ab95151f02715db6bd63
```suggestion
checksum=a830588fa1f4c99d548c11e6df50281c23dfa01f75e2ab95151f02715db6bd63

export LIBTOOL="${XBPS_CROSS_BASE}/usr/bin/libtool"
```

2023-04-26 20:23 UTC, mhmdanas commented on srcpkgs/libtickit/template
>  distfiles="http://www.leonerd.org.uk/code/libtickit/libtickit-${version}.tar.gz"
```suggestion
homepage="https://www.leonerd.org.uk/code/libtickit/"
distfiles="https://www.leonerd.org.uk/code/libtickit/libtickit-${version}.tar.gz"
```

2023-04-26 22:03 UTC, littlewing7 commented
Ok, i try. But cross compilation doesn’t work on original master for both
this packages using the original master branch template, how is this
possible ?

Il giorno mer 26 apr 2023 alle 17:27 Andrew Benson ***@***.***>
ha scritto:

> You'll need to fix cross-compilation for the template.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/void-linux/void-packages/pull/43532#issuecomment-1523615360>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF5RWEHVPP367Q2JCOUKGJ3XDE5ETANCNFSM6AAAAAAXEVEX3Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-27 11:36 UTC, abenson commented
It means it was broken then, too, and still needs to get fixed.

2023-04-27 11:39 UTC, littlewing7 commented
I modified the template as suggested: 

![image](https://user-images.githubusercontent.com/24845072/234850116-9883bc1a-d8d3-40ff-a857-45275ecdbf09.png)

but build fail again in my branch: 

![image](https://user-images.githubusercontent.com/24845072/234850379-31832d24-2e06-4006-9552-c798b70db8df.png)


what I don't understand is how is possible that the original packages successful build on CI (it is released) but fail  locally. 

can you point me how: 

> You'll need to fix cross-compilation for the template.

if this fail on the original packages? 

many thanks. 

Max

2023-04-27 20:32 UTC, mhmdanas commented
> but build fail again in my branch:

That's weird, did you run `./xbps-src clean` before running `./xbps-src pkg libtickit`?

> what I don't understand is how is possible that the original packages successful build on CI (it is released) but fail locally.

Changes to other packages may have caused the breakage, it's not exactly unusual.

2023-04-28 07:09 UTC, littlewing7 commented
HI guys, 

./xbps-src clean doesn't resolve the issue. 

At this point I suspects a different problem, relative to the Makefile/template of libtickit tar.gz  who became incompatible with the newest versions of libtool/workflow used for building packages. 
This because if you aren't able to build the actual released version of libtickit-0.4.1 who is published in the official repository, then something externally to the package libtickit-0.4.1.tar.gz was changed between the time of successful build and now. 

I'm able to build successfully the package libvterm-0.3.1.tar.gz (created from the same author  )

![image](https://user-images.githubusercontent.com/24845072/235076496-8f4fdc17-ccd5-4bc8-aef1-479eb224f733.png)

I suspect something a little bit different for the libtickit-04.3.tar.gz, for the above reasons, because i try to add the post_extract command to the template of libtickit as the one on libvterm: 

![image](https://user-images.githubusercontent.com/24845072/235077088-8644b6bc-1b1b-4c98-b400-171fda948d17.png)

but the build continue to fail with this error: 

![image](https://user-images.githubusercontent.com/24845072/235077359-4a33b3ec-3740-4c14-ac05-06c9400c2c3b.png)
![image](https://user-images.githubusercontent.com/24845072/235077436-4547a602-6868-42b7-b6c6-808a1667026c.png)

` /usr/arm-linux-gnueabihf/usr/bin/libtool --quiet --mode=compile --tag=CC arm-linux-gnueabihf-gcc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard   -I/usr/arm-linux-gnueabihf/usr/include -ffile-prefix-map=/builddir/libtickit-0.4.3=. -Wall -Iinclude -Isrc -std=c99  -DHAVE_UNIBILIUM  -o src/window.lo -c src/window.c

/usr/arm-linux-gnueabihf/usr/bin/libtool --quiet --mode=link --tag=CC arm-linux-gnueabihf-gcc -rpath /usr/lib -version-info 3:0:0 -o libtickit.la src/bindings.lo src/debug.lo src/evloop-default.lo src/mockterm.lo src/pen.lo src/rect.lo src/rectset.lo src/renderbuffer.lo src/string.lo src/term.lo src/termdriver-ti.lo src/termdriver-xterm.lo src/tickit.lo src/utf8.lo src/window.lo -Wl,-z,relro -Wl,-z,now -Wl,--as-needed    -L/usr/arm-linux-gnueabihf/usr/lib -lunibilium -ltermkey

/usr/bin/ld: src/.libs/bindings.o: relocations in generic ELF (EM: 40)

/usr/bin/ld: src/.libs/bindings.o: error adding symbols: file in wrong format

collect2: error: ld returned 1 exit status

make: *** [Makefile:62: libtickit.la] Error 1

=> ERROR: libtickit-0.4.3_1: do_build: '${make_cmd} CC="$CC" CXX="$CXX" LD="$LD" AR="$AR" RANLIB="$RANLIB" CPP="$CPP" AS="$AS" OBJCOPY="$OBJCOPY" OBJDUMP="$OBJDUMP" CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" PREFIX=/usr prefix=/usr ${makejobs} ${make_build_
args} ${make_build_target}' exited with 2

=> ERROR:   in do_build() at common/build-style/gnu-makefile.sh:9
`

many thanks for the patience and help. 

Max

2023-05-03 17:27 UTC, closed without merging