ffmpeg6 split
void-linux/void-packages pull request #43761
Opened 2023-05-05 13:20 UTC by zlice

[ci skip]

#### Testing the changes

- I tested the changes in this PR: **YES**

main testing has been vaapi in Firefox Nightly and enc/dec in Shotcut on Intel A770

#### New package

- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing

- I built this PR locally for my native architecture, **x86_64**

#### Discussion

Continuation of https://github.com/void-linux/void-packages/pull/36315

`libavresample` is deprecated, but marked as a dependency when trying to build other packages and install `ffmpeg`(5). I think the right way to handle this is make a meta package and the add to removals?

##### Commit naming / misc

Commits are 'dirty' right now, running with [gstreamer 1.22.1 updates](https://github.com/void-linux/void-packages/pull/42861) and [Intel OpenCL](https://github.com/void-linux/void-packages/pull/43084). This will also make [intel packages pr](https://github.com/void-linux/void-packages/pull/41132) obsolete.

Maintainer for previous ffmpeg(4) was orphaned, I can put my name in there if that matters, though I don't exactly see myself keeping up on ffmpeg.

This updates QT5 which looks like it is usually hosted by Johnny. Not sure if there's any reason to stay there or these sources are fine.

##### STILL FFMPEG4

These are a mix of emulators, games and/or older packages.

- attract (multiple patches in master)
- audacity  (3.2.x should work but void is missing some libs? vst3sdk?)
- ccextractor (master patches? no release)
- vice
- kodi
- mlt
- synfig (mlt)
- tvheadend
- ssr
- spek-alternative
- ppsspp
- olive
- moc
- mediastreamer
- libextractor
- idjc
- hedgewars
- ffmpegthumbnailer
- ffmpegthumbs
- deadbeef
- omxplayer
- qtav (fork has ffmpeg 5 patch - https://github.com/cmguo/QtAV)
- `vlc` (vlc4 will support ffmpeg5, there's a patch to build 3.x with ffmpeg5 but it will lack vaapi)
- `osg` (OpenSceneGraph plus `xine-lib`)
- `ytmdl` ? not sure but it uses `python3-ffmpeg-python` which being 6-8yr old I imagine is ffmpeg4

##### HAVE NOT BUILT YET

- omxplayer (rpi only?)
- kodi (big, but ffmpeg4)

##### UPDATED (for ffmpeg5)

- unpaper: update to 7.0.0.
- guvcview: update to 2.0.8.
- qt5: update to 5.15.8
- qt5-webengine: update to 5.18.13
- shiboken2: revbump for qt5.15.8 (patch)
- python3-pyside2: update to 5.15.8 (patch)

2023-05-07 19:26 UTC, paper42 commented
are the commits for a blender update, gstreamer and new intel packages really necessary for this PR? If not, please drop them. If yes and they could be merged before merging this PR, please split them to a separate PR and mention that it should be merged before this PR in this PR's description.

2023-05-07 22:00 UTC, zlice commented
**Intel OpenCL** commits removed

**blender** - uses ffmpeg-devel, added to update list

**gstreamer** - added to 'Requirements' section and only revbumped the appropriate packages

**Intel Packages** - added to 'Requirements'

2023-07-09 14:58 UTC, zlice commented
ICU updated, and many other things since my last full build test. building fine for now

2023-10-02 00:04 UTC, yoshiyoshyosh commented
we can replace `spek-alternative` with [`spek-x`](https://github.com/MikeWang000000/spek-X ), a more actively maintained fork that supports ffmpeg6. [the original `spek`](https://github.com/alexkay/spek) has also become maintained again, but it claims to only support up to ffmpeg 5.1.

2023-10-11 12:27 UTC, zlice commented
Blocked by https://github.com/void-linux/void-packages/pull/46172

Already quite a few updates to sift through and I don't feel comfortable trying until I know I can update mesa.

2023-10-11 17:06 UTC, SpidFightFR commented
> Blocked by #46172
> 
> Already quite a few updates to sift through and I don't feel comfortable trying until I know I can update mesa.

Sup, 23.1.8 should build, but it doesn't work because 32-bit subpackage problem. i still don't know how to solve this issue.

2023-10-16 12:12 UTC, zlice commented
Got 64/32bit x86 building again. tyvm spid

2023-10-16 12:19 UTC, SpidFightFR commented
> Got 64/32bit x86 building again. tyvm spid

it's not ready yet, i believe there is an issue with arm and aarch64 archs.
Mesa still can't be updated atm.

2023-10-16 12:19 UTC, SpidFightFR commented
see here: https://github.com/void-linux/void-packages/issues/46674

2023-10-17 12:59 UTC, zlice commented
> we can replace `spek-alternative` with [`spek-x`](https://github.com/MikeWang000000/spek-X), a more actively maintained fork that supports ffmpeg6. [the original `spek`](https://github.com/alexkay/spek) has also become maintained again, but it claims to only support up to ffmpeg 5.1.

added to here, separate PR was building off ffmpeg4 and looked like everything was bombing out.

not sure if i did the transitional dummy package to replace spek-alternative with spek-x right

2023-12-03 16:39 UTC, mhmdanas commented
I'd like to help move this along, is there anything I can do?

2023-12-05 16:30 UTC, mhmdanas commented
Thanks for all the info, when I get a bit more time (hopefully in a couple weeks), I'll sift through the items you mentioned. :)

2023-12-09 17:39 UTC, zlice commented
Using QT 5.15.11 that was just updated. Revbump for qt5 and some hacky patch to build qt5-webengine by forcing `-system-ffmpeg` and knocking out the test was complaining. If that should be fixed properly lmk.

2023-12-29 17:30 UTC, zlice commented
https://github.com/void-linux/void-packages/pull/46013

2024-02-02 22:46 UTC, zlice commented
updated comments for ffmpeg4 packages. flowblade seems to work for me and should allow for removal of mlt and can use mlt7.

vice, libextractor and idjc i wouldn't know how to test. mediastreamer is linphone based so i didn't check beyond seeing a new version (complained about optr cmake files?)

2024-02-03 20:38 UTC, zlice commented
I'm about to make all revisions 99 until this is about to merge x-x

2024-02-06 05:34 UTC, Luciogi commented
add flowblade PR link: https://github.com/void-linux/void-packages/pull/47195

2024-02-22 17:25 UTC, yoshiyoshyosh commented
heya, I have enough time that I'd like to help move this along. has much changed in terms of what needs to be done since your last comment about what needs to be done?

2024-02-22 17:34 UTC, zlice commented
i don't think much more can be done besides `vice, libextractor and idjc` being tested real quick. `tvheadend` update should hit at some point. nvidia headers could be merged. `mlt (flowblade)` can happen after. new `gonic` package can use ffmpeg6.

really just need to clean up commits and double check things.

as for testing, even slackware has ffmpeg 6.1, so i'm sure package compatibility fine at least for glibc.

2024-02-24 02:34 UTC, yoshiyoshyosh commented
vice and idjc work well (well, idjc spews a bunch of syntax parsing warnings but that's python stuff rather than ffmpeg stuff). libextractor's throwing an error with exiv2 and I'm not sure if that's affecting the ffmpeg part or not

2024-02-25 17:33 UTC, zlice commented
> vice and idjc work well

@yoshiyoshyosh would you mind making PRs to update vice/idjc version since you tested them? then i'll bump them in here

2024-02-25 19:08 UTC, yoshiyoshyosh commented
> @yoshiyoshyosh would you mind making PRs to update vice/idjc version since you tested them? then i'll bump them in here

@zlice sounds good. also, I figured out something with libextractor: it doesn't need ffmpeg anymore with the latest versions. can also make a pr to

2024-02-25 19:28 UTC, zlice commented
must be why it built lol. odd, they removed it and didn't replace it with anything so opus and thumbnails are gone? only thing that uses it is `gnunet`. thanks

2024-02-25 19:32 UTC, yoshiyoshyosh commented
> so opus and thumbnails are gone?
yup. I think it's just a symptom of being really old and half-abandoned by now haha

2024-02-25 21:44 UTC, yoshiyoshyosh commented
also, it seems like the latest idjc versions can build and run with ffmpeg6 perfectly fine.

2024-03-09 22:24 UTC, yoshiyoshyosh commented
idk if you did tests for spek-x when building it but they seem to fail for me without this patch:
```diff
--- a/tests/perf.cc	2024-03-09 17:13:49.086603418 -0500
+++ b/tests/perf.cc	2024-03-09 17:13:59.453603753 -0500
@@ -1,3 +1,4 @@
+#include <cstdint>
 #include <cstdlib>
 #include <iostream>
 #include <fstream>
```

2024-03-09 22:43 UTC, zlice commented
> idk if you did tests for spek-x when building it but they seem to fail for me without this patch:

haven't done full builds for musl yet. when your PRs get merged i'll probably start bugging people. coming up on a year now and my updates just needed another kick. probably doing a full reinstall once this merges.

2024-03-09 22:56 UTC, yoshiyoshyosh commented
> haven't done full builds for musl yet

that's odd, it was failing while I was testing on glibc O.o, wonder if there's some differing strict compiler flags present somewhere. whatever, so long as it works

2024-03-10 00:03 UTC, zlice commented
usually when i have to include stdint it's a musl thing. ya builds fine for me on glibc. don't know of anything fancy i do

2024-05-17 13:38 UTC, Luciogi commented
@zlice flowblade old PR got messed up, here is new PR https://github.com/void-linux/void-packages/pull/50385

2024-05-17 13:40 UTC, zlice commented
> @zlice flowblade old PR got messed up, here is new PR #50385

Awesome. Dang looks like builds aren't going for it D=

2024-05-29 22:19 UTC, zlice commented
Made mlt7 SDL2. Their git is tagged to sdl2 though build searches for either. Suppose 1 would have less revbumps but it seems benign.

2024-06-21 18:12 UTC, ahesford requested changes
This is a massive and far-reaching PR. I think we should scale it back:
1. Keep `ffmpeg` at its current version (4.4.4). This lets us drop all revbumps that would need to be rebuilt for a new `ffmpeg4`. That's about 20% of the templates you've touched.
2. Make a new package, `ffmpeg6` and any of the new additions necessary to support it.
3. Delete the `freecad` commit, it doesn't seem to belong.
4. The current `ffmpeg` dependants that can be easily migrated to the new `ffmpeg6` can be included in this PR, but let's defer some of the large rebuilds until later. For example:
    - electron19
    - electron24
    - qt6-pdf (this might include qt6-multimedia)
    - qt5-webengine (this might include qt5 and qt5-speech)
 
I'm not sure if there are other interactions between qt stuff that might depend on the old `ffmpeg` and dependants that might move to the new `ffmpeg6`, but those whole branches can remain on the old `ffmpeg` for now. As we update the electron and qt packages, we can move them to `ffmpeg6` and eventually sunset `ffmpeg`.

2024-06-21 18:12 UTC, ahesford commented on srcpkgs/spek-x/template
> +checksum="7f4b109903333cdd310ab2b9176f0dc49a565891376e281a233d342cedf90ef7"
This should include a `replaces="spek-alternatives<=0.8.2.3_2"` line to make sure upgrades are properly handled.

2024-06-23 16:07 UTC, zlice commented
> This is a massive and far-reaching PR. I think we should scale it back:

Updating this or making another PR with a ffmpeg6 package should be easy enough, but I can't really test ffmpeg(4)+ffmpeg6 without a reinstall. Hope to make a new PC when ryzen 9000 drops. From what I remember talking with paper a while back I recall there was something that made switching that way (ffmpeg+ffmpeg6) a no-go or harder to do. Would you make 4 depend on 6 and use the binaries for ffmpeg/ffprobe/etc from ffmpeg6 ? Would that mess with dependencies or keeping a plain 'ffmpeg' package?

It looks closer to 10% ffmpeg4 to me, lower when flowblade and idjc are updated and mlt can be removed. Should just be old or dead packages left.

**probably 4 'forever'**

- vlc 4.x release (not ffmpeg4) is ultra slow
- olive should be axed i think
- qtox git is archived
- moc is old and probably dead
- kodi hasn't been touched in 10 years, not sure it compiles at all

**6 compatible**

- tvheadend release is slow
- qtav has another fork
- mediastreamer/linphone stuff i wanted to stay away from but probably possible
- deadbeef needs some newer packages for update, doable same as linphone
- hedgewars + ffmpeg6 built fine with https://github.com/hedgewars/hw/pull/74

What helps/hurts doing the big qt/gtk/electron stuff upfront vs after other packages that use ffmpeg6? Either way seems like no one will be able to update cleanly for a good while. More of a pain for the build process? Or do you see the ffmpeg PR being picked at and slowly added?

Should be able to get on irc this week if that's easier to talk over. Recovering from massive jetlag.

2024-06-29 11:24 UTC, zlice commented
Made ffmpeg ffmpeg4 and ffmpeg6 a new package. Haven't built yet, don't know when I can test.

shiboken/pyside are semi unrelated now that qt and webkit stuff are dropped. Can make a new PR for that if it matters.

2024-06-29 15:16 UTC, zlice commented
obs needed `qt6-base-private-devel` ? not sure what that is in 6.7.2

audacity update pending https://github.com/void-linux/void-packages/pull/50047 (either works, have patch for annoying scrollbar bug)

everything else built fine

idjc and flowblade updates can move those to 6

still need to test install and en/decoding

2024-07-04 16:17 UTC, chrysos349 commented
hey, great job here! do you plan to update ffmpeg to 7.0.1?

2024-07-04 16:36 UTC, classabbyamp commented
it would make more sense to leave the ffmpeg 4 binaries as-is for now, and add the ffmpeg 6 binaries as <binname>6 to avoid conflicts. once most things support ffmpeg 6 and ffmpeg = 6.x, then we can change the default binary names

2024-07-05 18:00 UTC, zlice commented
> it would make more sense to leave the ffmpeg 4 binaries as-is for now, and add the ffmpeg 6 binaries as 6 to avoid conflicts. once most things support ffmpeg 6 and ffmpeg = 6.x, then we can change the default binary names

i don't see why anyone would want the ffmpeg6 libraries but ffmpeg4 binaries. you won't be able to use new codecs on command line. can you overwrite the binaries for 4 with 6? that was part of the original PR having 6 as the main `ffmpeg` package.

only 4 packages can't move past ffmpeg4 : vlc, mediastreamer(linphone), olive, moc

vlc and mediastreamer may eventually update but olive is probably a lost cause and moc hasn't been touched since 2016 or something. i think it makes more sense to update everything else, maybe poke tvheadend where the 'q1' 4.4 release is or use the recommended 'dev' version - and leave vlc/mediastreamer on 4 as a library only. everything will just end up being build more otherwise won't it?

- updated digikam/qtav - qtav was absorbed and patched in digikam 8.0.0
- updated deadbeef finally

tested both on my old branch with 6 as main...looks like qt5-webengine broke over the last month or so on some chromium re2 StringPiece class

2024-07-05 18:07 UTC, classabbyamp commented
my comment got messed up by markdown, it should say `<binname>6` not just 6

2024-07-05 18:50 UTC, ahesford commented
Do any of the remaining v4 dependents actually require command-line tools? If not, I think making the original `ffmpeg` a library-only package is fine and we can let `ffmpeg6` be the only provider of command-line tools (and without versions in the executable names). But if VLC *et al.* require command-line tools, we probably need to take advice from @classabbyamp and let the new package provide tools with `6` at the end of their names.

2024-07-05 22:03 UTC, zlice commented
> But if VLC _et al._ require command-line tools, we probably need to take advice from @ classabbyamp and let the new package provide tools with `6` at the end of their names.

afaik they don't. didn't look at olive code but the others look like code and no scripts calling anything

did get kodi 21 going, but xbps complains that it makes a `/kodi` instead of putting some python scripts for ps3 remote in `/opt` or somewhere else. not sure how to handle that short of moving them under `/usr/share`

2024-07-05 22:47 UTC, classabbyamp commented
would it be possible to split this into smaller PRs, e.g.:
1. new package: ffmpeg6
2. opencv update
3. smaller batches of ffmpeg 4->6 migrations
4. big packages like chromium or webengine on their own (or held off until there's an update for them)

as it stands, it's very hard to review because of the size

2024-07-05 23:10 UTC, zlice commented
it is, ffmpeg touches everything.

i can split more PRs, but some rebuilds will dupe ffmpeg revdeps

if you have any ideas for priority on waves of packages to make things smoother lmk

**updates**

- guvcview: update to 2.0. (dupe revbump for ffmpeg6)
- handbrake: update to 1.6. (dupe revbump)
- opencv: update to 4.7. (retroshare dupe revbump)
- unpaper: update to 7.0. (dupe revbump)
- deadbeef: update to 1.9. (libdispatch, dupe revbump)
- libwaylandpp: update to 1.0 / kodi: update to 21.0 (kodi dupe revbump)
- spek relacement (dupe revbump)
- audacity: update to 3.5. (another PR has this)
- idjc (another PR)
- flowblade (another PR)

**big packages**

- gtk4
- qt5
- qt5-webengine
- qt6-pdf (webengine)
- qt6-multimedia
- konqeror
- chromium
- electron19
- electron24

**misc**

- qtav/digikam (should be no extra work as a separate PR)

2024-07-06 13:31 UTC, zlice commented
https://github.com/void-linux/void-packages/pull/51123

https://github.com/void-linux/void-packages/pull/51124

only half of opencv passed ci for some reason, seems fine locally for me

2024-07-06 20:07 UTC, zlice commented
https://github.com/void-linux/void-packages/pull/51132

still probably going to use this branch/pr for tracking

2024-07-19 20:32 UTC, Pestdoktor commented
Just wanted to report in that I haven't had an issue running ffmpeg and dependencies off this branch (as pulled at the end of march). Great work!

2024-07-21 23:20 UTC, zlice commented
will do, probably later tonight. ill probably sort by stuff i use reguarly that has been working fine with 6, version update packages separately(?), then by w/e groups that make sense. hold on the big electron/gtk/qt stuff like you said and wait for those to update and switch ffmpeg.

2024-07-21 23:29 UTC, classabbyamp commented
sounds good to me, no rush too

2024-07-28 23:02 UTC, classabbyamp commented
by my reckoning, this is all that's left in this PR:

- _New package: vpl-gpu-rt-24.2.5_ - #51133 
- _python3-pyside2: revbump for qt5-5.15.11_ and _shiboken2: revbump for qt5-5.15.11_ - should be their own PR, not sure why they're in here
- _audacity: update to 3.5.1_ - #50047 or #51407

Thus, this can be closed now.

other packages I see in the repos still on ffmpeg4:
- electron19
- electron24
- qt5
- qt5-webengine
- qt6-pdf
- qt6-multimedia
- vlc
- qtox
- moc
- mpv-mpris
- tvheadend
- opencv
- olive
- mediastreamer

2024-07-28 23:02 UTC, closed without merging

2024-07-29 01:35 UTC, zlice commented
sounds right

pyside/shiboken was due to the original having ffmpeg6 as main and rebuilding qt i think. will take another look at those and make a pr if theyre still not compiling currently.

tvheadend still no 4.4 release, the 4.3 'dev' works. electron and qt should be the only things left then. others are on ffmpeg4 until question-marks

thanks for all the assistance abby

2024-07-29 03:39 UTC, classabbyamp commented
made a tracking issue: #51522 

can you make a PR for the qt5-related patches?