Updating ZMusic to 1.1.12
void-linux/void-packages pull request #43958
Opened 2023-05-20 11:05 UTC by SpidFightFR

Little update for the zmusic package that might be required for gzdoom.

#### Testing the changes
- I tested the changes in this PR: **briefly (i tested on x64)**

2023-06-09 07:13 UTC, classabbyamp commented on srcpkgs/ZMusic/template
>  distfiles="${homepage}/archive/${version}.tar.gz"
```suggestion
distfiles="https://github.com/coelckers/ZMusic/archive/${version}.tar.gz"
```

2023-06-14 17:28 UTC, Duncaen commented
The commits need to be squashed and follow the standard format, like the first commit.

2023-06-18 09:28 UTC, SpidFightFR commented
> The commits need to be squashed and follow the standard format, like the first commit.

Agreed, and done. ^^

2023-06-18 09:33 UTC, classabbyamp commented on srcpkgs/ZMusic/template
>  distfiles="${homepage}/archive/${version}.tar.gz"
This was lost

2023-06-25 17:14 UTC, Duncaen requested changes
Remove `${homepage}` from `distfiles`.

2023-06-25 21:08 UTC, classabbyamp commented
squash please

2023-06-26 16:33 UTC, merged