mesa: update to 23.1.1. (+ required consul update)
void-linux/void-packages pull request #44108
Opened 2023-05-26 21:56 UTC by SpidFightFR

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Thanks to Aedinius on the [IRC](https://web.libera.chat/#voidlinux) for helping with this PR !

2023-05-27 01:43 UTC, classabbyamp requested changes
the consul changes should not be there, it's reversing a change that was made even.

use `git pull --rebase` to update your branch in the future

2023-05-27 08:52 UTC, SpidFightFR commented
@classabbyamp i get an error wit the updated commit of consul:

```
=> ERROR: mesa-23.1.1_1: do-patch_00-patches: 'patch -s ${_args} < "${_patch}" 2> /dev/null' exited with 1
=> ERROR:   in _process_patch() at common/hooks/do-patch/00-patches.sh:34
=> ERROR:   in hook() at common/hooks/do-patch/00-patches.sh:51
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:262
=> ERROR:   in run_step() at common/xbps-src/shutils/common.sh:71
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-dopatch.sh:33
```

2023-05-27 08:58 UTC, classabbyamp commented
You probably need to `./xbps-src clean`

2023-05-27 09:07 UTC, SpidFightFR commented
Yep, it works, i'm gonna let it build nicely, once that's done, gonna check if there are any mistakes in the template and update the PR. See ya then, and thanks for your help !

2023-05-27 09:46 UTC, SpidFightFR commented
Okay so this update of my branch says "3 files changed", probably because i firstly changed consul, but in reality i pulled the latest commits from the void repos and added back my changes with mesa. It should be okay, but please keep me in touch.

2023-05-27 13:54 UTC, abenson commented
Something went wrong with your commit... It shows the wrong author.

2023-05-27 15:20 UTC, SpidFightFR commented
> Something went wrong with your commit... It shows the wrong author.
> 
> Follow @classabbyamp's recommendation, run `git pull --rebase` and then `git commit --amend --reset-author`.

okay i ran both of the commands, i hope this time it will be good !

2023-05-29 16:24 UTC, classabbyamp commented
There are still changes to the consul template included here that shouldn't be

2023-05-29 17:51 UTC, closed without merging