moosefs: update to 3.0.117
void-linux/void-packages pull request #44384
Opened 2023-06-12 12:08 UTC by toomyem

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-glibc)

2023-06-12 12:15 UTC, toomyem commented
Sorry. I've made PR from master branch of my fork by mistake. The only way to correct this was to create new PR. It won't happen again.

2023-06-12 12:17 UTC, mhmdanas commented
No worries. :)

2023-06-12 12:20 UTC, mhmdanas requested changes

2023-06-12 12:20 UTC, mhmdanas commented on srcpkgs/moosefs/template
>  revision=2
Revision should be reset to 1 when bumping version.

2023-06-12 12:20 UTC, mhmdanas commented on srcpkgs/moosefs/template
>  distfiles="http://ppa.moosefs.com/src/moosefs-${version}-1.tar.gz"
Those URLs should work with HTTPS too.

2023-06-12 12:20 UTC, mhmdanas commented on srcpkgs/moosefs/template
>  python_version=2 #unverified
Upstream apparently supports Python 3 too, can you try that?

2023-06-13 15:54 UTC, classabbyamp commented on srcpkgs/moosefs/template
> +homepage="https://moosefs.org/"
```suggestion
homepage="https://moosefs.com/"
```

2023-06-13 23:28 UTC, merged