i3status-rust: update to 0.31.8.
void-linux/void-packages pull request #44899
Opened 2023-07-07 07:56 UTC by pablomancera

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

2023-07-08 14:56 UTC, Bnyro commented
(supersedes #44067)

2023-07-09 00:35 UTC, pablomancera commented
Compiling with and without the notmuch option did not make any changes to the generated manpage, and building the manpage seemed to be difficult for cross compiling and local compiling at least on an aarch64 device (due some issues compiling the pandoc dependency). So I think it's best to bundle the generated manpage as a file and install it with the template.

With this change the generated package worked on a Raspberry Pi 4, both cross compiling from my PC and compiling locally.

2023-07-26 07:55 UTC, classabbyamp requested changes

2023-07-26 07:55 UTC, classabbyamp commented on srcpkgs/i3status-rust/files/i3status-rs.1
no we are not going to vendor a 7.5k line man page from upstream

2023-07-26 08:16 UTC, kartikynwa commented on srcpkgs/i3status-rust/files/i3status-rs.1
For conditionally generating man pages you can look at this for reference: https://github.com/void-linux/void-packages/pull/44917/files

2023-09-16 05:31 UTC, pablomancera commented
Superseded by #46079

2023-09-16 05:31 UTC, closed without merging