ci: add step to verify the functionality of update-check
void-linux/void-packages pull request #44927
Opened 2023-07-08 19:07 UTC by classabbyamp

runs update-check on all changed templates, then errors only if there was an issue with the update-check. does not error if further updates are available, as there may be a good reason not to update to those versions

#### Testing the changes
- I tested the changes in this PR: **YES**

2023-07-08 19:22 UTC, Chocimier commented
Not against, but if package got updated, it means somebody tracks updates.

It may be more fruitful to report `NO VERSION found for` in void-updates.

2023-07-08 19:56 UTC, classabbyamp commented
If we report `NO VERSION found` here while a package is being updated, then it can be fixed (or, as of now, disabled) while the package is being updated.

`NO VERSION found` is also reported in https://repo-default.voidlinux.org/void-updates/void-updates/_log.txt already but that's kinda hidden.

also, this could let reviewers check if there are further updates available

2023-07-08 20:52 UTC, Chocimier commented
I didn't knew about _log.txt, thanks.

Shouldn't this go into lint job rather than x86_64 build?

Ack overall for checking new packages.

2023-07-08 21:04 UTC, classabbyamp commented
> Shouldn't this go into lint job rather than x86_64 build?

this is out of convenience, because the lint job does not run in a void container but instead on the ubuntu host. I've attempted to bring it over to a void container like the build CI but xlint was doing something weird with the escaping of backreferences in a sed. it works as-is but in void it does not resolve the backreference properly (see [here](https://github.com/void-linux/void-packages/actions/runs/5029165174/jobs/9020547621?pr=43949#step:7:22))

2023-07-08 21:09 UTC, mhmdanas requested changes

2023-07-08 21:09 UTC, mhmdanas commented on .github/workflows/build.yaml
> +      - run: common/travis/xlint.sh || exit 0
```suggestion
      - run: common/travis/xlint.sh || exit
```

2023-09-06 01:00 UTC, classabbyamp commented
ok this now runs the update-check lint in the lint job, now that xlint can run with bash as sh (thanks btw!)

example here: https://github.com/void-linux/void-packages/actions/runs/6091407376/job/16527947208?pr=44927

2023-09-07 17:04 UTC, Chocimier approved these changes

2023-09-08 08:33 UTC, merged