add power-profiles-daemon startup dependency
void-linux/void-packages pull request #45660
Opened 2023-08-18 16:47 UTC by Luciogi

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-Glibc)

2023-08-18 17:53 UTC, Luciogi commented
should I bump version or wait for maintainer?

2023-08-18 18:20 UTC, ahesford requested changes
The revision needs to be bumped, or this package won't be rebuilt.

2023-08-19 01:21 UTC, Luciogi commented
@ahesford done

2023-08-19 01:23 UTC, ahesford commented on srcpkgs/power-profiles-daemon/files/power-profiles-daemon/run
> +sv start dbus >/dev/null || exit 1
This is supposed to be `sv check`, not `sv start`.

2023-08-19 03:13 UTC, Luciogi commented
ah sorry.
Now Fixed
@ahesford

2023-08-20 14:32 UTC, merged