opencl2-header rename to opencl-header, also update dependent packages
void-linux/void-packages pull request #45686
Opened 2023-08-20 15:38 UTC by aryalaadi

Renaming opencl2-header to opencl-header because its misleading since this ships headers for OpenCL 3.0 specs as well. Unless the 2 in opencl2-header is supposed to signify something else, its better to rename it. Also updated every dependent packages.
#### Testing the changes
- I tested the changes in this PR: **YES**

2023-08-28 20:02 UTC, ahesford commented on srcpkgs/opencl-headers/template
> +pkgname=opencl-headers
This should be `OpenCL-Headers` if we're going to rename the package, and there should be a meta-package called `opencl2-headers` that pulls this in for backwards compatibility.

2023-08-30 07:41 UTC, aryalaadi commented on srcpkgs/opencl2-headers/template
@ahesford is this what a metapackage is? im not sure

2023-08-30 11:30 UTC, ahesford requested changes
The transitional metapackage should be a subpackage of the one that replaces it. See, for example, the `stow` template, which was renamed from `perl-stow`.

Also, don't strip my name from the maintainer field.

2023-09-01 19:41 UTC, aryalaadi commented
looks good now? also i assumed this package was abandoned or smth my bad

2023-09-01 20:04 UTC, ahesford requested changes
You'll need to make a symlink from `srcpkgs/opencl2-headers` to `OpenCL-Headers` so that the transitional metapackage is built.

2023-09-01 20:04 UTC, ahesford commented on srcpkgs/OpenCL-Headers/template
> +replaces="OpenCL-Headers>=0"
```suggestion
provides="opencl-headers-${version}_${revision}"
replaces="opencl-headers>=0"
```
These lines replace an old, removed `opencl-headers` package, so they need to be carried forward from the `opencl2-headers` template verbatim.

2023-09-01 21:05 UTC, closed without merging

2023-09-01 21:07 UTC, ahesford commented
Thanks. I cleaned up the commits and split the dependant changes, including revbumping `ocl-icd` so that the dependency change to `ocl-icd-devel` is reflected in the package.