python3-aiohttp_socks: update to 0.8.3 and add required dependencies
void-linux/void-packages pull request #46383
Opened 2023-10-02 13:48 UTC by ar-jan

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

I accidentally had to add and update multiple packages in order to python3-aiohttp_socks:

- New package: python3-tiny-proxy-0.2.0: needed for python3-aiohttp_socks tests
- New package: python3-httpx-socks-0.7.8: needed for python3-tiny-proxy tests
- New package: python3-aiosignal-1.3.1: needed for python3-tiny-proxy tests, and python3-aiohttp v3.8
- New package: python3-frozenlist-1.4.0: needed for python3-aiosignal
- New package: python3-proxy.py-2.4.3: needed for python3-aiohttp tests
- New package: python3-re_assert-1.1.0: needed for python3-aiohttp tests
- python3-aiohttp: update to 3.8.5: needed for passing python3-aiohttp_socks tests
- python3-async-timeout: update to 4.0.3: needed for python3-aiohttp v3.8

@the-maldridge would you care to take a look at this since you maintain python3-aiohttp and python3-async-timeout?

2023-10-02 14:17 UTC, ar-jan commented
Hmm, all tests pass locally. Some missing dependency for CI?

2023-10-14 15:30 UTC, ahesford commented
I suggest dropping all of the new packages added just to support checks. If those checks requiring these packages can be skipped, great; otherwise, just skip all of the checks.

2023-10-16 22:18 UTC, ar-jan commented
OK, I've removed these new dependencies:

> New package: python3-httpx-socks-0.7.8
> New package: python3-tiny-proxy-0.2.0
> New package: python3-re_assert-1.1.0
> New package: python3-proxy.py-2.4.3

But python3-aiosignal is required for python3-aiohttp, and depends on python3-frozenlist (not just for tests). Previously tests were passing, now I get this for python3-aiosignal:

```
$ ./xbps-src pkg -Q python3-aiosignal
...
=> python3-aiosignal-1.3.1_1: building with [python3-module] [python3] for x86_64...
...
[check] python3-frozenlist-1.4.0_1: found (/host/binpkgs/aiohttp-socks084-fewer-deps)
[runtime] python3-frozenlist-1.4.0_1: found (/host/binpkgs/aiohttp-socks084-fewer-deps)
...
==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_signals.py ____________________
ImportError while importing test module '/builddir/python3-aiosignal-1.3.1/tests/test_signals.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_signals.py:6: in <module>
    from aiosignal import Signal
aiosignal/__init__.py:1: in <module>
    from frozenlist import FrozenList
E   ModuleNotFoundError: No module named 'frozenlist'
```

Could this have anything to do with the move to Python 3.12?

2023-11-13 15:18 UTC, ar-jan commented
I bumped python3-aiohttp to prerelease 3.9.0b1 for [compatibility with Python 3.12](https://github.com/aio-libs/aiohttp/issues/7639#issuecomment-1751995946). Version 3.8.6 or earlier do not compile.

I don't know why `frozenlist` module cannot be imported in the tests for `python3-aiosignal` (I believe these tests ran successfully before Python 3.12, not sure).

2023-11-13 16:45 UTC, ahesford requested changes

2023-11-13 16:45 UTC, ahesford commented on srcpkgs/python3-aiohttp/template
> +make_check=no # Depends on proxy.py and re_assert
If tests are disabled here because they require dependencies not packaged for Void, the entire list of `checkdepends` should be dropped.

2023-11-13 16:45 UTC, ahesford commented on srcpkgs/python3-aiosignal/template
> +make_check=no # frozenlist ModuleNotFoundError
The tests run fine for me, so there must be something on your end that needs to be resolved. In any case, please reinstate the tests.

2023-11-13 17:34 UTC, ar-jan commented
Updated. After nuking my `masterdir` and `hostdir`, tests using frozenlist worked again. No idea how that got messed up.

2023-11-15 11:35 UTC, ahesford approved these changes
This seems fine to me, notwithstanding my objection to the very existence of the `frozenlist` Python package.

2023-11-26 20:55 UTC, ar-jan commented
Updated to `aiohttp-3.9.1`.

2023-11-26 21:17 UTC, merged