audacity: update to 3.3.3.
void-linux/void-packages pull request #46524
Opened 2023-10-09 10:38 UTC by ii8

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl
- I built this PR locally for these architectures:
  - armv6l-musl

2023-10-09 12:05 UTC, ahesford requested changes

2023-10-09 12:05 UTC, ahesford commented on srcpkgs/audacity/template
> +		echo "/usr/bin/qemu-${XBPS_TARGET_QEMU_MACHINE}-static ${wrksrc}/${build_wrksrc}/Release/bin/image-compiler \$@" >> ${wrksrc}/${build_wrksrc}/scripts/image-compiler
This should be an indented HEREDOC for legibility.
```suggestion
		cat > "${XBPS_WRAPPERDIR}/image-compiler" <<-EOF
			#!/bin/sh
			/usr/bin/qemu-${XBPS_TARGET_QEMU_MACHINE}-static "${wrksrc}/${build_wrksrc}/Release/bin/image-compiler" "\$@"
			EOF
```

2023-10-09 12:05 UTC, ahesford commented on srcpkgs/audacity/template
> +		export PATH="${wrksrc}/${build_wrksrc}/scripts/:$PATH"
No need for this anymore.

2023-10-09 12:05 UTC, ahesford commented on srcpkgs/audacity/template
> +		chmod +x ${wrksrc}/${build_wrksrc}/scripts/image-compiler
Use full numeric permissions for predictability.
```suggestion
		chmod 0755 "${XBPS_WRAPPERDIR}/image-compiler"
```

2023-10-09 14:35 UTC, ii8 commented on srcpkgs/audacity/template
> -CXXFLAGS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
`_LARGEFILE_SOURCE` is redundant. I've added `_FILE_OFFSET_BITS=64` again only for those targets where it has an effect.

2023-10-09 15:12 UTC, ii8 commented
The i686 build is failing, it uses ninja which depends on python and the python tests are failing.
Should I just use make instead of ninja:
```sh
if [ "$XBPS_TARGET_MACHINE" = i686 ]; then                                      
        export CMAKE_GENERATOR="Unix Makefiles"                                 
        make_cmd=make                                                           
fi
```
or is there a better way to fix that?

2023-10-09 15:44 UTC, ahesford commented
Your test is failing because we are in the middle of a massive Python update; the problem is ephemeral and not related to this PR.

2023-10-11 12:13 UTC, ahesford commented on srcpkgs/audacity/template
> -CXXFLAGS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
There's no need for the guard; we have several templates that add these flags, and we always just add them to CXXFLAGS globally.

2023-10-13 01:44 UTC, ii8 commented
Previous attempts for reference: #44662,  #40508

2023-10-13 03:31 UTC, merged