owncloudclient: update to 5.1.0.
void-linux/void-packages pull request #47025
Opened 2023-11-02 17:24 UTC by tornaria

#### Testing the changes
- I tested the changes in this PR: **briefly**

I've been using 5.0.0 for a while, and now updated to 5.1.0.

Note that kde integration (#45352) has been removed.
There is an external project: https://github.com/owncloud/client-desktop-shell-integration-dolphin but I don't use kde and I wouldn't be able to test at all.

It was necessary to build `qtkeychain-qt6` which I copied with obvious changes from `qtkeychain-qt5`. Should this new pkg keep @yopito as maintainer?

2023-11-03 16:19 UTC, tornaria commented
I wonder if `-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins` and `-DECM_MKSPECS_INSTALL_DIR=/usr/lib/qt6/mkspecs` should be in `common/build-style/cmake.sh` just as `-DQT_HOST_PATH=/usr` and `-DQT_HOST_PATH_CMAKE_DIR=/usr/lib/cmake` are.

2024-01-31 22:26 UTC, tornaria commented
Here:
```
--- a/src/sage/features/threejs.py
+++ b/src/sage/features/threejs.py
@@ -61,4 +61,4 @@ class Threejs(StaticFile):
 
 
 def all_features():
-    return [Threejs()]
+    return []
```

2024-04-03 13:10 UTC, ahesford requested changes

2024-04-03 13:10 UTC, ahesford commented on srcpkgs/libre-graph-api-cpp-qt-client/template
> +hostmakedepends="qt6-tools-devel"
Please reconcile with b0a4ed8d2158

2024-04-03 13:10 UTC, ahesford commented on srcpkgs/owncloudclient/template
> +hostmakedepends="pkg-config extra-cmake-modules qt6-tools-devel"
Please reconcile with b0a4ed8d2158

2024-04-03 23:03 UTC, tornaria commented
@ahesford it makes a lot of sense, sorry I missed that. I did it in the four templates. I tested locally the cross-build on aarch64 to make sure I got the `hostmakedepends` right (sometimes `qt6-base` suffices, other times `qt6-tools` is also necessary).

2024-04-05 11:23 UTC, merged