[wip] new package: incus (replaces lxd)
void-linux/void-packages pull request #47573
Opened 2023-12-04 16:30 UTC by dkwo

- I tested the changes in this PR: no
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): yes

@leahneukirchen @CameronNemo #46536 still working on this, maybe you can provide feedback
(I'll update srcpkgs/removed-packages later)

2023-12-24 18:29 UTC, ahesford commented
I don't think we should drop `lxd` in this PR.

2023-12-26 18:05 UTC, dkwo commented
when building incus, i need to update raft, which makes it harder to bump dqlite and lxd.
the current lxd is also outdated, and it hasn't been rebuilt with at least go 1.21 as its distfiles have been moved.

2023-12-26 20:19 UTC, sbromberger commented
I managed to get incus running on void a couple days ago. here's my runit service if it helps:

```
#!/bin/sh
exec 2>&1
_systemd_cgrp="/sys/fs/cgroup/systemd"
if [ ! -d ${_systemd_cgrp} ]; then
        mkdir ${_systemd_cgrp}
fi
if ! mountpoint -q "${_systemd_cgrp}"; then
        mount -t cgroup -o none,name=systemd cgroup ${_systemd_cgrp}
fi

[ -r conf ] && . ./conf
exec /usr/local/bin/incusd --group incus-admin --syslog ${OPTS:- --verbose}
```

2023-12-27 18:39 UTC, dkwo commented
Thanks! Updated incus to 0.4, tried to follow upstream recommendations https://linuxcontainers.org/incus/docs/main/packaging/ which also suggests

> The incusd and incus-user daemons should be kept outside of the user’s PATH. The same is true of incus-agent which needs to be available in the daemon’s PATH but not be visible to users.

how can i keep those daemons outside of path?

2023-12-28 16:46 UTC, sbromberger commented
> how can i keep those daemons outside of path?

Recommendation from folks on #lxc liberachat is to put them in `/usr/sbin`.

2023-12-28 16:49 UTC, sbromberger commented
Would it be possible to make cowsql a separate PR and get that integrated sooner?

2023-12-28 17:29 UTC, ahesford commented
Void is usr-merged and doesn't distinguish between root-visible and user-visible executables. If the executables are intended only for execution by other programs, a subdirectory of `/usr/libexec` is the proper place. Otherwise, just put them in `/usr/bin`.

2023-12-31 15:53 UTC, ahesford commented
> is it ok to add `export PATH=/usr/libexec/incus:$PATH` to the services, so that they know where to find incus-agent?

No. If the programs that use these utilities expect them to be in the system path, then they belong in the standard `/usr/bin`. Programs that use non-user-visible executables should expect to find these utilities in `/usr/libexec` without modifications to the search path. If the upstream suggestion is to put them in `/usr/sbin` to keep them out of the default path of ordinary users (`/usr/sbin` should always be in the default path of the super user), then the answer on Void is that we make no distinction.

2024-01-12 20:40 UTC, classabbyamp commented on srcpkgs/incus/template
> +# temporarily don't build fluidshift, as it conflicts with lxd, lxd-lts
why not rename it to fluidshift-incus or something?

2024-01-12 20:40 UTC, leahneukirchen requested changes

2024-01-12 20:40 UTC, leahneukirchen commented on srcpkgs/incus/template
> +system_groups="incus-admin incus"
Can we use _incus-admin and _incus here?

2024-01-12 20:41 UTC, classabbyamp commented on srcpkgs/incus/template
> +system_groups="incus-admin incus"
why isn't this following the [established convention](https://github.com/void-linux/void-packages/blob/master/Manual.md#creating-system-accountsgroups-at-runtime) for system groups?

2024-01-12 20:41 UTC, classabbyamp commented on srcpkgs/incus/template
> +go_build_tags=libsqlite3
quote this

2024-01-12 20:42 UTC, classabbyamp commented on srcpkgs/incus/files/incus-user/check
> +incus config show >/dev/null 2>&1
should this be exec'd?

2024-01-13 20:30 UTC, classabbyamp commented
squash the two incus commits please

2024-01-17 14:38 UTC, leahneukirchen approved these changes

2024-01-23 18:21 UTC, sbromberger commented
Now that this has been approved, what's the process for getting it merged? (Eagerly awaiting not having to have a custom install of incus!)

2024-01-23 18:56 UTC, merged

2024-01-24 04:36 UTC, sbromberger commented
Erm. Why is `lxc` a dependency here? Incus doesn't require it.

2024-01-24 16:05 UTC, sbromberger commented
I think wget may be a transitive dependency (possibly from lxc). I installed incus from scratch on a test void system with only cowsql and raft as dependencies.

I can try my hand at a PR but I'm unfamiliar with the config files for packaging so I might mess it up. Thanks.