spectrwm: update to 3.5.1, orphan
void-linux/void-packages pull request #47629
Opened 2023-12-06 23:33 UTC by tmtrucco

#### Testing the changes
I tested the changes in this PR: YES

#### Local build testing
I built this PR locally for my native architecture, (ARCH-LIBC)

2023-12-07 01:47 UTC, mhmdanas requested changes
Thanks for your PR! Please don't keep closing your PRs and opening new ones just to make changes to them; instead, amend your commits and force-push to the existing PR branch (see https://www.atlassian.com/git/tutorials/rewriting-history).

2023-12-07 01:47 UTC, mhmdanas commented on srcpkgs/spectrwm/template
> +revision=4
`revision` should be reset to 1 on version bumps.

2023-12-07 01:47 UTC, mhmdanas commented on srcpkgs/spectrwm/template
> +maintainer=" Orphaned <orphan@voidlinux.org>"
Remove the extra space

2023-12-07 02:16 UTC, tmtrucco commented
Sorry for the PR spam! I made the first PR with just the web and couldn't
figure out how to ammend the commit. I started all over again from terminal
with git so I can finally push the ammend. It should be good to go now,
sorry for the inconveniences

On Wed, Dec 6, 2023, 10:47 PM Mohammed Anas ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for your PR! Please don't keep closing your PRs and opening new
> ones just to make changes to them; instead, amend your commits and
> force-push to the existing PR branch (see
> https://www.atlassian.com/git/tutorials/rewriting-history).
> ------------------------------
>
> In srcpkgs/spectrwm/template
> <https://github.com/void-linux/void-packages/pull/47629#discussion_r1418197319>
> :
>
> > @@ -1,7 +1,7 @@
>  # Template file for 'spectrwm'
>  pkgname=spectrwm
> -version=3.4.1
> -revision=3
> +version=3.5.1
> +revision=4
>
> revision should be reset to 1 on version bumps.
> ------------------------------
>
> In srcpkgs/spectrwm/template
> <https://github.com/void-linux/void-packages/pull/47629#discussion_r1418197372>
> :
>
> > @@ -10,11 +10,11 @@ hostmakedepends="pkg-config"
>  makedepends="libXcursor-devel libXft-devel libXrandr-devel libXt-devel
>   xcb-util-keysyms-devel xcb-util-wm-devel"
>  short_desc="Small dynamic tiling window manager for X11"
> -maintainer="Jakub Skrzypnik ***@***.***>"
> +maintainer=" Orphaned ***@***.***>"
>
> Remove the extra space
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/void-linux/void-packages/pull/47629#pullrequestreview-1768953838>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDOOIZH46AKCGLWTNVJSGTDYIEN3ZAVCNFSM6AAAAABAKFNONGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONRYHE2TGOBTHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-10 02:34 UTC, mhmdanas commented
No worries, looks good to me now.

2023-12-19 15:41 UTC, merged