[WIP] labwc: update to 0.7.0
void-linux/void-packages pull request #47876
Opened 2023-12-22 20:29 UTC by tranzystorekk

#### Testing the changes
- I tested the changes in this PR: **YES**

2023-12-22 20:30 UTC, tranzystorekk commented
I've run into crashes when launching `wezterm`, `rio`, `gitk` at the moment.

2023-12-23 02:51 UTC, ahesford commented
I cannot reproduce your problem. I'm running a branch four commits ahead of 0.7.0, none of which would have any bearing on this problem, and can launch all three programs.

2023-12-23 02:53 UTC, ahesford requested changes

2023-12-23 02:53 UTC, ahesford commented on srcpkgs/labwc/template
> +makedepends="cairo-devel glib-devel libpng-devel librsvg-devel libxml2-devel pango-devel wlroots0.17-devel"
Wrap this at 78 characters.

2023-12-23 02:53 UTC, ahesford commented on srcpkgs/labwc/template
>  post_install() {
All of the files installed by `post_install` are already installed in `/usr/share/doc/labwc`. I think this function should just be dropped.

2023-12-23 20:53 UTC, tranzystorekk commented
I'm wondering if we should disregard the vm-specific problems and just merge this anyway...

2023-12-23 21:25 UTC, ahesford commented
I agree that problems in VMware shouldn't block the update, especially because it seems to originate outside of labwc.

2023-12-24 01:17 UTC, merged