New package: gama-1.0.4
void-linux/void-packages pull request #48123
Opened 2024-01-08 14:30 UTC by zen0bit

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x64 glibc

2024-01-08 22:09 UTC, meator requested changes
Remove all commented out variables. Apart from that, I've checked everything and I have not found any other problems. I am unsure whether the repo is GPL-3.0-only or GPL-3.0-or-later because upstream makes no mention of this, but that is a nitpick.

2024-01-09 00:04 UTC, zen0bit commented
> Remove all commented out variables. Apart from that, I've checked everything and I have not found any other problems. I am unsure whether the repo is GPL-3.0-only or GPL-3.0-or-later because upstream makes no mention of this, but that is a nitpick.

Done
question passed upstream

2024-01-09 00:05 UTC, zen0bit reviewed
Done

2024-01-09 03:57 UTC, canack approved these changes
Thank you for your interest in gama! 🚀

2024-01-09 03:57 UTC, canack commented on srcpkgs/gama/template
> +version=1.0.4
Hi, I've released new version. And this version includes new description about license. 📄 
```suggestion
version=1.0.5
```

2024-01-09 10:41 UTC, meator commented
When there is no [mention of "or later", it is GPL-3.0-only](https://www.gnu.org/licenses/identify-licenses-clearly.html) AFAIK. So the previous notice was valid and it was GPL-3.0-only. But the author changed his license making this clear. These two variants are usually differentiated in license comment headers in code itself, but the project doesn't use these.

But I'm not a license expert.

2024-01-09 11:08 UTC, canack commented
Thank you very much for the information. I am not very knowledgeable about licenses, and I will pay more attention to this matter in my future programming processes. 👍🏻

2024-01-25 09:35 UTC, canack commented
Hi 👋🏻 
Gama v1.1.0 has been released : https://github.com/termkit/gama/releases
May you can update the package version 🍀

2024-11-29 02:43 UTC, closed without merging