New package: firebird5-5.0.1.1322~8672410
void-linux/void-packages pull request #48350
Opened 2024-01-24 03:00 UTC by onlylunix

#### Testing the changes
- I tested the changes in this PR: YES

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC, i686-LIBC, x86_64-musl)

New features:
You can now install and run several different versions of Firebird at the same time, including client and development libraries, since the databases require the corresponding server versions.

Made the packages unified. Also see PR https://github.com/void-linux/void-packages/pull/46672

2025-06-08 19:38 UTC, Duncaen requested changes
not a fan of this `INSTALL` script, its barely readable, uses absolute paths instead of relative paths, uses `pwgen` which might not be installed. Does for some reason sets `LD_LIBRARY_PATH`.
chowning all files in `/tmp/firebird` for whatever resaon.

2025-06-08 19:55 UTC, onlylunix commented
> not a fan of this `INSTALL` script, its barely readable, uses absolute paths instead of relative paths, uses `pwgen` which might not be installed. Does for some reason sets `LD_LIBRARY_PATH`. chowning all files in `/tmp/firebird` for whatever resaon.

/tmp/firebird creates the firebird utilities themselves. Nothing bad will happen if pwgen is not installed.
You can remove INSTALL. I automated a quick deployment of the firebird server in it.

2025-06-08 20:15 UTC, onlylunix commented
> not a fan of this `INSTALL` script, its barely readable, uses absolute paths instead of relative paths, uses `pwgen` which might not be installed. Does for some reason sets `LD_LIBRARY_PATH`. chowning all files in `/tmp/firebird` for whatever resaon.

2025-06-08 20:15 UTC, closed without merging

2025-06-08 20:32 UTC, onlylunix commented
Buggy interface, I think I didn't close PR

2025-06-12 05:54 UTC, onlylunix reviewed
very good

2025-07-13 15:21 UTC, onlylunix commented
@Duncaen, I fixed it

2025-08-06 22:37 UTC, onlylunix reviewed
ready

2025-08-09 13:23 UTC, onlylunix commented
@abenson, review please also

2026-04-17 23:35 UTC, onlylunix commented
Reopen https://github.com/void-linux/void-packages/pull/60010