New-package: ironbar-0.14.0
void-linux/void-packages pull request #48502
Opened 2024-02-03 01:54 UTC by caughtquick

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

2024-02-03 21:15 UTC, caughtquick commented
Should I be setting the specific arches where this package builds or is it fine?

2024-02-04 08:58 UTC, oreo639 commented on srcpkgs/ironbar/template
> +makedepends="gtk+3-devel gtk-layer-shell-devel pkg-config"
pkg-config should be in hostmakedpends.

2024-02-04 20:13 UTC, caughtquick commented
I've corrected that issue, and it appears like it's building on all systems now, thanks for the help @oreo639.

2024-02-14 14:41 UTC, ahesford requested changes
Looks like 0.14.1 is out now.

2024-02-14 14:41 UTC, ahesford commented on srcpkgs/ironbar/template
> +	}
Remove indentation of the closing brace.

2024-02-14 15:01 UTC, ahesford commented
Also, I think you should install the contents of the `examples/` directory. The `vsconf` helper is convenient for this.

2024-03-26 00:57 UTC, merged