ruby-tmuxinator: update to 3.1.1.
void-linux/void-packages pull request #48761
Opened 2024-02-16 12:14 UTC by dataCobra

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686

2024-03-24 18:07 UTC, classabbyamp commented on srcpkgs/ruby-tmuxinator/INSTALL.msg
> +Thank you for installing tmuxinator.
this is unnecessary and noisy

2024-03-24 19:31 UTC, ahesford requested changes
Drop the `INSTALL.msg` entirely. We don't use messages to teach people how to use the packages that they install.

2024-03-24 19:33 UTC, ahesford requested changes
Also, ping the maintainer of the package you intend to adopt, who is still an active Void contributor.

2024-03-24 19:38 UTC, dataCobra commented
@egorenar are you fine with me adopting?

2024-03-30 07:02 UTC, dataCobra commented on srcpkgs/ruby-tmuxinator/INSTALL.msg
> +Thank you for installing tmuxinator.
Dropped the INSTALL.msg file.

2024-03-30 07:05 UTC, dataCobra commented
As requested, I have removed the INSTALL.msg file.

I've pinged the current maintainer also and he approved my adoption.

2024-05-07 17:22 UTC, dataCobra commented
Updated PR from 3.1.2 to 3.2.0.

2024-05-07 17:31 UTC, classabbyamp commented on srcpkgs/ruby-tmuxinator/patches/xdg.patch
there's a bunch of changes in this patch that feel unnecessary. can you clean up the diff so it's easier to see what changed?

2024-05-07 17:48 UTC, dataCobra commented on srcpkgs/ruby-tmuxinator/patches/xdg.patch
I assume you mean the XDG config changes?

2024-05-07 18:10 UTC, classabbyamp commented on srcpkgs/ruby-tmuxinator/patches/xdg.patch
the file i commented on, yes

2024-06-10 09:43 UTC, dataCobra commented on srcpkgs/ruby-tmuxinator/patches/xdg.patch
The file should be good to go now.

Please review a last time.

2024-06-10 16:20 UTC, merged