[WIP] New package: Criterion-2.4.2
void-linux/void-packages pull request #50109
Opened 2024-04-29 12:39 UTC by MIvanchev

#### Testing the changes
- I tested the changes in this PR: **NO**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

2024-07-30 06:54 UTC, MIvanchev commented
Bump.

2024-10-29 07:17 UTC, MIvanchev commented
Bump.

2025-01-29 07:50 UTC, MIvanchev commented
Bump.

2025-05-01 16:24 UTC, MIvanchev commented
Bump.

2025-06-08 19:09 UTC, Duncaen commented
This fails to build when rebased.

2025-06-16 07:42 UTC, Rutpiv commented
The build issue was caused by the recent update to CMake 4, which removed compatibility with `CMakeLists.txt` files targeting versions older than 3.5 — as was the case with the version of `nanopb` used in the original wrap.

To fix this, I updated the `nanopb` subproject to version **0.4.9.1** (previously **0.4.7**), along with its corresponding checksum. This version is compatible with CMake 4. With this change, the build completes successfully, and all tests pass as expected.

---

Additionally, I attempted to update `nanomsg` to version 1.2.1, although the Meson wrap requires only version 1.2. While version 1.2 builds and works correctly, version 1.2.1 causes several tests in `Criterion` to fail with SIGABRT.

<details>
<summary>Tests errors</summary>

```bash
=> Criterion-2.4.2_1: running do_check ...
ninja: Entering directory `/builddir/Criterion-2.4.2/Criterion-2.4.2/build'
ninja: no work to do.
 1/19 boxfort / nested.c                        OK              0.02s
 2/19 boxfort / callback.c                      OK              0.02s
 3/19 boxfort / context.c                       OK              0.03s
 4/19 criterion / unit tests                    ERROR           0.07s   killed by signal 6 SIGABRT
>>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=45 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/unit/unit_tests --tap

 5/19 criterion / full / exit.c                 FAIL            0.08s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=89 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/exit.c.bin --always-succeed

 6/19 criterion / full / failmessages.c         FAIL            0.09s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 MALLOC_PERTURB_=116 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/failmessages.c.bin --always-succeed

 7/19 criterion / full / flood.c                OK              0.04s
 8/19 criterion / full / long-messages.c        FAIL            0.05s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=107 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/long-messages.c.bin --always-succeed

 9/19 criterion / full / other-crashes.c        FAIL            0.05s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 MALLOC_PERTURB_=227 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/other-crashes.c.bin --always-succeed

10/19 criterion / full / with-time.c            FAIL            0.05s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=237 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/with-time.c.bin --always-succeed

11/19 criterion / full / bug463.c               FAIL            0.05s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=150 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/bug463.c.bin --always-succeed

12/19 criterion / full / theories_regression.c  OK              0.06s
13/19 criterion / full / exception.cc           FAIL            0.09s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=119 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/exception.cc.bin --always-succeed

14/19 criterion / full / exit.cc                FAIL            0.09s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 MALLOC_PERTURB_=114 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/exit.cc.bin --always-succeed

15/19 criterion / full / failmessages.cc        FAIL            0.09s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 MALLOC_PERTURB_=241 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/failmessages.cc.bin --always-succeed

16/19 criterion / full / long-messages.cc       FAIL            0.06s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=100 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/long-messages.cc.bin --always-succeed

17/19 criterion / full / other-crashes.cc       FAIL            0.05s   killed by signal 6 SIGABRT
>>> LD_LIBRARY_PATH=/builddir/Criterion-2.4.2/Criterion-2.4.2/build/src ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=127 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 /builddir/Criterion-2.4.2/Criterion-2.4.2/build/test/full/other-crashes.cc.bin --always-succeed

18/19 criterion / full / theories_regression.cc OK              0.06s
19/19 boxfort / timeout.c                       OK              2.01s

Ok:                 7   
Expected Fail:      0   
Fail:               12  
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```
</details>

These errors do not occur with `nanomsg versions 1.1.5 or 1.2, which both build and pass the test suite successfully.

2025-06-16 08:36 UTC, MIvanchev commented
Where did you update nanopb @Rutpiv ?

2025-06-16 09:23 UTC, Rutpiv commented
I updated `nanopb` directly inside the `Criterion` template you provided, as the patch structure suggests it sources the files directly from there. Glad to hear our findings align — let me know if there’s anything else I can help with.

2025-09-15 02:43 UTC, Rutpiv commented
Bump.

2025-09-15 05:39 UTC, MIvanchev commented
@Rutpiv I forgot to answer you, I'll test this asap and commit, thank you, sorry!!!

2025-09-21 17:02 UTC, Rutpiv commented
No worries, take your time. Thanks for letting me know!

2025-11-13 20:15 UTC, Rutpiv commented
`Criterion` has released version 2.4.3, which now depends on `nanomsg` 1.2.2 in its Meson wrap.
I have opened a PR updating `nanomsg` to 1.2.2 to match this new requirement: void-linux/void-packages#57875.

2025-12-18 21:39 UTC, MIvanchev commented
Thanks for all your effort @Rutpiv, maybe we'll get this released!

2025-12-20 21:35 UTC, Rutpiv commented
Thanks for the kind words, and thank you as well for driving this forward.
Really looking forward to seeing this land in the repository.

2026-05-10 05:26 UTC, Rutpiv commented
Bump.

2026-05-10 14:42 UTC, Duncaen requested changes

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/template
> +skip_extraction="debugbreak klib nanopb BoxFort"
Those need to be filenames.

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/template
> +	https://github.com/Snaipe/BoxFort/archive/refs/tags/v${_BoxFortver}.tar.gz>BoxFort.tar.gz"
Indent with one space inside variables.

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/template
> +	https://github.com/Snaipe/BoxFort/archive/refs/tags/v${_BoxFortver}.tar.gz>BoxFort.tar.gz"
I usually prefer to have the version or the commit in the renamed filenames.

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/template
> +homepage="https://github.com/Snaipe/Criterion"
```suggestion
homepage="https://github.com/Snaipe/Criterion"
changelog="https://raw.githubusercontent.com/Snaipe/Criterion/refs/heads/bleeding/ChangeLog"
```

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/template
> +	depends="Criterion>=${version}_${revision}"
```suggestion
	depends="${sourcepkg}>=${version}_${revision}"
```

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/template
> +build_wrksrc=${pkgname}-${version}
You don't need a separate `build_wrksrc` if `skip_extraction` is fixed.

2026-05-10 14:42 UTC, Duncaen commented on srcpkgs/Criterion/patches/wraps.patch
I don't think this is how you supposed to provide your own sources for wrap subprojects. Pretty you can just put the files in place and the build styles `--wrap-mode=nodownload` stops it from pulling with git.

2026-06-05 13:24 UTC, MIvanchev commented
@Duncaen many thanks, let me address them :)

2026-06-13 14:22 UTC, MIvanchev commented on srcpkgs/Criterion/template
> +build_wrksrc=${pkgname}-${version}
Tried `skip_extraction="debugbreak.tar.gz klib.tar.gz nanopb.tar.gz BoxFort.tar.gz"` without `build_wrksrc`; error upon build.

2026-06-13 14:22 UTC, MIvanchev commented on srcpkgs/Criterion/template
> +homepage="https://github.com/Snaipe/Criterion"
Done, thanks.

2026-06-13 14:22 UTC, MIvanchev commented on srcpkgs/Criterion/template
> +	https://github.com/Snaipe/BoxFort/archive/refs/tags/v${_BoxFortver}.tar.gz>BoxFort.tar.gz"
I'd rather have them additional info :D

2026-06-13 14:23 UTC, MIvanchev commented on srcpkgs/Criterion/template
> +	https://github.com/Snaipe/BoxFort/archive/refs/tags/v${_BoxFortver}.tar.gz>BoxFort.tar.gz"
Done, thanks!

2026-06-13 14:23 UTC, MIvanchev commented on srcpkgs/Criterion/template
> +skip_extraction="debugbreak klib nanopb BoxFort"
Tried `skip_extraction="debugbreak.tar.gz klib.tar.gz nanopb.tar.gz BoxFort.tar.gz"` without `build_wrksrc`; error upon build.

2026-06-13 14:25 UTC, MIvanchev commented on srcpkgs/Criterion/patches/wraps.patch
Where is this option supposed to be provided?

2026-06-13 18:30 UTC, Duncaen commented on srcpkgs/Criterion/patches/wraps.patch
https://github.com/void-linux/void-packages/blob/a25bbae3aaf693c7305ee17c113708392bf405a9/common/build-style/meson.sh#L39

2026-06-13 18:31 UTC, Duncaen commented on srcpkgs/Criterion/template
> +skip_extraction="debugbreak klib nanopb BoxFort"
you did not use the full filename.

2026-06-13 18:31 UTC, Duncaen commented on srcpkgs/Criterion/template
> + https://github.com/MrAnno/debugbreak/archive/${_debugbreakcommit}.tar.gz>debugbreak.tar.gz
Those renamed archives should probably include the version or commit.

2026-06-13 19:07 UTC, MIvanchev commented
Thanks @Duncaen, I should do more packages again :)

2026-06-13 21:20 UTC, merged