incus: update to 6.1
void-linux/void-packages pull request #50251
Opened 2024-05-08 23:22 UTC by dkwo

I still need to test this.

2024-05-09 14:09 UTC, dkwo commented
to do: add a readme.void mentioning incus groups, subpackages and perhaps
`echo "root:1000000:1000000000" | doas tee -a /etc/subuid /etc/subgid`
and maybe also set CGROUP_MODE in rc.conf to unified instead of hybrid.

2024-05-23 00:29 UTC, dkwo commented
@ahesford can you take a look at this one as well?

2024-06-04 19:09 UTC, sbromberger commented
Hi all,

6.2 was just released - any way we might just bump the version here?

2024-06-04 20:00 UTC, ahesford requested changes
I don't have any experience with incus, but I've made a few suggestions to improve the readme and variable handling in the template.

2024-06-05 12:30 UTC, dkwo commented
Thanks!  Implemented the suggestions and updated to 6.2

2024-06-05 12:40 UTC, dkwo commented on srcpkgs/incus/files/README.voidlinux
> +unified instead of hybrid.
done.

2024-06-05 12:42 UTC, dkwo commented
Still failing on 32 bit. I thought that patch had been merged in v6.2
is anyone actually using incus on those archs? I wonder if it's worth it supporting them..

2024-06-05 17:22 UTC, dkwo commented
the patch fixes 32 bit. i'll leave this as draft until it is merged upstream.

2024-06-06 20:27 UTC, dkwo commented
patch now merged upstream.

2024-06-06 20:42 UTC, merged

2024-06-06 22:11 UTC, sbromberger commented
Thank you both!