vaultwarden: update to 1.31.0; vaultwarden-web: update to 2024.5.1b.
void-linux/void-packages pull request #51188
Opened 2024-07-10 03:48 UTC by TinfoilSubmarine

#### Testing the changes
- I tested the changes in this PR: **YES**

2024-07-11 02:10 UTC, ahesford commented on common/build-style/cargo.sh
>  		${configure_args} ${make_check_args}
I think this change merits discussion in a separate PR.

2024-07-11 16:03 UTC, ahesford requested changes
There's no need for indirection with the function overrides.

2024-07-11 16:03 UTC, ahesford commented on srcpkgs/vaultwarden/template
> +		${make_cmd} build --locked --target ${RUST_TARGET} ${configure_args}
```suggestion
		cargo auditable build --locked --target ${RUST_TARGET} ${configure_args}
```

2024-07-11 16:03 UTC, ahesford commented on srcpkgs/vaultwarden/template
> +			${configure_args} ${make_check_args}
```suggestion
		cargo auditable test --locked --target ${RUST_TARGET} \
			${configure_args} ${make_check_args}
```

2024-07-11 17:34 UTC, TinfoilSubmarine commented
> There's no need for indirection with the function overrides.

fixed

2024-07-12 17:11 UTC, closed without merging

2024-07-12 17:12 UTC, ahesford commented
Thanks!