New template: ocean-sound-theme
void-linux/void-packages pull request #51845
Opened 2024-08-14 14:10 UTC by hunt3r0one

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

2024-08-14 15:43 UTC, Johnnynator requested changes

2024-08-14 15:43 UTC, Johnnynator commented on srcpkgs/ocean-sound-theme/template
> +distfiles="https://invent.kde.org/plasma/${pkgname}/-/archive/v${version}/${pkgname}-v${version}.tar.gz"
```suggestion
distfiles="${KDE_SITE}/plasma/${version}/${pkgname}-${version}.tar.xz"
```

2024-08-14 15:43 UTC, Johnnynator commented on srcpkgs/ocean-sound-theme/template
> +license="custom:multiple"
```suggestion
license="CC-BY-SA-4.0"
```

(CI stuff is `CC0-1.0` but not used from us, CMake stuff is `BSD-2-Clause` but not installed, so not really important for the final package)

2024-08-15 12:38 UTC, ahesford commented
The commit message should be

    New package: ocean-sound-theme-6.1.4

2024-12-01 02:12 UTC, closed without merging

2025-01-30 00:09 UTC, hunt3r0one commented
How come it was never accepted?