Signal-Desktop: update to 7.23.0.
void-linux/void-packages pull request #52141
Opened 2024-09-07 23:06 UTC by MouadCharradi

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

Using `yarn` to build the package resulted in many errors, so I decided to use `npm` instead (I copied the commands from the way Arch Linux does it). I also added a desktop that I copied from `/usr/share/applications`, since I got a build error saying that it was not found without it.

This still needs some testing,
People who might know about this more than me, any suggestions are welcome. Thanks

2024-09-15 18:02 UTC, classabbyamp commented
7.24.1 is available

2024-09-15 18:04 UTC, classabbyamp requested changes

2024-09-15 18:04 UTC, classabbyamp commented on srcpkgs/Signal-Desktop/files/signal-desktop.desktop
do not vendor desktop files like this (#49164). there is a script somewhere in the source that will generate it

2024-09-15 18:57 UTC, lawmanuk commented
> 7.24.1 is available

i couldn't find this via xbps?

Please advise how to install latest version.  (super beginner question).

thx

2024-09-15 19:10 UTC, classabbyamp commented
i was talking to the author of the PR about available upstream versions. this isn't available with xbps until this is merged

2024-09-16 05:12 UTC, MouadCharradi commented on srcpkgs/Signal-Desktop/files/signal-desktop.desktop
Thank you for point that out, I managed to make the script use the upstream `.desktop` file.
Also the package is now at the latest version, so hopefully the build passes.

Thanks

2024-09-18 02:10 UTC, merged