Kobo Clara ereader support
void-linux/void-packages pull request #52331
Opened 2024-09-24 09:18 UTC by Emru1

#### Testing the changes
- I tested the changes in this PR: **IN PROGRESS**

Those packages provide kernel for Kobo Clara ereader, WiFi driver, screen firmware extractor and some tools needed to run https://github.com/bjesus/air as DE

Still work in progress, comments will be appreciated

2024-09-25 12:55 UTC, Emru1 commented
ditched `tinydm` and `autologin`
`kobo-firmware-extractor` uses SPDX MIT in source files, but does not provide `LICENSE` file
I was *almost* able to run everything, but screen rotation under Xorg is not working as intended (no idea why, under PostmarketOS it works okay).
There is some problems with screen when using wlroots-based compositors (https://github.com/swaywm/sway/issues/7035)

2024-09-25 13:34 UTC, ahesford requested changes
Please move the `lisgd` and `svkbd` packages to separate PRs (one for each), as they are not fundamentally connected to the rest of this request.

2024-09-25 13:34 UTC, ahesford commented on srcpkgs/svkbd/patches/ctrl.patch
> + 	{ "↲ Enter", 0, XK_Return, 2 },
Why does this patch exist? If it is from upstream, please use a properly formatted patch to maintain provenance. If it is not upstream, we don't want it.

2024-09-25 23:02 UTC, classabbyamp commented on srcpkgs/kobo-clara-linux/patches/soc-qcom-add-in-kernel-pd-mapper-implementation.patch
definitely not needed for this device

2024-09-26 09:19 UTC, Emru1 commented on srcpkgs/kobo-clara-linux/patches/soc-qcom-add-in-kernel-pd-mapper-implementation.patch
I wasn't sure how I should do kernel package, so I just copied existing linux6.10 and modified it
thanks

2024-10-02 11:45 UTC, akemnade commented
> ditched `tinydm` and `autologin` `kobo-firmware-extractor` uses SPDX MIT in source files, but does not provide `LICENSE` file I was _almost_ able to run everything, but screen rotation under Xorg is not working as intended (no idea why, under PostmarketOS it works okay). There is some problems with screen when using wlroots-based compositors ([swaywm/sway#7035](https://github.com/swaywm/sway/issues/7035))


Xorg has a bug regarding rotation damage area calculation, fix is upstream, but not apparently not in a release.
See:

 https://gitlab.alpinelinux.org/alpine/aports/-/commit/1c819e599bbd920110cfda7ef7b4221b5b921890

2024-10-02 16:13 UTC, Emru1 commented
Thanks @akemnade, I've added this patch and now my screen works as intended

2024-10-02 18:19 UTC, akemnade commented
btw: what do you do about u-boot? I think having the board revision detection logic from pmOS would be vital so people do not toast there reader. (rev a vs b)

2024-10-31 12:11 UTC, Emru1 commented
I have not put much thought about it. For now, I had just taken already working SD card with pmOS, ripped out root partition and pmOS kernel, and reinstalled it with Void. When I have some time, I'll try to do clean install with Void.

2025-01-16 20:04 UTC, Emru1 commented
thanks @hrdl-github, I've already updated to 6.11, so when it's merged (I assume you're merging to @akemnade repo), I'll give it a try

2025-01-17 13:20 UTC, akemnade commented
I will probably rebase the kobo kernel stuff upon 6.13 some time next week and include that drm fix

2025-01-17 16:02 UTC, Emru1 commented
Thanks @akemnade
I'm not proficient about linux kernel, but would it possible to extract bits from your branch as out-of-tree drivers and use mainline kernel? I don't think so (763 changed files), but maybe I'm wrong

2025-01-28 23:30 UTC, akemnade commented
I updated my kernel stuff and also did a MR to pmOS: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6102

2025-01-28 23:33 UTC, akemnade commented
so for comparison:

$ git diff v6.13 --stat | tail -n 1
 60 files changed, 17505 insertions(+), 44 deletions(-)

2025-07-11 02:14 UTC, closed without merging