incus: enable installing client without the daemon
void-linux/void-packages pull request #52384
Opened 2024-09-27 23:03 UTC by duskmoss

incus-client is intended to be installed without the daemon to use to control remove incus servers. incus the daemon can't me used without the client, at least to authorize another client's to access the API.

I moved incus-user to the daemon package because it's a daemon and not part of the client.

readme: I also removed the information about subuid and subgid because void sets these up out of the box.

readme: I changed "and" to "or" because the two groups grant you access to the daemons in different privelege levels.

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture:
x86_64-glibc
- I built this PR locally for these architectures:
x86_64-musl
(cross) aarch64-musl 
(cross) armv7l
(cross) armv6l-musl

2024-09-27 23:22 UTC, duskmoss commented
@dkwo 

If you could take a look at let me know what you think I'd appreciate it, willing to make changes, especially to content of readme.  I also have opened a PR for handbook docs https://github.com/void-linux/void-docs/pull/815 and we can discuss what information should exist in readme vs handbook.

2024-09-28 14:08 UTC, dkwo commented
Hey, the changes to incus make sense to me, thanks!
About the readme, could you leave the subuid/subgid part?

I was also thinking it'd be useful to have man pages, something like
```
vtargetrun incus manpage --all --format=man /target/path
vman /target/path
```
Can you try adding this?

2024-09-28 19:22 UTC, duskmoss commented
Sure! I'll work on getting the manpages added this weekend. 

For the subuid/subguid, I can leave it in.  Maybe I should add something about checking current /etc/subuid /etc/subguid? 

Might not be necessary since if people do run it it'll hopefully be a no op, since [base-files](https://github.com/void-linux/void-packages/blob/master/srcpkgs/base-files/files/subuid) matches the range the read me suggests.

2024-09-29 13:31 UTC, dkwo commented
Hey, this looks good to me.
I think it's better to move a discussion about readme into the docs pr, so i'd leave the readme as is here.

Should some man pages go into the tools subpkg?
Can you post the output of `xls incus`, xls incus-client etc,
to make sure they are going to the right place?

2024-09-29 16:15 UTC, duskmoss commented
There are no man pages for "fuidshift-incus lxc-to-incus lxd-to-incus incus-benchmark incus-migrate incus-simplestreams" So it looks like they all go in the incus-client to me.


incus-tools
```
/usr/bin/fuidshift-incus
/usr/bin/incus-benchmark
/usr/bin/incus-migrate
/usr/bin/incus-simplestreams
/usr/bin/lxc-to-incus
/usr/bin/lxd-to-incus
```
incus
```
/etc/sv/incus/check
/etc/sv/incus/log/run
/etc/sv/incus/run
/etc/sv/incus-user/log/run
/etc/sv/incus-user/run
/usr/bin/incus-agent
/usr/libexec/incus/incus-user
/usr/libexec/incus/incusd
/usr/share/doc/incus/README.voidlinux
/etc/sv/incus/log/supervise -> /run/runit/supervise.incus-log
/etc/sv/incus/supervise -> /run/runit/supervise.incus
/etc/sv/incus-user/log/supervise -> /run/runit/supervise.incus-user-log
/etc/sv/incus-user/supervise -> /run/runit/supervise.incus-user
```
incus-client 
https://0x0.st/Xguv.txt

2024-09-30 13:53 UTC, dkwo commented
You're right, and this looks good to me. Thanks!

2024-09-30 17:00 UTC, duskmoss commented
yw, thanks for the feedback!

2024-10-01 18:07 UTC, ahesford commented
The commit message would more aptly be something along the lines of

    incus: move incus-user service to main package, install man pages

2024-10-01 18:24 UTC, ahesford requested changes

2024-10-01 18:24 UTC, ahesford commented on srcpkgs/incus/template
> +depends="lxc acl acl-progs rsync squashfs-tools xz dnsmasq iptables attr-progs ${pkgname}-client-${version}_${revision}"
Break lines at 80 columns.

2024-10-01 18:24 UTC, ahesford commented on srcpkgs/incus/template
> +	done
```suggestion
	#generate man pages
	mkdir man
	vtargetrun ${_incus} manpage --all --format=man man
	
	local _manpage _prefix _suffix
	for _manpage in man/*; do
		_prefix="${_manpage%.*}"
		_suffix="${_manpage##*.}"
		[ "${_suffix}" != "${_manpage}" ]
		mv "${_manpage}" "${_prefix//./-}.{_suffix}"
	done
```

2024-10-01 18:24 UTC, ahesford commented on srcpkgs/incus/template
> +		for _manpage in ${wrksrc}/man/*; do
```suggestion
		for _manpage in man/*; do
```

2024-10-01 19:01 UTC, ahesford commented on srcpkgs/incus/template
> +	done
Try this:

```bash
# rename pages with multiple dots
for _manpage in man/*.*.*; do
    [ -f "${_manpage}" ] || continue
    _prefix="${_manpage%.*}"
    _suffix="${_manpage##*.}"
    mv "${_manpage}" "${_prefix//./-}.${_suffix}"
done
```

2024-10-01 21:33 UTC, duskmoss commented
Summarizing a quick conversation on IRC:

-> maybe man page naming should be changed up stream
-> the man pages have the same information as --help  so maybe it's not worth it. (per https://linuxcontainers.org/incus/docs/main/packaging/#manual-pages )

There seem to be a few ways to move forward. 

1) Merge  with the man pages change
   a) I get them fixed upstream we can remove the renaming logic when we version bump
   b) We decide the renaming we're doing is fine for now 
2) Merge the original changes but leave the man pages out
   a) Decide not to care about including the man pages 
   b) I work on getting the files renamed upstream, and we add them after that.
   
I don't mind whichever direction we want to take, but If there's a lot of debate I'd rather merge the original changes and decide what to do about man pages separately. 

@ericonr @classabbyamp  @dkwo

2024-10-01 21:49 UTC, classabbyamp commented
300+ manpages just for regurgitated `--help` seems like a bit much

2024-10-01 21:59 UTC, duskmoss commented
I saved the other commit on a local branch, so can bring the man page changes back if we need it, but here's the PR without adding man pages

2024-10-02 14:13 UTC, dkwo commented
I'm fine either way about man pages.

2024-10-03 20:14 UTC, duskmoss commented
@dkwo  I'm running the 6.6 update now to test,  and have added it to this PR, unless you'd rather have it in a separate one.

2024-10-05 18:22 UTC, dkwo commented
v6.6 works fine for me.

2024-10-06 01:56 UTC, duskmoss commented
It's also been solid for me. Tested some vm stuff too just in case.

2024-10-06 19:23 UTC, closed without merging