mupen64plus: update to 2.6.0
void-linux/void-packages pull request #53109
Opened 2024-11-17 19:14 UTC by M374LX

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

#### Notes
- As the Boost libraries are no longer required, they have been removed from the dependencies.
- Two of the patches have been removed because the new version incorporates the respective changes.

#### Pending checks
- For some reason, the launcher (mupen64plus-ui-console) still displays 2.5.9 as the version number, although the core library (mupen64plus-core) displays 2.6.0, as expected.
- The "ui-console-pic" patch might need to be updated.

2024-11-26 15:29 UTC, zlice commented
commits need squashed

also had this a while back when i started using RMG - https://github.com/void-linux/void-packages/compare/master...zlice:void-packages:mupen-arm

aarch64 glibc seems to build fine for me on top of your 2.6.0

the `archs` can probably just be removed from template?

`source/mupen64plus-core/projects/unix/Makefile` may need something for musl or im doing it wrong?

2024-12-01 00:34 UTC, M374LX commented
@zlice If you built the musl package from a virtual machine, you might need to increase the amount of RAM. I have just tried a musl build from a virtual machine and it failed at first. The problem turned out to be too little RAM and increasing it was enough for the build to be successful. In my case, the increase was from 512 MB to 2 GB.

2025-01-09 22:55 UTC, Johnnynator requested changes
Maybe also import the cross build patch that zlice linked

2025-01-09 22:55 UTC, Johnnynator commented on srcpkgs/mupen64plus/template
>  nopie=yes
`nopie` can be removed

2025-01-09 22:55 UTC, Johnnynator commented on srcpkgs/mupen64plus/template
>  nopie=yes
Same with `CFLAGS="-fcommon"` some lines down

2025-02-15 23:24 UTC, M374LX commented
With the ARM architecture now supported, as seen in https://github.com/mupen64plus/mupen64plus-video-glide64mk2/blob/eb6484ee309f2aa4dfeff44c4fdd3755c97f812d/projects/unix/Makefile#L111, a cross-build patch is ideally not needed, but I am waiting for someone with access to an ARM machine to test.

2025-05-31 02:09 UTC, closed without merging