New package: supersonic-0.13.2
void-linux/void-packages pull request #53632
Opened 2024-12-22 18:09 UTC by fanyx

Resolves #53617 

#### Testing the changes
- I tested the changes in this PR: **NO**(t yet, i can get to after the holidays)

@tommyalatalo Feel free to test, if you are able

Might be missing runtime dependencies.

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

2024-12-22 18:23 UTC, tommyalatalo commented
Hi, thanks for creating this template!
It builds and installs successfully, but the application errors when trying to start it.
For what it's worth I checked out the same package from nix package manager, and it fails with the same error.
```
❯ supersonic
2024/12/22 19:20:49 Error reading app config file: open /home/tommy/.config/supersonic/config.toml: no such file or directory
2024/12/22 19:20:49 Starting supersonic...
2024/12/22 19:20:49 Using config dir: /home/tommy/.config/supersonic
2024/12/22 19:20:49 Using cache dir: /home/tommy/.cache/supersonic
2024/12/22 19:20:50 failed to load theme file "": open /home/tommy/.config/supersonic/themes: no such file or directory
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: GLX: No GLXFBConfigs returned
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an invalid error was not accepted by the caller: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig
go-gl/glfw: Please report this in the Go package issue tracker.
panic: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0xc000019728, 0x2, 0x1d7a4770?})
        github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/error.go:181 +0x225
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0xa, 0xa, {0xf0e3e4?, 0xe?}, 0x0, 0x0)
        github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/window.go:349 +0x15d
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1()
        fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/window_desktop.go:751 +0x11f
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0x0?)
        fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/loop.go:45 +0xd0
fyne.io/fyne/v2/internal/driver/glfw.(*window).create(0xc000441180)
        fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/window_desktop.go:723 +0x56
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).SetSystemTrayMenu.func1()
        fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/driver_desktop.go:71 +0xfb
sync.(*Once).doSlow(0xedaa20?, 0x1f6a401?)
        sync/once.go:76 +0xb4
sync.(*Once).Do(...)
        sync/once.go:67
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).SetSystemTrayMenu(0xc000476c30, 0xc00080c6f0)
        fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/driver_desktop.go:42 +0x4d
fyne.io/fyne/v2/app.(*fyneApp).SetSystemTrayMenu(0xeff74c?, 0xc00080c6f0?)
        fyne.io/fyne/v2@v2.5.0/app/app_xdg.go:105 +0x3c
github.com/dweymouth/supersonic/ui.(*MainWindow).SetupSystemTrayMenu(0xc000400880, {0xf0808f, 0xa}, {0x107e538?, 0xc0002ae820})
        github.com/dweymouth/supersonic/ui/mainwindow.go:268 +0x92c
github.com/dweymouth/supersonic/ui.NewMainWindow({0x107e538, 0xc0002ae820}, {0xc0000b2688?, 0xc0000b2698?}, {0xf0808f, 0xa}, {0xf01b1a, 0x6}, 0xc000381508)
        github.com/dweymouth/supersonic/ui/mainwindow.go:60 +0x306
main.main()
        github.com/dweymouth/supersonic/main.go:53 +0x293
```

2024-12-22 18:43 UTC, fanyx commented
thanks for checking so fast!
i'll have a look once i get on my laptop.

2024-12-22 19:12 UTC, matthewbeaudoin commented
I've been using Supersonic with a build template based on #47986 for a few while now, and I've had no problems building and running v0.13.2.

2024-12-22 22:05 UTC, tommyalatalo commented
Ah yes sorry, scratch all I said above, I'm an idiot... I still had the nix package installed and accidentally started that instead of the void package.

The void package works, the only thing I would say I'm missing is an application shortcut so that it can be started from a launcher and not just from the cli, would that be possible to include?

2024-12-23 13:35 UTC, fanyx commented
I'll add the application shortcut, similar to matthew's solution.

@matthewbeaudoin where do you get the dependency on libsecret and libayatana-appindicator in you template?
I don't see them listed on the github install docs and it works without just fine.

2025-03-24 08:15 UTC, tommyalatalo commented
This is still relevant, anything still needed to merge?

2025-04-08 09:47 UTC, matthewbeaudoin commented
I'm now running v0.15.1 with the following build template:

```
# Template file for 'supersonic-desktop'
pkgname=supersonic-desktop
version=0.15.1
revision=1
build_style=go
go_import_path="github.com/dweymouth/supersonic"
go_build_tags="wayland"
hostmakedepends="pkg-config gcc"
makedepends="mpv-devel libXcursor-devel libXxf86vm-devel"
short_desc="Full-featured, mpv-based music player for Subsonic and Jellyfin servers"
maintainer="Michał Szmidt <michal.sz@disroot.org>"
license="GPL-3.0-or-later"
homepage="https://github.com/dweymouth/supersonic"
distfiles="https://github.com/dweymouth/supersonic/archive/refs/tags/v${version}.tar.gz"
checksum=14816a197151660b439361d271dd09cfb9c882a62fe2b2e795dbc04b72798531

post_install() {
	# go install command has no possibility to change name
	# https://github.com/golang/go/issues/47176
	# There is confilicting supersonic package on GitHub, see repology
	# https://repology.org/projects/?search=supersonic
	mv ${DESTDIR}/usr/bin/supersonic "${DESTDIR}/usr/bin/supersonic-desktop"
	vinstall res/appicon.png 644 usr/share/pixmaps supersonic-desktop.png
	vinstall res/supersonic-desktop.desktop 644 usr/share/applications
}
```
The only build-time dependencies that I found were required for a successful build are `makedepends="mpv-devel libXcursor-devel libXxf86vm-devel"` (the latter two are only necessary when _not_ using `go_build_tags="wayland"` but would need to be included for compatibility [?]).

However, it fails when building with the `-Q` (check) flag: 
```
=> supersonic-desktop-0.15.1_1: running do_check ...
# github.com/go-gl/glfw/v3.3/glfw
In file included from _build-supersonic-desktop-xbps/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/c_glfw_lin.go:10:
_build-supersonic-desktop-xbps/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/glfw/src/wl_window.c:29: warning: "_GNU_SOURCE" redefined
   29 | #define _GNU_SOURCE
      | 
<command-line>: note: this is the location of the previous definition
# github.com/dweymouth/supersonic/ui/browsing
ui/browsing/trackspage.go:213:4: log.Println call has possible Printf formatting directive %v
?   	github.com/dweymouth/supersonic	[no test files]
?   	github.com/dweymouth/supersonic/backend	[no test files]
?   	github.com/dweymouth/supersonic/backend/ipc	[no test files]
?   	github.com/dweymouth/supersonic/backend/mediaprovider	[no test files]
?   	github.com/dweymouth/supersonic/backend/mediaprovider/helpers	[no test files]
?   	github.com/dweymouth/supersonic/backend/mediaprovider/jellyfin	[no test files]
?   	github.com/dweymouth/supersonic/backend/mediaprovider/subsonic	[no test files]
?   	github.com/dweymouth/supersonic/backend/player	[no test files]
?   	github.com/dweymouth/supersonic/backend/player/dlna	[no test files]
?   	github.com/dweymouth/supersonic/backend/player/jukebox	[no test files]
?   	github.com/dweymouth/supersonic/backend/player/mpv	[no test files]
?   	github.com/dweymouth/supersonic/backend/util	[no test files]
?   	github.com/dweymouth/supersonic/res	[no test files]
ok  	github.com/dweymouth/supersonic/sharedutil	0.001s
?   	github.com/dweymouth/supersonic/ui	[no test files]
FAIL	github.com/dweymouth/supersonic/ui/browsing [build failed]
?   	github.com/dweymouth/supersonic/ui/controller	[no test files]
?   	github.com/dweymouth/supersonic/ui/dialogs	[no test files]
?   	github.com/dweymouth/supersonic/ui/layouts	[no test files]
?   	github.com/dweymouth/supersonic/ui/shortcuts	[no test files]
?   	github.com/dweymouth/supersonic/ui/theme	[no test files]
ok  	github.com/dweymouth/supersonic/ui/util	0.032s
?   	github.com/dweymouth/supersonic/ui/visualizations	[no test files]
?   	github.com/dweymouth/supersonic/ui/widgets	[no test files]
FAIL
=> ERROR: supersonic-desktop-0.15.1_1: do_check: '${make_check_pre} go test -p "$XBPS_MAKEJOBS" -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${make_check_args} ${make_check_target}' exited with 1
=> ERROR:   in do_check() at common/build-style/go.sh:66
```

Despite this issue, I have no unexpected problems with the software in day-to-day use having built it from the above build template (and no `-Q` flag).

2025-06-02 01:10 UTC, Duncaen requested changes
please update

2025-06-04 14:43 UTC, fanyx commented
Backported https://github.com/dweymouth/supersonic/commit/989bc886466076d452914d746c150eb0ae91c9c7 to fix build tests.

2025-06-04 14:55 UTC, merged