jadx: install desktop entry
void-linux/void-packages pull request #53772
Opened 2024-12-31 12:48 UTC by Bnyro

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

cc @abenson

2024-12-31 17:30 UTC, classabbyamp requested changes

2024-12-31 17:30 UTC, classabbyamp commented on srcpkgs/jadx/files/jadx-gui.desktop
we should not be vendoring or inventing our own desktop files #49164

2025-01-01 10:35 UTC, Bnyro commented on srcpkgs/jadx/files/jadx-gui.desktop
I'll see if I can upstream it then

2025-01-01 18:14 UTC, Bnyro commented on srcpkgs/jadx/files/jadx-gui.desktop
The desktop file is upstreamed. Should we wait for the next release or add the desktop file addition as a patch?

2025-01-01 18:16 UTC, classabbyamp commented on srcpkgs/jadx/files/jadx-gui.desktop
we could add it as a patch, I guess

2025-04-02 08:11 UTC, Bnyro commented
bump

2025-06-03 18:28 UTC, Bnyro commented
With the 1.5.2 release, the desktop file no longer needs to be patched since it's upstreamed now.

2025-06-03 19:50 UTC, merged